OfficeDev/office-js-docs-pr

docs/excel/performance.md

Misc comments:
- links within the same doc set should use relative paths (not complete URLs) -- I've updated links accordingly
- the distinction between `relationships` and `properties` will be going away soon (when we start auto-generating docs), so I've removed mention of 'relationships' in this article.
- `Note` formats in OPS use a special markdown syntax -- I've updated the note in this article to use that syntax.
Also, maybe consider adding code samples for the **Suspend calculation temporarily** section and the **Convert between range and table** section?

Minor edits.

---

docs/excel/excel-add-ins-events.md

Seems like this was omitted accidentally. Updating the docs accordingly.
https://dev.office.com/reference/add-ins/excel/settingcollection#events

Adding an entry for onSettingsChanged

---

docs/design/content-add-ins.md

Some links had the en-us localization already inserted. One link was pointing to a renamed file.

Fixing links

---

docs/excel/excel-add-ins-data-validation.md

All but one of these broken links is to one or another of the data validation preview APIs. This doesn't _fix_ the links to. It points them to the URLs that _will be_ correct when we publish the Excel 1.8 Data Validation APIs (when they GA). But the links will be broken until then.

dealing with broken links in the Excel data validation article

---

docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md
docs/testing/sideload-office-addin-using-sideload-command.md

The React tutorial also creates a manifest.json file in a public folder which seemed like it should be the manifest file to me as a first go through of this. However, turns out they want you to select my-office-addin-manifest.xml, which I totally didn't even see because of the name. So, I tried to clarify here by stating explicitly that it's an XML file. I don't think this problem happens in the others, though I haven't done Vue or Angular.

Adding 'manifest XML' here to clarify for React

---

docs/develop/understanding-the-javascript-api-for-office.md

In the understanding doc, the link to the object model 404s. I realized this was because the leading slash linked to the incorrect relative location.
Remove leading / from API object model docs
This should lead it to link to the correct place now, since it’s in the same location.

Resolve broken link to API object model doc

---

docs/excel/excel-add-ins-events.md
docs/excel/performance.md

The preview section on event toggling seems like a better fit for the advanced concept page on performance, rather than the basic page about events.
Also reworded the text to better match the new context.

Referencing event toggling to performance page

---

docs/develop/authorize-to-microsoft-graph.md
docs/develop/create-sso-office-add-ins-aspnet.md
docs/develop/create-sso-office-add-ins-nodejs.md
docs/develop/sso-in-office-add-ins.md
docs/develop/troubleshoot-sso-in-office-add-ins.md

This is a temporary solution: We need this beta API in the documentation but it must not appear in the Intellisense. So moving it to the SSO conceptual topic. It will be pulled from the d.ts in a PR to the DefinitelyTyped repo.

Move SSO reference into conceptual temporarily

---

docs/develop/dialog-api-in-office-add-ins.md

Based on [this thread](https://github.com/OfficeDev/office-js/issues/73#issuecomment-370204722), we should clarify the scope of "same domain" to explicitly rule out subdomains.
This PR is in response to [Issue #107](https://github.com/OfficeDev/office-js-docs-pr/issues/107).
@Rick-Kirkham, if I misunderstood the intent, please let me know. Thanks!

Clarifying domain scope

---

docs/excel/excel-add-ins-advanced-concepts.md
docs/excel/excel-add-ins-charts.md
docs/excel/excel-add-ins-core-concepts.md
docs/excel/excel-add-ins-data-validation.md
docs/excel/excel-add-ins-error-handling.md
docs/excel/excel-add-ins-events.md
docs/excel/excel-add-ins-multiple-ranges.md
docs/excel/excel-add-ins-overview.md
docs/excel/excel-add-ins-pivottables.md
docs/excel/excel-add-ins-ranges.md
docs/excel/excel-add-ins-tables.md
docs/excel/excel-add-ins-worksheet-functions.md
docs/excel/excel-add-ins-worksheets.md
docs/excel/performance.md
docs/includes/file-get-started-excel-angular.md
docs/includes/file-get-started-excel-jquery.md
docs/includes/file-get-started-excel-react.md
docs/includes/file-get-started-excel-vue.md
docs/toc.yml

This takes the content out of the category nodes themselves and makes it into pages under the category. It also removes the distinction between "core" and "advanced" concepts.
I'm open to naming suggestion for the new pages. My rationale for the "* Excel add-in programming" is it stands out as a thing I, as a developer, should read.

Excel Core and Advanced Concepts TOC Restructure

---

docs/excel/custom-functions-best-practices.md
docs/excel/custom-functions-json.md
docs/excel/custom-functions-overview.md

Updating to reflect current info on namespace and function id. They now can only contain alphanumeric characters and/or periods.

adding info on alphanumeric characters and periods

---

docs/excel/excel-add-ins-core-concepts.md
docs/excel/excel-add-ins-error-handling.md

This change helps consolidate the Fundamentals article by moving a long table of error codes to the error handling article.

Moving error list to error handling article

---

docs/includes/file-get-started-excel-jquery.md
docs/includes/file-get-started-excel-vue.md
docs/includes/file-get-started-onenote.md
docs/includes/file-get-started-powerpoint.md
docs/includes/file-get-started-project.md
docs/includes/file-get-started-word.md

The new version of Yo Office that was released today changes the name of the manifest file that's generated as part of the project; updating the docs to reflect the new name of the manifest file.

Changed the name of the manifest file.

---

docs/overview/office-add-in-availability.md

Added host/platform availability info for Project and Access based on [SOT](https://github.com/OfficeDev/Office-Js-Requirement-Sets/blob/master/mapping/requirements_officejs.json). This addresses issue https://github.com/OfficeDev/office-js-docs-pr/issues/508.

Add Project and Access details

---

docs/reference/manifest/rule.md

Change 'BodyAsHtml' to 'BodyAsHTML' in the `Rule` element article.

Fix typo in manifest docs

---

docs/excel/excel-add-ins-core-concepts.md

Inspired by [this UserVoice request](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/16952863-add-workbook-canceledit-or-worksheet-canceledit-to), we received a request to share how to avoid failure when the user is in cell edit mode. Since this is a RunOption passed to `Excel.run` it made the most sense to add the information here. If there's a better location, please suggest it.

Add section on RunOptions

---

docs/design/office-ui-fabric.md

The link to Office UI Fabric Core's CSS pointed to an out-of-date version that was associated with Office UI Fabric JS. Though it works functionally the same as the "standalone" Fabric Core CSS, it's quite out of date and isn't the most appropriate for this context.

Update CDN link to office-ui-fabric-core

---

docs/excel/excel-add-ins-multiple-ranges.md
docs/excel/excel-add-ins-ranges-advanced.md

This PR is to balance the special cells content appropriately between the Range and RangeAreas articles. the `getSpecialCells` methods are on both `Range` and `RangeAreas`, but return a `RangeAreas` object. In my mind, this makes them a `Range` topic, with the more advanced, multi-range behavior described in `RangeAreas`. 
Most of the text was directly moved from the RangeAreas article, with some small changes to make it contextually fit.
I'm open to organizational suggestions, as well as content edits across the board.

[excel] (SpecialCells) Reorganizing special cells content between range areas and adv. ranges articles

---

docs/onenote/onenote-add-ins-page-content.md

This is a distilled version of an HTML usage recommendation from the OneNote engineering team.

Adding HTML/CSS support note for OneNote

---

docs/reference/manifest/rule.md
docs/resources/resources-links-help.md

Quite a while back, a config setting was added to docfx.json to disable the OPS "Feedback " feature for the Resources article; this PR removes the (now unnecessary) note that advised folks not to add comments on that article. This PR also updates the ms.date value for a manifest reference article that was updated back in December 2018.

[Admin] (typo) - Remove obsolete note from Resources article.

---

docs/reference/manifest/action.md
docs/reference/objectmodel/requirement-set-1.7/office.context.mailbox.userProfile.md

Addresses #679. 
Update `Action` element article to indicate that the `SupportsPinning` child element is now also supported by Outlook 2016 for Mac. Also update wording of support info in another article (for consistency).

[Outlook] (manifest) - Update the `Action` element article.

---

docs/excel/excel-add-ins-worksheets.md
docs/reference/requirement-sets/excel-api-requirement-sets.md

This is in response to [this issue on the office-js repo](https://github.com/OfficeDev/office-js/issues/365). Worksheets cannot be deleted if the visibility is "Very Hidden", so this should be documented here.

[excel] (Worksheet) Adding note about "Very Hidden" visibility

---

docs/overview/office-add-in-availability.md

Office 2016 only had the 1.1 Rich API sets. Updating the documentation accordingly. Also adding a caveat about the Dialog API being patched into older releases.

[excel, word] (Requirement Sets) Fixing requirement set listings to match what's in O365 and O2016

---

docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md

[Internal staging site link](https://review.docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac?branch=AlexJ-Sideload).
These images are unnecessary and out-of-sync after recent iTunes UI changes. Removing them for ease of maintenance.

[general] (Sideloading) Removing iTunes interface images

---

docs/excel/excel-add-ins-workbooks.md

This adds details about a pair of preview APIs to the Workbook article. It also corrects a JavaScript code sample so that it's not type casting.

[excel] (Workbook) Adding information about save and close

---

docs/reference/manifest/desktopformfactor.md
docs/reference/manifest/supportssharedfolders.md

Based on notes in [delegate access article](https://docs.microsoft.com/en-us/outlook/add-ins/delegate-access).

[Outlook] (manifest) Update notes on SupportsSharedFolders element

---

docs/excel/custom-functions-naming.md

Function ids can only use A to Z whereas function names can use any Unicode alphabetic character.

[Excel] (Custom functions) Function ids can only use A-Z

---

docs/quickstarts/excel-custom-functions-quickstart.md
docs/toc.yml

Note these instructions will need to change when the new template gets pushed up. Right now reflects `npm run start-web` not `npm run start:web`

[Excel] (Custom Functions) Quick Start 

---

docs/overview/office-add-in-availability.md

Got retail Office build number from [here](https://docs.microsoft.com/en-us/officeupdates/update-history-office-2019). Also flipped order around so top-down O365-2013.
[Internal preview site](https://review.docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability?branch=elizs-add-o365).

Add O365 entries

---

docs/toc.yml

These changes are necessary due to an upcoming change in the way that OPS builds (renders) the TOC. For details, see internal work item # 3292909. 
I've used "Overview" as the name of the new child node, in most cases -- except for cases where "Overview" would insufficiently describe the content of the corresponding article (then I gave the node a more specific name).

[Admin] (TOC) Ensure that parent nodes in the TOC never have an href.

---

docs/excel/excel-add-ins-events.md

As per the d.ts and [reference documentation](https://docs.microsoft.com/en-us/javascript/api/excel/excel.table?view=office-js#onfiltered), these events are still in preview. Adjusting the Event article accordingly.

[excel] (Events) Moving onFiltered events back to preview

---

docs/overview/office-add-in-availability.md
docs/reference/requirement-sets/office-add-in-requirement-sets.md

iOS does not support the Compressed File requirement set. There will be a corresponding PR in Definitely Typed soon.

[Common API] (Compressed File) Removing support notes for Compressed File on iOS

---

docs/excel/custom-functions-json.md

Format fake URL as `code` so that it's not a clickable link in the article. Addresses #1011.

[Excel] (typo) Change link format.

---

docs/reference/openspec/openspec.md
docs/reference/overview/excel-add-ins-reference-overview.md
docs/reference/overview/word-add-ins-reference-overview.md

We received feedback that the Open Spec page gave a misleading impression about preview APIs. To help distinguish the two for our users, we're making this page explicitly about open specifications. The surrounding text has been changed to also clarify the process and journey. 
I also cleaned up the markdown of a couple files I was in.

[general] (Open Spec) Scoping Open Spec page to focus more on open spec

---

docs/index.yml

Since we don't have anything in open specification right now, I'd like to deprioritize the page. Open spec shouldn't be one of the first things a customer is linked to.

[admin] (Discoverability) Remove link to open spec

---

docs/word/word-add-ins-programming-overview.md

Aside from addressing #1075, this removes the notion that we're actively updating Word APIs. Since we have no immediate plans to add open specs for Word, we shouldn't promote it from the overview page.

[admin] (Discoverability) Remove open spec link from Word overview

---

docs/overview/office-add-in-availability.md

After discussing with our editor, Laura, landed on the following.
-Rename "Office Online" to "Office on the web"
-Reword "connected to Office 365" to "connected to Office 365 subscription"
-Reword from "for [platform]" to "on [platform]"

[All] Rename Office Online

---

docs/includes/quickstart-yo-prerequisites.md

The next release of Yo Office no longer requires Git. I'll plan to merge this PR as soon as the next release of Yo Office is published (most likely Monday 6/24).

[All] (Yo Office prerequisites) Remove Git as a prerequisite for using Yo Office.

---

docs/excel/custom-functions-json-autogeneration.md

Some of the Types links had broken links which linked to ##types instead of #types.

Fixed broken links with duplicate hashtags

---

docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md

Hi!
The instructions to sideload an add-in in Office on Mac tells user to go to the "documents" folder, but Office needs a (capital-letter) "Documents" folder.

[typo] (Office on Mac) Fix folder name in instructions

---

docs/develop/add-in-manifests.md
docs/reference/manifest/appdomain.md
docs/reference/manifest/appdomains.md

Clarification language to communicate the usage of AppDoamins manifest entry to add trusted domains from where Office.js API calls can be made.

[common] (AppDomain) Trusted domains that can make Office.js API call

---

docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md

Hello again,
In the steps to sideload an Office add-in on Windows, the steps say to click "OK", while the UI shows "Add".
I'm using Office 365 ProPlus, version 1906, and performed the sideloading process in Excel.
If this UI element is not universal across the versions, and you'd like to keep it, feel free to close the PR.

Change OK to Add to reflect UI

---

docs/excel/custom-functions-parameter-options.md

Noted that the parameters are still null from Excel, not undefined as you would typically expect.
Added TypeScript examples (because initialization syntax won't work as expected)

[Excel](custom functions) Updated info on optional parameters

---

docs/design/add-in-icons.md

H3 headers were not shown correct due to missing space after hash signs.

Added mandatory space for H3 header

---

docs/excel/excel-add-ins-charts.md
docs/excel/excel-add-ins-shapes.md

Making the [Chart](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-charts?view=office-js) and [Shape](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-shapes?view=office-js) article titles match the casing of the [Table](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-tables?view=office-js) and [Worksheet](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-worksheets?view=office-js) articles.

[typo] Fixing Excel page title casing

---

docs/overview/explore-with-script-lab.md
docs/overview/schemas/content/OfficeAppBasicTypesV1_0.xsd
docs/overview/schemas/content/OfficeAppManifestV1_1.xsd
docs/overview/schemas/mail/OfficeAppBasicTypesV1_0.xsd
docs/overview/schemas/mail/OfficeAppManifestV1_1.xsd
docs/overview/schemas/taskpane/OfficeAppBasicTypesV1_0.xsd
docs/overview/schemas/taskpane/OfficeAppManifestV1_1.xsd
docs/reference/manifest/alternateid.md
docs/reference/manifest/iconurl.md
docs/reference/manifest/scopes.md

Changes **Office Store** -> **AppSource** throughout the docs. Note that I've intentionally *not* updated `ms.date` in any of these articles, since none of the changes are substantive.

[Admin] Fix typos.

---

docs/develop/specify-office-hosts-and-api-requirements.md
docs/excel/excel-add-ins-advanced-concepts.md
docs/excel/excel-add-ins-tables.md
docs/reference/requirement-sets/onenote-api-requirement-sets.md
docs/reference/requirement-sets/outlook-api-requirement-sets.md
docs/tutorials/excel-tutorial.md
docs/tutorials/word-tutorial.md

This PR updates `ms.date` for articles that were updated in #1187 and also makes the requirement set number parameter in the `isSetSupported` call a string (by adding quotation marks around the parameter value) in a few more places.

[common API] (Requirement Set) Updating requirement set syntax (part 2 of 2)

---

docs/excel/excel-add-ins-advanced-concepts.md
docs/excel/excel-add-ins-core-concepts.md

This change also tries to better document behavior around structs such as `DataValidation.prompt` and `PageLayout.zoom`.

[excel] (Rich API) Remove obsolete references to relationships

---

docs/overview/office-add-in-availability.md
docs/reference/requirement-sets/image-coercion-requirement-sets.md

[Internal tracking issue](https://office.visualstudio.com/OC/_workitems/edit/3537516)
Excel on the Web does not support Image Coercion. This change removes those claims.

[excel] (Requirement Sets) Removing support for Image Coercion for Excel on the Web

---

docs/develop/convert-javascript-to-typescript.md
docs/develop/specify-office-hosts-and-api-requirements.md
docs/excel/excel-add-ins-advanced-concepts.md
docs/reference/requirement-sets/outlook-api-requirement-sets.md

This is a follow-up to @sumurthy's PR (https://github.com/OfficeDev/office-js-docs-pr/pull/1174).
I want to make it clear users should use strings instead of numbers for `isSetSupported` and why.
If the text and messaging is good here, I'll update DefinitelyTyped and the ref docs.

[Common API] (Requirement Sets) Increased urgency around using strings in isSetSupported

---

docs/excel/excel-add-ins-shapes.md
docs/excel/excel-add-ins-workbooks.md
docs/powerpoint/powerpoint-add-ins.md

Based on the findings in [this PR](https://github.com/OfficeDev/office-js-docs-pr/issues/1276), these code changes should be made.

[excel, powerpoint] (Create Workbook/Presentation) Update code samples

---

docs/publish/publish.md

Point Sideloading URL to the Sideloading Heading. When clicking the sideloading method it feels like it's going to the wrong page. 
#1281 
https://github.com/OfficeDev/office-js-docs-pr/issues/1281
I'm not familiar to how you are modifying the URLs on your end, mainly the suffix/extension `.md`, but the change that works for me externally: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md#sideload-your-add-in

Point Sideloading URL to the Sideloading Heading

---

docs/design/using-office-ui-fabric-react.md
docs/includes/note-yeoman-generator-bug-201908.md
docs/quickstarts/excel-custom-functions-quickstart.md
docs/quickstarts/excel-quickstart-angular.md
docs/quickstarts/excel-quickstart-jquery.md
docs/quickstarts/excel-quickstart-react.md
docs/quickstarts/onenote-quickstart.md
docs/quickstarts/powerpoint-quickstart.md
docs/quickstarts/project-quickstart.md
docs/quickstarts/word-quickstart.md
docs/tutorials/excel-tutorial-create-custom-functions.md

This PR reverts changes made in PR #1241 (now that the issue with spaces not being allowed in project names / folder path has been resolved).

[Add-ins] (Yo Office) Remove note about spaces not being permitted in project name or folder path.

---

docs/excel/excel-add-ins-workbooks.md

The parameter order changed in [CommentCollection.add](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.commentcollection?view=excel-js-preview&branch=master#add-celladdress--content--contenttype-). This fixes the article sample.

[excel] (Comments) Correcting add comment parameter order

---

docs/develop/referencing-the-javascript-api-for-office-library-from-its-cdn.md

The CDN URL for office.js should be changed to all lowercase letters, because many of our tools and samples are referencing it that way. Furthermore, we are now prefetching the office.js using the lowercase URL in Office Online. Using uppercase O in the URL causes us to be unable to share the browser cache as the URLs are different.

Update office.js CDN URL to all lowercase letters

---

docs/excel/custom-functions-overview.md

Just a quick fix to which link is the custom function runtime link.

[Excel](custom functions): Fix to runtime link

---

docs/reference/manifest/getstarted.md

LearnMoreUrl is required in GetStarted element, when user doesn't provide it, the add-in will not successfully sideload into Excel, and also 'npm run validate' will return XML Schema Violation:

Changed info regarding LearnMoreUrl element

---

docs/docfx.json
docs/excel/custom-functions-overview.md
docs/excel/excel-add-ins-overview.md
docs/onenote/onenote-add-ins-programming-overview.md
docs/overview/explore-with-script-lab.md
docs/overview/office-add-ins.md
docs/powerpoint/powerpoint-add-ins.md
docs/project/project-add-ins.md
docs/reference/overview/visio-javascript-reference-overview.md
docs/word/word-add-ins-programming-overview.md

The data science and developer program team would like to recommend add-in getting started docs to users. However, we hit a few issues with the metadata:
1) Most platforms besides add-ins tag their overview docs as "conceptual" docs. When combining docs across all the platforms, the user now has to understand and distinguish between "overview" and "conceptual" docs (which adds a layer of confusion)
To alleviate this, I've changed the "ms.topic: overview" tags to "ms.topic: conceptual".
2) We are having trouble pulling the custom tags from telemetry. So, instead of calling the column "scenarios", I've added the ms.custom tag and nested scenarios there.
3) When combining the tutorials/quickstarts across products, we noticed the add-in tutorials and quickstarts were not being recommended. …

Metadata update for getting started docs

---

docs/excel/excel-add-ins-ranges-advanced.md

- The `showOutlineLevels` method is on Worksheet, not Range. 
- Link anchors can't be camel-cased.
- `upgroup` should be spelled correctly.

[excel] (Outlines) Fixing links

---

docs/includes/file-get-the-whole-document-from-an-add-in-for-powerpoint-or-word.md
docs/powerpoint/get-the-whole-document-from-an-add-in-for-powerpoint.md
docs/word/get-the-whole-document-from-an-add-in-for-word.md

This is necessary to fix an OPS build warning (suggestion) which verifies that every article contains an H1.

[Admin] (Address build suggestion) Move H1 out of include file into each individual file.

---

docs/excel/excel-add-ins-worksheets.md

This is in response to #1365 .
The conceptual article for worksheets could use a small section describing the behavior of `Worksheet.copy`. This adds that section. 
It also adjusts the references to properties to use codeticks instead of bold font. This is in accordance with our current style and localization requirements.
There are also reference doc updates to clarify method behavior. They are in PR on DefinitelyTyped right now: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39189

[excel] (Worksheet) Adding a section about Worksheet.copy

---

docs/develop/addressing-same-origin-policy-limitations.md

I'm pretty sure JSONP doesn't have a slash. (https://en.wikipedia.org/wiki/JSONP, https://www.w3schools.com/js/js_json_jsonp.asp) I'm just going through all of our docset to check for images, so am trying to fix things along the way that I notice as well.

[Add-ins] (Minor fix) Eliminate slashes from JSONP messages

---

docs/excel/excel-add-ins-advanced-concepts.md

This was supposed to link to the [DataValidation](https://docs.microsoft.com/en-us/javascript/api/excel/excel.datavalidation?view=excel-js-preview) reference page, but that link was accidentally omitted.

[admin] (Links) Add missing link to scalar object setting example

---

docs/develop/convert-javascript-to-typescript.md

Current guidance is to always use a string when referring to requirement set versions in `isSetSupported`.
This addresses issue #1394.

[common] (Requirement Sets) Removing instruction to revert requirement set version to a number

---

docs/tutorials/powerpoint-tutorial.md

Visual Studio 2019 Office Add-ins project templates no longer use Fabric components. This PR updates the PowerPoint tutorial instructions to no longer rely on the presence of Fabric components, and also makes some other minor modifications such as specifying project name and using `Office.onReady`.

[PowerPoint] (tutorial) Update tutorial instructions to work with Visual Studio 2019.

---

docs/develop/common-coding-issues.md
docs/excel/excel-add-ins-core-concepts.md

This adds a section centralizing the limitations with Excel range sizes. It also discusses the Common/Outlook programming model and its lack of promises.

[excel, CommonAPI] (Code patterns) Adding notes about range limits and promiseless callback methods

---

docs/develop/common-coding-issues.md
docs/excel/excel-add-ins-core-concepts.md

This is based on clarification from the production team:
> Range size limitation (five million cells) is for get operations (not set operations). It applies to all platforms.
> 
> Payload size limit is kind of platform limitation, it is online only and it applies to all APIs (not only range API).

[excel] (Performance) Correcting range limit text

---

docs/develop/add-in-manifests.md

There was a remark that before the product launch the strict position enforcement through XSD could be changed. Just tested it and it hasn't changed, thus removing the comment to provide clarity.

Removed remark about Label in CustomTab

---

docs/reference/manifest/group.md

Indicate that the `Icon` element is a required child element of the `Group` element in the manifest.
Fixes #1462

[All Hosts] Update the Group element article in the manifest reference docs.

---

docs/excel/custom-functions-overview.md
docs/tutorials/excel-tutorial.md

Fixes #1452.
As per a conversation with @sumurthy:
> AlexJerabek: What is the difference between the /1/ and /1.1/ CDN endpoints? 
> sumurthy: They point to the same thing. We should just use one of them in the docs =>  /1/ 
@mscharlock, I tested the Custom Function endpoint and this appears to be true there too. Please verify that's correct.

[all] (CDN) Standardizing CDN URL to /1/

---

docs/concepts/browsers-used-by-office-web-add-ins.md
docs/develop/create-and-debug-office-add-ins-in-visual-studio.md
docs/includes/enable-debugging-on-edge-devtools.md
docs/testing/debug-add-ins-using-f12-developer-tools-on-windows-10.md

This adds information about how to enable debugging for UI-less code (like add-in commands) that are running in the Edge WebView.

[all] debugging ui-less code with Edge DevTools

---

docs/develop/add-in-manifests.md
docs/develop/troubleshoot-sso-in-office-add-ins.md
docs/excel/custom-functions-troubleshooting.md
docs/testing/clear-cache.md
docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md
docs/testing/runtime-logging.md
docs/testing/testing-and-troubleshooting.md
docs/testing/troubleshoot-manifest.md
docs/toc.yml

This PR moves information about "clearing the Office cache" and "debugging with runtime logging" into separate articles (for improved discoverability of this important info), making it so that the "validate an add-in's manifest" article contains only information relevant to that topic.
(re internal work item # 2660004)

[All hosts] Refactor debugging/troubleshooting content.

---

docs/reference/requirement-sets/excel-api-requirement-sets.md
docs/reference/requirement-sets/word-api-requirement-sets.md

I want to make these notes more direct and clear, to lessen the confusion about Office 2016/2019 restrictions.

[excel, word] (Requirement sets) Simplifying note about perpetual versions

---

docs/testing/clear-cache.md

This PR:
- Adds info about how to remove a sideloaded add-in from Outlook.
- Updates info about using Edge DevTools to clear the cache on Windows 10, to remove the implication that the procedure is only applicable for Outlook (because it's applicable for all Office hosts).  (See #1570 for supporting info.)

[All hosts]  (clearing cache) Updated content that explains how to clear Office cache on Windows.

---

docs/quickstarts/excel-quickstart-angular.md
docs/quickstarts/excel-quickstart-react.md
docs/quickstarts/excel-quickstart-vue.md
docs/quickstarts/onenote-quickstart.md
docs/quickstarts/project-quickstart.md

Added descriptions for a few of the quickstarts that didn't have them. These descriptions were modeled after the Word quickstart description, and will help make sure we display content properly when we pull the quickstarts into the dev program.

Added missing descriptions to quickstarts

---

docs/excel/excel-add-ins-comments.md
docs/excel/excel-add-ins-events.md
docs/excel/excel-add-ins-ranges-advanced.md

This also corrects the labeling of some preview or online-only features in the Comment article and adds a behavior clarification to the remove event handler section.

[excel] (Range) Adding a `Range.moveTo` sample

---

docs/testing/clear-cache.md
docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md
docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md
docs/testing/sideload-office-add-ins-for-testing.md
docs/toc.yml

Fixes #1137. 
These changes should clarify how to remove a side loaded add-in by clearing the cache. @kbrandl can you please make the analogous change in PR #1597 (specifically [this article](https://docs.microsoft.com/en-us/outlook/add-ins/sideload-outlook-add-ins-for-testing))?
I also cleaned up some formatting according to docs markdown linter.

[testing] (Sideloading) Linking to cache clearing article

---

docs/testing/clear-cache.md

Every time I try to copy this folder path, I accidentally grab the '.' at the end of the sentence. Making this a code block gives users the "Copy" button. It also draws the eyes to the most important information on this page.

[admin] (Ease-of-use) Switch folder path to code block

---

docs/excel/excel-add-ins-comments.md

Notes and comments are two different things in the Excel world. This PR removes the use of the word "note" as a synonym for "comment".

[excel] (Comments) Remove the word 'note' from comment article

---

docs/includes/console-tool-note.md
docs/quickstarts/excel-quickstart-jquery.md
docs/quickstarts/outlook-quickstart.md
docs/quickstarts/powerpoint-quickstart.md
docs/quickstarts/word-quickstart.md

Fixes #1676. 
This gives quick-start users information about finding the `console.log` output the quick start add-ins generate.

[quickstarts] (Visual Studio) Add note about console for VS

---

docs/toc.yml

The "(Office 2013+)" at the end of this folder name implies that the Common APIs are only available on the perpetual license Office. They are actually available on all platforms including subscription.

[All Hosts] (toc) fix misleading TOC folder name

---

docs/excel/excel-add-ins-pivottables.md

We had a customer request for a `getDataBodyRange` example. This PR attempts to make this example more visible and its utility more clear.

[excel] (PivotTable) Clean up PivotLayout.getDataBodyRange example

---

docs/excel/performance.md

Fixes #1762.
References are still maintained and rebuilt when calculations are suspended. There is no way to disable this through the JS API today.

[excel] (Performance) Add a blurb about reference rebuilding under calculation suspension

---

.openpublishing.publish.config.json
docs/excel/excel-add-ins-comments.md
docs/excel/excel-add-ins-events.md
docs/excel/excel-add-ins-ranges-advanced.md
docs/excel/excel-add-ins-workbooks.md
docs/reference/requirement-sets/excel-api-1-11-requirement-set.md
docs/reference/requirement-sets/excel-api-online-requirement-set.md
docs/reference/requirement-sets/excel-api-requirement-sets.md
docs/reference/requirement-sets/excel-preview-apis.md
docs/toc.yml

This PR:
- Adds a page for ExcelApi 1.11.
- Updates the Excel Preview APIs with the current difference between preview and release.
- Updates the ExcelApiOnline 1.1 page to reflect the current differences between 1.11 and Online.
- Updates the requirement set overview to give the build numbers for ExcelApi 1.11 (based on https://github.com/OfficeDev/Office-Js-Requirement-Sets/pull/57).
- Updates the iOS build numbers (based on https://github.com/OfficeDev/Office-Js-Requirement-Sets/pull/56).
- Removes any preview or online-only tags from article sections that no longer apply.

[excel] (ExcelApi 1.11) ExcelApi Requirement Set 1.11 Updates

---

docs/excel/excel-add-ins-advanced-concepts.md

[Staging site](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-advanced-concepts?branch=AlexJ-DefaultLoad#loading-the-properties-of-an-object).
Some of the new Excel preview API properties will not be loaded by default with a parameter-less load statement. This behavior needs to be documented. I restructured the load section of this article because I didn't want to have a note within a note.

[excel] (Load/Sync) Discussing default load exclusions

---

docs/excel/excel-add-ins-core-concepts.md

Fixes #2013.
While the code sample here technically works, it does not compile against the TypeScript definitions. This is because properties can't have multiple types. In order to tell a more cohesive story with TypeScript, we'll remove this section.

[excel] (Range) Removing single value property set section

---

docs/index.yml

This PR includes: 
-- my attempt at adding a paragraph to the main landing page (mostly unsuccessful because the page schema is very restrictive -- doesn't allow ":" characters, couldn't figure out how to do a line break, etc). Any suggestions here?? 
-- since the paragraph didn't work, I experimented with adding MS Learn links to the About Office Add-ins card. If we include MS Learn links here, my intuition is that they should open in a new tab, and also that there be some visual indicator that these thinks go to a different section of the site (a small icon?). Not sure how much freedom we have. Open to suggestions here, too!

[all] (index.yaml) Adding links to main landing page

---

docs/overview/learning-path-beginner.md
docs/overview/learning-path-transition.md
docs/toc.yml

Link to this branch: https://review.docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins-fundamentals?branch=alison-mk-TOC-ideas
Updated four TOC titles: 
-- removed Start Here! and Transition Here! as discussed in meeting earlier this week, feels awkward plus updated L2 nav will help highlight each learning path 
-- switched "Building Office Add-ins: to "Office Add-ins development process", which to me clarifies that the article is about a broad process, as opposed to specifics for how to build an add-in ("Building Office Add-ins" is so vague to me that I mentally translated it to 'How to build Office Add-ins' and then was confused upon reading the article). 
-- I think 'Core development concepts' adds useful clarity to this node, but honestly I feel less committed to this …

[all](ToC) TOC update ideas

---

docs/excel/excel-add-ins-events.md

A fix for this issue has been made and received through the various Office channels.

[excel] (Events) Remove warning about onSelectionChanged behavior

---

docs/excel/excel-add-ins-blank-null-values.md
docs/excel/excel-add-ins-charts.md
docs/excel/excel-add-ins-comments.md
docs/excel/excel-add-ins-conditional-formatting.md
docs/excel/excel-add-ins-core-concepts.md
docs/excel/excel-add-ins-data-validation.md
docs/excel/excel-add-ins-delay-in-cell-edit.md
docs/excel/excel-add-ins-error-handling.md
docs/excel/excel-add-ins-events.md
docs/excel/excel-add-ins-overview.md
docs/excel/excel-add-ins-pivottables.md
docs/excel/excel-add-ins-ranges-advanced.md
docs/excel/excel-add-ins-ranges.md
docs/excel/excel-add-ins-tables.md
docs/excel/excel-add-ins-workbooks.md
docs/excel/excel-add-ins-worksheet-functions.md
docs/excel/excel-add-ins-worksheets.md
docs/excel/performance.md
docs/quickstarts/excel-quickstart-angular.md
docs/quickstarts/excel-quickstart-jquery.md
docs/quickstarts/excel-quickstart-react.md
docs/quickstarts/excel-quickstart-vue.md
docs/reference/overview/excel-add-ins-reference-overview.md
docs/reference/requirement-sets/excel-api-requirement-sets.md
docs/toc.yml
docs/tutorials/excel-tutorial.md

Split up the Excel fundamental concepts article:
1. Move Run options to its own article "Delay ..."
2. Move blank or null values section to it's own article "Blank ..."
3. Move requirement sets section to the existing Excel requirements article
4. Rename fundamental concepts article "Excel object model".

Excel object model

---

docs/excel/custom-functions-requirement-sets.md

This PR adds:  
- Supported builds to the requirement set table. 
- A short paragraph to describe the differences between the versions.

Update CF req set overview page

---

docs/reference/requirement-sets/dialog-api-requirement-sets.md

A result of [PR #2168](https://github.com/OfficeDev/office-js-docs-pr/pull/2168). Also updating one use of 'version' to 'requirement set'.

Reverse order of Dialog API req sets

---

docs/excel/custom-functions-errors.md

@ElizabethSamuel-MSFT after consulting the original author (David), I've decided to remove the JavaScript note entirely for the divisionByZero error code. The other descriptions in this table define the error codes themselves, and do not include suggestions for how to write the error handler scripts, so it's out of context here to only mention it for this error code. It seems strange to assume that the developer can write the other error handlers, but won't know how to write a handler for division by zero. Based on the JavaScript skill level assumed throughout the rest of this page, I'm inclined to think the developer will be capable of writing a division by zero handler. If you approve, I'll make this change to the type definition file, too.

[Excel] (CustomFunctionRuntime 1.3) Adjust divisionByZero definition per feedback

---

docs/reference/manifest/supportssharedfolders.md

Mac supports `SupportsSharedFolders` once again ([PR](https://github.com/OfficeDev/office-js-docs-pr/pull/2150/files)) so requirement set support matches delegate access feature support.

[Outlook] (delegate) Update support note

---

docs/concepts/add-in-development-best-practices.md
docs/develop/develop-overview.md
docs/excel/custom-functions-overview.md
docs/excel/excel-add-ins-overview.md
docs/onenote/onenote-add-ins-programming-overview.md
docs/outlook/outlook-add-ins-overview.md
docs/overview/explore-with-script-lab.md
docs/overview/learning-path-beginner.md
docs/overview/learning-path-transition.md
docs/overview/office-add-ins.md
docs/overview/patterns-and-practices-overview.md
docs/overview/set-up-your-dev-environment.md
docs/powerpoint/powerpoint-add-ins.md
docs/project/project-add-ins.md
docs/resources/resources-links-help.md
docs/word/word-add-ins-core-concepts.md
docs/word/word-add-ins-programming-overview.md

Putting some cross-links to the dev program seems to me like it would be a good idea since we rarely expose it in our docs. :)

[Add-ins][All hosts] Add links to the Dev Program

---

docs/design/keyboard-shortcuts.md

Here are the changes I made:
1. Add "actions" object to the JSON file (this resulted in a few changes to verbiage changing "action name" to "action")
2. Include the platform limitations as part of !Important note (to match custom functions documentation)
3. Move the example JSON before the notes regarding the example
4. Small spelling/wording fixes

Keyboard shortcuts documentation edits

---

docs/reference/requirement-sets/excel-api-requirement-sets.md
docs/reference/requirement-sets/excel-preview-apis.md
docs/reference/requirement-sets/powerpoint-api-requirement-sets.md
docs/reference/requirement-sets/powerpoint-preview-apis.md
docs/toc.yml

This PR adds a page for the PowerPointAPI Preview requirement set. It also makes the PPT requirement set overview page match [that of Excel](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets?view=powerpoint-js-preview) for better consistency across hosts.

[PowerPoint] (Requirement sets) PowerPoint preview APIs requirement set page

---

docs/design/keyboard-shortcuts.md
docs/tutorials/keyboard-shortcuts-tutorial.md

What I added/modified:
1. Changed all instances of 'extended manifest JSON' to 'shortcuts JSON' for simplicity
2. Added links to the PnP sample at the beginning of each article.
3. Added a section for the limitation around the user's focus.
4. Removed per platform customization for public preview docs (will be included as part of GA)
5. For the tutorial, consolidate the entire JSON sample together to make it simpler for developers to copy and paste.
6. Add some keyboard mapping clarifications between Mac and win32.

KB shortcuts changes

---

docs/toc.yml

This changes the TOC to focus on the CF section when the CF quickstart is selected, as opposed to focusing on the overall uick start section.
It also corrects the TOC to not show errors in VSCode.

[admin] (TOC links) Adjust CF quick start link and add items yml

---

docs/reference/overview/visio-javascript-reference-overview.md

Fixes [2364](https://github.com/OfficeDev/office-js-docs-pr/issues/2364)
NOTE to reviewers: SharePoint is still using "SharePoint Online", not "SharePoint on the web".

[Visio] (apis) clarify limitations on when it can be used

---

.openpublishing.redirection.json

After #2342, there is no longer a need for this redirection link. This PR removes it from the `redirection.json` file.

[admin] (Redirects) Remove unused redirect link

---

docs/includes/word-preview-apis-note.md
docs/reference/requirement-sets/word-preview-apis.md

Word preview APIs are only supported for Windows. Adding a note at the top of the page to clarify that.

Add windows only note to word preview APIs

---

docs/tutorials/excel-tutorial.md

I follow the documentation in https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial and I tested the example code in my project, I found 2 errors in this part.
currentWorksheet.charts.add('ColumnClustered', dataRange, 'auto'); 
The third parameter should be "Auto", not "auto"
chart.legend.position = "right"
the value of chart.legend.position should be "Right" not "right"

Correction for error example in documentation

---

docs/tutorials/excel-tutorial.md

This PR adds a missing semicolon and changes `&euro;` to the unicode `\u20AC`. 
`&euro;` displays literally as `"&euro;"` in this chart in Excel, but `\u20AC` displays the euro symbol (the intended result).

[Excel] (Tutorial) Add missing semicolon, update euro symbol to unicode

---

docs/reference/manifest/version.md

The schema has a pattern of `<xs:pattern value="([0-9]{1,5})(\.[0-9]{1,5}){0,3}?"/>`. This allows formats like
- 1
- 1.2
- 1.2.3
- 1.2.3.4
Additionally, each part of the version number can only be 5 digits long.

[manifest] (Version) Update to match schema allowances

---

docs/excel/custom-functions-parameter-options.md

The yo office issue that inspired this !IMPORTANT note has been resolved, and the manually-created JSON process is no longer required to detect parameter addresses.
This PR resolves GitHub issue #2472.

[Excel] (Custom Functions) Adjust parameter address note

---

docs/testing/debug-office-add-ins-on-ipad-and-mac.md

The Mac App Store builds of Office do not support the `OfficeWebAddinDeveloperExtras` flag.

Clarify debugging limitations with MAS builds

---

docs/excel/custom-functions-parameter-options.md

Including the @returns in this sample ensures that the JSON metadata compiles to include dimensionality: "matrix".

[Excel] (Custom Functions) Add @returns to param address sample

---

docs/excel/custom-functions-debugging.md

The names of various menus and options in VSCode has changed since this tutorial was written, making it somewhat confusing.  This PR changes that language to match the current version of VSCode.

Update language to reflect current menu names and options in VSCode

---

docs/concepts/privacy-and-security.md

Documenting a security prompt you may see if the add-in's host domain is different from Exchange on-premise, or Office Online Server (when loading first time.)

[All](security): add note about security prompt on different domains

---

docs/excel/custom-functions-troubleshooting.md
docs/outlook/autolaunch.md

At present, users running this type of add-in on Win32 through yo office may need to include a loopback exemption.

[Outlook] (event-based activation) Add note about loopback exemption

---

docs/excel/excel-add-ins-workbooks.md

Replacing `addFromBase64` content with content for the new `insertWorksheetsFromBase64` preview API.

[Excel] (Workbook) Update insert worksheets article section with new Preview API 

---

docs/develop/persisting-add-in-state-and-settings.md

There's been some confusion about how this article applies to web browser storage settings, and how to manage settings across documents.
- Removed link to archived web storage sample.
- Added note that user can disable various web storage settings.
- Added note that this article does not apply when storing settings beyond the scope of the current document.

[All](Storage)clarify web browser usage

---

docs/overview/office-add-in-availability.md
docs/reference/requirement-sets/open-browser-window-api-requirement-sets.md

Do we need to note which Office applications support OpenWindowBrowserApi on the Open Window Browser API requirement sets page?

Note availability of newer requirement sets

---

docs/develop/specify-office-hosts-and-api-requirements.md

@Rick-Kirkham Is this something you can help verify? I took a look at the [availability page](https://docs.microsoft.com/office/dev/add-ins/overview/office-add-in-availability) and the schemas.
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2631.

[Add-ins] Clarify which clients support which OfficeApp types

---

docs/develop/loading-the-dom-and-runtime-environment.md

Fixes #2618 - removing references to initDialer sample that does not exist.
Removes duplicate content about **Office.onReady** and **Office.initialize** that's better covered in [Initialize your Office Add-in](https://docs.microsoft.com/office/dev/add-ins/develop/initialize-add-in)

[Outlook] Remove non-existent sample and duplicate content

---

docs/testing/sideload-office-add-ins-for-testing.md

According to https://github.com/OfficeDev/generator-office/issues/626#issuecomment-818822432 and https://www.youtube.com/watch?v=6255LyDZxEk the document should be defined in config and not in scripts.
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2623

Document definition should be part of config and not scripts

---

docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md

Added a note to clarify which manifest to use when sideloading from Visual Studio 2019 projects.

[All hosts](Sideloading) Add note for which manifest to use from Visual Studio

---

docs/includes/office-js-api-models.md

PowerPoint is getting to the point where it should be mentioned as having an application-specific API model. This PR adds it to an include file listing those applications.

[powerpoint] Add PowerPoint to the application-specific API list

---

docs/overview/core-concepts-office-add-ins.md

This section was referring to a TOC section that no longer exists. Hopefully, this makes it more clear that the reader is supposed to read the rest of the links later in the page.

[getting started] (Development overview) Remove reference to "Core concepts"

---

docs/design/keyboard-shortcuts.md

This change adds the "Shift" key limitations to the keyboard shortcuts documentation.

Add shift key details to kb shortcuts documentation

---

docs/develop/configure-your-add-in-to-use-a-shared-runtime.md
docs/testing/troubleshoot-development-errors.md

You can update a Visual Studio project to use shared runtime, but you can get validation errors in the manifest because Visual Studio 2019 ships with a slightly older version of the XSD files. I added a troubleshooting section on how to update your XSD files. This really would apply for any newer feature we release that requires new elements in the manifest.

[All hosts](Visual Studio) how to fix schema issues in VS for shared runtime

---

docs/includes/quickstart-yo-start-server-excel.md
docs/quickstarts/excel-custom-functions-quickstart.md
docs/quickstarts/excel-quickstart-angular.md
docs/quickstarts/excel-quickstart-jquery.md
docs/quickstarts/excel-quickstart-react.md
docs/quickstarts/excel-quickstart-vue.md
docs/quickstarts/onenote-quickstart.md
docs/quickstarts/outlook-quickstart.md
docs/quickstarts/powerpoint-quickstart.md
docs/quickstarts/project-quickstart.md
docs/quickstarts/sso-quickstart-customize.md
docs/quickstarts/word-quickstart.md

Fixes #2826.
This PR updates the quick starts to include an `npm install` step missing in the latest versions of yo office.

[quickstarts] Add npm install steps to all quick starts

---

docs/excel/custom-functions-overview.md

Fixes #2830 and #2829. 
Re: the shared runtime note. Because this article includes a link to the Shared Runtime article (with additional information) in the paragraph following this bullet point, I opted to remove the obsolete browser note entirely.

[Excel] (Custom Functions) Update overview article

---

docs/includes/quickstart-yo-start-server-excel.md
docs/quickstarts/excel-custom-functions-quickstart.md
docs/quickstarts/excel-quickstart-vue.md
docs/quickstarts/onenote-quickstart.md
docs/quickstarts/outlook-quickstart.md
docs/quickstarts/powerpoint-quickstart.md
docs/quickstarts/project-quickstart.md
docs/quickstarts/word-quickstart.md

Thanks to https://github.com/OfficeDev/generator-office/pull/653, the yo office path now runs `npm install`. This means the changes from #2852 are no longer necessary.

[quick starts] Remove unnecessary npm install step

---

docs/overview/explore-with-script-lab.md

Script Lab is ready to stop supporting IE11 and will do so imminently.

[script lab] (Support) Edit Script Lab IE11 support note

---

docs/develop/create-sso-office-add-ins-aspnet.md
docs/develop/create-sso-office-add-ins-nodejs.md

This updates 2 articles to match respective changes in the code samples. We recommend to use Office.auth interface, no longer the OfficeRuntime.auth interface.

[All hosts](SSO) - Use Office.auth interface

---

docs/testing/clear-cache.md

Pressing F5 with add-in in focus will not reload from source, only from cache.
Pressing Ctrl-F5 will reload from source disregarding cache.
I assume hard reload is the most likely needed scenario, as such I propose replacing F5 with Ctrl-F5.
If this assumption is incorrect or not warranted, adding a sentence describing Ctrl-F5 might be a better solution.

Update tip using F5 to use Ctrl-F5

---

docs/develop/run-code-on-document-open.md

When following [Run code in your Office Add-in when the document opens](https://docs.microsoft.com/office/dev/add-ins/develop/run-code-on-document-open) the information on where to put your startup code is in the last section on the article. However, this is information that you always need, whereas the other sections are more optional. 
This PR moves the startup code section earlier to help reduce confusion so developers can find this information faster. Fixes https://github.com/OfficeDev/office-js-docs-reference/issues/932

[All hosts](Add clarity for where to locate startup code on document open)

---

docs/reference/manifest/customfunctionssourcelocation.md
docs/reference/manifest/event.md
docs/reference/manifest/extendedpermission.md
docs/reference/manifest/extendedpermissions.md
docs/reference/manifest/mobileformfactor.md
docs/reference/manifest/script.md
docs/reference/manifest/supportssharedfolders.md
docs/toc.yml

TOC: Remove Outlook Concepts subfolder to make organization consistent with other hosts; some alphabetizing in manifest versionoverrides section; move extendedpermissions nodes to under versionoverrides
Manifest section: Add supported add-in types to various articles (not a comprehensive update)

[admin] TOC update; include add-in types in manifest articles

---

docs/develop/add-in-manifests.md
docs/reference/manifest/runtime.md
docs/reference/manifest/runtimes.md

This is the first of what will be a series of PRs adding info to manifest elements about
- Which VersionOverrides schema the elements are valid for.
- Which requirement sets are associated with the elements.
This one also contains a new conceptual section of the manifest overview that describes the `<VersionOverrides>` element. This section will be linked to in all the PRs.

[All Hosts] (manifest) versionoverrides and req set info for runtimes

---

docs/testing/debug-desktop-using-edge-chromium.md

Fixes #3031.
This also makes gives the command a copy button, so people can easily paste the code in their command window.

[Developer Experience] (debugging) Update Office debugging command instructions

---

docs/reference/requirement-sets/shared-runtime-requirement-sets.md

This adds build information for support in preview for the shared runtime requirement set.

[Word and PowerPoint] Add preview information for shared runtime

---

docs/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog.md

Reported as broken link. Removing link altogether since M365 Germany is being decommissioned.

[all hosts] (publish) Remove link to M365 Germany

---

docs/excel/excel-data-types-concepts.md
docs/excel/excel-data-types-overview.md
docs/reference/requirement-sets/excel-api-1-14-requirement-set.md
docs/reference/requirement-sets/excel-preview-apis.md

This PR: 
- Adjusts the Preview note on two Data Types articles because the missing data types API (Range.valuesAsJson) has now reached beta release 
- Updates the Preview APIs intro table based on the recent CDN transfer
- Updates the ExcelApi 1.14 intro table with link to new conceptual docs

[Excel] Update conceptual docs following CDN transfer

---

docs/excel/custom-functions-overview.md
docs/excel/excel-add-ins-overview.md
docs/onenote/onenote-add-ins-programming-overview.md
docs/outlook/outlook-add-ins-overview.md
docs/overview/office-add-ins.md
docs/powerpoint/powerpoint-add-ins.md
docs/project/project-add-ins.md
docs/reference/overview/visio-javascript-reference-overview.md
docs/word/word-add-ins-programming-overview.md

Generally setting ms.topic to "overview" for main page being used as Overview page for each product.

[all hosts] (metadata) Set tag to overview

---

docs/design/add-in-commands.md
docs/develop/create-addin-commands.md

This addresses issue #3126 and updates https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-addin-commands to refer to the quick starts for starting off with a command (as all the yo office projects give you a command for free).
Also removes a broken video link from https://docs.microsoft.com/en-us/office/dev/add-ins/design/add-in-commands that no longer exists.

[All hosts](commands) Update getting started info

---

docs/develop/persisting-add-in-state-and-settings.md

This updates the note that Web Storage API (localStorage/sessionStorage) may not be available on some browsers or based on user settings.
Fixes #3066

[All hosts](Web Storage API) add note on Web Storage API availibility

---

docs/develop/develop-overview.md
docs/overview/explore-with-script-lab.md

Pretty simple fix to remove the period from the titles for the Script Lab videos.

[Script Lab](Fix title on videos)

---

docs/excel/custom-functions-debugging.md
docs/testing/debug-desktop-using-edge-chromium.md

We have a broken link pointing to "https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-edge". This PR That extension no longer seems to exist, so the original link has been replaced with a link to what appears to be the new iteration of that extension. The PR also adjusts another indirect reference to that extension.

[DevX] (Edge Debugger) Point links to current iteration of the Edge debugger extension

---

docs/overview/office-add-in-code-samples.md

Changes some links from the samples page to go direct to repo, versus code sample gallery to see if this increases traffic.
Also adds the Outlook encryption sample to the list for discoverability.

[All hosts] Experiment with direct sample links

---

docs/quickstarts/onenote-quickstart.md
docs/testing/sideload-office-add-ins-for-testing.md

Running `npm run start:web -- --document {url}` for a OneNote add-in generated by yo office causes the following error:
```
Debugging is being started...
App type: web
Starting the dev server... (webpack serve --mode development)
The dev server is running on port 3000. Process id: 27556
Sideloading the Office Add-in...
Error: Unable to start debugging.
Error: Unable to sideload the Office Add-in.
Error: Sideload to the OneNote web app is not supported.
```
This PR removes that instruction in favor of manually sideloading the add-in. It also updates the sideloading guidance to mention OneNote. It also updates the sample code to use the "modern JS" pattern of `async`/`await`.

[OneNote] (quickstart) Update OneNote quick start with sideloading guidance

---

docs/develop/application-specific-api-model.md
docs/develop/convert-javascript-to-typescript.md
docs/develop/run-code-on-document-open.md
docs/excel/excel-add-ins-charts.md
docs/tutorials/migrate-vsto-to-office-add-in-shared-code-library-tutorial.md

This PR updates some samples to use "modern JS" (`async`/`await`). Rather than tackling every sample in a single PR, I plan to split the work into area-specific PRs. This batch is the "unrelated" bucket (besides the charts sample where I renamed `ctx` - that will help with future changes).
As part of this, I also noticed the "Convert an Office Add-in project in Visual Studio to TypeScript" project didn't reference the latest version of Visual Studio. The sample code in that article intentionally uses the old `return context.sync()` pattern, but that's intentional to match what's in the default VS files.

[excel] (Samples) Update JS and test VS conversion

---

docs/overview/office-add-in-code-samples.md

Per input from David, update all links to point to GitHub directly instead of the docs samples site.
No longer depends on when PR https://github.com/OfficeDev/Office-Add-in-samples/pull/261 is merged and the Outlook Encrypt Attachments sample indexed.

[all hosts] Update all links to point to GitHub

---

docs/excel/excel-add-ins-data-validation.md
docs/excel/excel-add-ins-pivottables.md
docs/excel/excel-add-ins-worksheets.md
docs/onenote/onenote-add-ins-programming-overview.md
docs/powerpoint/shapes.md

Part of [this internal work item](https://office.visualstudio.com/OC/_workitems/edit/2747466/) and related to #3254. 
This PR changes more of the samples to use the `async`/`await` pattern to reflect modern JS practices.

[PowerPoint] (Shapes) Modernizing sample code for PPT, OneNote, and missed Excel samples

---

docs/quickstarts/word-quickstart.md
docs/tutorials/word-tutorial.md
docs/word/search-option-guidance.md
docs/word/word-add-ins-programming-overview.md

This PR updates the JavaScript samples in the Word-specific articles to match the modern JS patterns that use `async`/`await`.
Reviewers, please note that I was unable to successfully run the Word tutorial with Visual Studio under any circumstance. Please let me know if that problem is happening for you too.

[Word] (Samples) Updating JS patterns in Word articles

---

docs/toc.yml

Our lead for Documentation Strategy already approved this move, so it doesn't need to be reviewed by her again.

[All Hosts] (ia) move same-origin article to more appropriate ToC node

---

docs/reference/manifest/launchevent.md

The SendMode property of the LaunchEvent element is not required. Clarified this in the manifest documentation and added a description for the Block option.

[Outlook] (manifest) Define default SendMode option and add Block option

---

docs/includes/excel-custom-functions-manually-register.md
docs/quickstarts/excel-custom-functions-quickstart.md
docs/tutorials/excel-tutorial-create-custom-functions.md

Addresses feedback from #3315. Tested yo office process and confirmed that manually registering the add-in is usually necessary to access the CONTOSO namespace, on both Windows and Mac.

[Excel] (Custom functions) Update tutorial and quick start to include add-in register instructions

---

docs/develop/initialize-add-in.md

This is to fix #3331. The onReady function does run outside of an Office host, and you get null values in the info object.

[All hosts](initialization) Fix incorrect text about onReady function

---

.openpublishing.redirection.json

We were using these in the TOC so that the context would change to reference instead of staying in conceptual. With the move of reference content to the reference repo, we no longer use these in the TOC.

[all hosts] Remove unused redirects to reference

---

docs/outlook/delegate-access.md
docs/outlook/outlook-add-ins-overview.md

The shared mailbox add-in feature is in preview on Outlook on Windows and on Mac at this time.

[Outlook] (shared mailbox) Remove OWA support for shared mailbox feature

---

docs/concepts/add-in-development-best-practices.md
docs/concepts/browsers-used-by-office-web-add-ins.md
docs/concepts/requirements-for-running-office-add-ins.md
docs/develop/support-ie-11.md
docs/testing/ie-11-testing.md

We will delay publication of this until the new policy is in place, expected to be about May 1st.

[All Hosts] (browsers) IE no longer required by AppSource

---

docs/toc.yml

Per [docs contributor guide](https://review.docs.microsoft.com/en-us/help/contribute/preview-content?branch=main#headings-titles-and-tocs), TOC labels shouldn't include preview tags. Moving to [displayName property](https://review.docs.microsoft.com/en-us/help/contribute/toc-management?branch=main#yaml-toc-format) allows users to search for "preview" and locate the related content.

[all hosts] (TOC) Move preview tag from name to displayName

---

docs/outlook/autolaunch.md
docs/outlook/compare-outlook-add-in-support-in-outlook-for-mac.md
docs/outlook/smart-alerts-onmessagesend-walkthrough.md

Per [Get ready for the new Outlook for Mac](https://techcommunity.microsoft.com/t5/outlook-blog/get-ready-for-the-new-outlook-for-mac/ba-p/2897724) and [The new Outlook for Mac](https://support.microsoft.com/en-us/office/the-new-outlook-for-mac-6283be54-e74d-434e-babb-b70cefc77439), the new Mac UI is now deployed.

[Outlook] (Mac) Remove preview tag from new Mac UI references

---

.openpublishing.redirection.json
docs/concepts/add-in-development-best-practices.md
docs/develop/develop-office-add-ins-for-the-ipad.md
docs/quickstarts/excel-quickstart-vue.md
docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md
docs/testing/debug-office-add-ins-on-ipad-and-mac.md
docs/testing/sideload-an-office-add-in-on-ipad.md
docs/testing/sideload-an-office-add-in-on-mac.md
docs/testing/sideload-office-add-ins-for-testing.md
docs/testing/test-debug-office-add-ins.md
docs/testing/troubleshoot-development-errors.md
docs/toc.yml

Addressing customer suggestion #3502. I agree with the customer's take that using only Finder is more logical for this process. Tested and confirmed steps on Mac OS.

[Testing] (Sideload) Divide iPad and Mac desktop sideloading instructions

---

.openpublishing.redirection.json
docs/excel/performance.md
docs/reference/javascript-api-for-office-error-codes.md
docs/testing/application-specific-api-error-handling.md
docs/toc.yml

This PR moves the error code and handling articles to the testing section of the TOC. It also generalizes the Excel error handling article to cover the whole application-specific space. Finally, it adds a note about when you'd get the `NotImplemented` error (which was the genesis of this PR...)
I'm open to thoughts about where these articles should live in the TOC. This is just my proposal.

[Excel, Word, PPT] (Errors) Abstracting the Excel errors page to app-specific

---

docs/includes/outlook-irm-add-in-activation.md
docs/outlook/outlook-add-ins-overview.md
docs/outlook/privacy-and-security.md
docs/outlook/troubleshoot-outlook-add-in-activation.md

- Remove preview tags and specify that add-ins don't activate on IRM-protected items in Outlook on Mac and on the web.
- Apply minor formatting fixes, such as contractions.

[Outlook] (IRM) Remove preview tags for activation on IRM items feature

---

docs/tutorials/migrate-vsto-to-office-add-in-shared-code-library-tutorial.md

The sample referenced by [Tutorial: Share code between both a VSTO Add-in and an Office Add-in with a shared code library](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/migrate-vsto-to-office-add-in-shared-code-library-tutorial#the-cell-analyzer-vsto-add-in) was updated so you do not need to configure a test certificate. See https://github.com/OfficeDev/Office-Add-in-samples/pull/341 for details.
This PR removes the steps from the tutorial.

[All hosts](VSTO migration) Remove certificate steps

---

docs/outlook/use-regular-expressions-to-show-an-outlook-add-in.md

In response to a [forum post](https://stackoverflow.com/questions/73088079/outlook-add-in-regular-expression-works-on-body-but-not-on-subject) and internal bug 165177.

[Outlook] (manifest) Clarify use of Highlight attribute

---

docs/outlook/autolaunch.md

The same guidance is already provided in [Office.AddinCommands.Event.completed()](https://docs.microsoft.com/en-us/javascript/api/office/office.addincommands.event?view=common-js-preview#office-office-addincommands-event-completed-member(1)).

[Outlook] (autorun) Clarify guidance on calling event.completed

---

docs/outlook/compose-scenario.md

Both Yo Office and Visual Studio projects default to the latest manifest version, so this clause is useless. Removing also makes the article compatible with the JSON manifest.

[Outlook] (manifest) remove unneeded reference to manifest version

---

docs/outlook/manifests.md
docs/outlook/testing-and-tips.md

This is a very minimalist update of two articles to make them compatible with the fact that there is now a JSON-formatted manifest (in preview). 
More extensive updates of one or both of these should be done too with the aim of not duplicating manifest documentation between the Outlook docs and the overall Office Add-in docs.

[Outlook] (manifest) update 2 overviews for JSON manifest awareness

---

docs/outlook/categories.md

Per our [reference documentation](https://learn.microsoft.com/en-us/javascript/api/outlook/office.categories?view=outlook-js-preview#outlook-office-categories-addasync-member(1)), the categories API isn't supported in Compose mode in Outlook on the web.

[Outlook] (categories) Correct categories API support in OWA

---

docs/develop/application-specific-api-model.md
docs/testing/runtimes.md

This PR adds a note to let people know that the undo stack is cleared when an application-specific API is called.
It also does some minor cleanup to the runtimes article, because I considered that article as a place to add this note.
One note for reviewers: I thought about adding information to the custom functions runtime article, but voted against it. Saying non-shared runtimes support undo with CFs sounds too much like an endorsement. However, I'm open to other thoughts.

[all hosts] (Application-specific APIs) Adding undo behavior note

---

docs/outlook/use-rest-api.md

The Outlook REST endpoint decommission date has been postponed (previously scheduled for November 30, 2022). As the new decommission date is still pending and the previously announced date is fast approaching, updated the note about the postponement.

[Outlook] (REST) Update REST endpoint decommission note

---

docs/outlook/debug-autolaunch.md
docs/testing/debug-desktop-using-edge-chromium.md

This is an emergency because a port number change has already been merged in the Custom Functions template for Yo Office: https://github.com/OfficeDev/Excel-Custom-Functions-JS/pull/89/files
The change is too trivial to need a review or to change the metadata dates of the articles.

[All Hosts] (tools) update port number in launch.json

---

docs/outlook/autolaunch-store-options.md

Adds a link to [Manage apps in the Integrated apps portal](https://learn.microsoft.com/microsoft-365/admin/manage/test-and-deploy-microsoft-365-apps#manage-apps-in-the-integrated-apps-portal) for instructions on how admins can consent to recent Store add-in updates.

[Outlook] (event-based) Add link to admin consent process 

---

docs/outlook/autolaunch.md

Adds information that admins must consent to any updates to the manifest of an event-based Outlook add-in.
Related PR: https://github.com/OfficeDev/office-js-docs-pr/pull/3807

[Outlook] (event-based) Add note about admin consent to manifest updates

---

docs/excel/custom-functions-debugging.md

The VSC launch option that this section uses no longer works and is being removed from projects created with Yo Office.

Remove obsolete debugging method

---

docs/includes/outlook-permission-levels-table.md

Reflects the actions allowed with read permissions as described in [Understanding Outlook add-in permissions](https://learn.microsoft.com/office/dev/add-ins/outlook/understanding-outlook-add-in-permissions#can-do-1).

[Outlook] (permissions) Clarify description of read permissions

---

docs/concepts/browsers-used-by-office-web-add-ins.md

This is based on the original question in https://github.com/OfficeDev/office-js-docs-pr/issues/3783. Windows Server 2016+ does support Office Add-ins and WebView2.
This PR also arranges the tables to match the newer-first ordering in [other MSFT documentation](https://learn.microsoft.com/en-us/microsoft-edge/webview2/#supported-platforms). Happy to reverse that change if folks disagree with it. I personally think it helps people understand the current (and most likely) situation quicker.

[all hosts] (Support) Windows Server support notes

---

docs/develop/sso-in-office-add-ins.md
docs/includes/deploy-updates-that-require-admin-consent.md
docs/outlook/manifests.md
docs/publish/deploy-office-add-in-sso-to-azure.md
docs/publish/host-an-office-add-in-on-microsoft-azure.md
docs/publish/maintain-breaking-changes.md
docs/publish/package-your-add-in-using-visual-studio.md
docs/publish/publish-add-in-vs-code.md
docs/publish/publish.md
docs/testing/testing-and-troubleshooting.md

This adds information to relevant articles on when you deploy an updated manifest, and what changes will require the admin to consent again when centrally deployed.

[All hosts](deployment) Add information on when admin consent required again

---

docs/outlook/delegate-access.md

"Web Browser - modern Outlook" documentation has a broken link to blog post from 2013/09/04 configuring-delegate-access-in-outlook-web-app Current: (relative) /microsoft-365/blog/2013/09/04/configuring-delegate-access-in-outlook-web-app/ Changed to: (relative) /en-us/microsoft-365/blog/2013/09/04/configuring-delegate-access-in-outlook-web-app/

Update "Web browser - modern Outlook" blog post link

---

docs/develop/configure-your-add-in-to-use-a-shared-runtime.md

Updates article to warn that all resid values must match in the manifest or shared runtime won't load. Fixes https://github.com/OfficeDev/Excel-Custom-Functions/issues/351

[All hosts](shared runtime) Fix issue all resid values must match

---

docs/resources/resources-links-help.md

As per @TristanD-MSFT's request, we want our support page to look like [that of Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/feedback). This PR merges our information with that format.

[all hosts] (Support) Following Teams support page format

---

docs/concepts/browsers-used-by-office-web-add-ins.md

Fixes the link to a deprecated MDN page. For more context about the deprecation, see https://github.com/mdn/content/pull/24787.

[All hosts] (browser) Fix broken link

---

docs/excel/custom-functions-json-autogeneration.md

The code example provided for the @helpurl parameter does not use the "http://" prefix. If the developer implements it like this it won't work. The automatically created functions.json file does not include the http prefix and Excel fails to recognise it when clicking on it on the desktop app.
The documentation for manually creating the functions.json file correctly indicates the use of the "http://" prefix. See https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-json#json-metadata-example

Added  "http://" prefix to 'helpUrl' parameter example

---

docs/develop/configure-your-add-in-to-use-a-shared-runtime.md

Removed a note about the shared runtime requirement that only applied to Word. it was a bug that has since been fixed.

[Word](shared runtime) remove note on bug that was fixed

---

docs/outlook/append-on-send.md

Based on feedback in #3904:
- Removes `WebViewRuntime.Url` and `JSRuntime.Url` resources from the manifest, as these aren't required for the walkthrough to work.
- Clarifies how the `prependOnSendAsync` and `appendOnSendAsync` methods are activated.

[Outlook] (prepend-on-send) Clarify feature description

---

docs/develop/manifest-element-ordering.md

For some reason, the `<MobileFormFactor>` element was left out of this article.

[Outlook] (manifest) add MobileFormFactor to element ordering article

---

docs/develop/create-sso-office-add-ins-nodejs.md

Typo fix that doesn't need a review.
Fixes [3953](https://github.com/OfficeDev/office-js-docs-pr/issues/3953)

[All Hosts] (auth) typo in node sso tutorial

---

docs/testing/troubleshoot-manifest.md

The instructions for running `npm run validate` are listed twice in this article.
@Rick-Kirkham, I might be missing something, so please let me know if there's a good reason to have this include in both places.

[all hosts] (Manifest) Remove duplicate validate reference

---

docs/develop/develop-office-add-ins-for-the-ipad.md
docs/outlook/add-mobile-support.md
docs/outlook/manifests.md
docs/outlook/mobile-log-appointments.md
docs/outlook/online-meeting.md
docs/outlook/outlook-add-ins-overview.md
docs/outlook/outlook-addin-design.md
docs/outlook/outlook-mobile-addins.md
docs/outlook/sideload-outlook-add-ins-for-testing.md
docs/outlook/use-regular-expressions-to-show-an-outlook-add-in.md
docs/outlook/use-rest-api.md
docs/toc.yml

Replaces "Outlook Mobile" references with "Outlook on mobile devices", "Outlook mobile" (for subsequent uses), "Outlook on Android", and "Outlook on iOS", where applicable. This change aligns the docs with internal guidelines.
Related PR: https://github.com/OfficeDev/office-js-docs-reference/pull/1565

[Outlook] (mobile) Replace Outlook Mobile references

---

docs/develop/register-sso-add-in-aad-v2.md
docs/includes/register-sso-add-in-aad-v2-include.md

The "for example" text in this include file seems like it should use an example, rather than the placeholder text.

[all hosts] (SSO) Fix example API link text

---

docs/develop/install-latest-office-version.md
docs/includes/excel-shared-runtime-preview-note.md
docs/includes/use-legacy-edge-or-ie.md
docs/includes/using-preview-apis-host.md
docs/outlook/append-on-send.md
docs/outlook/contextless.md
docs/outlook/item-multi-select.md
docs/outlook/one-outlook.md
docs/outlook/onmessagefromchanged-onappointmentfromchanged-events.md
docs/outlook/pinnable-taskpane.md
docs/outlook/sensitivity-label.md
docs/overview/explore-with-script-lab.md

The Office Insider program is now referred to as the Microsoft 365 Insider program (https://insider.microsoft365.com). This PR updates references in our documentation.

[All hosts] (insider program) Update references to the Office Insider program

---

docs/publish/government-cloud-guidance.md

This PR updates the sovereign cloud guidance to explicitly call out that centralized deployment is still supported.

[all hosts] (Deployment) Update govt cloud guidance with CD note

---

docs/publish/publish.md

As reported in https://github.com/OfficeDev/office-js-docs-pr/issues/3988, the GoDaddy SKUs of M365 don't support some deployment patterns of add-ins. This PR adds that information

[all hosts] (Publishing) Adding note about GoDaddy SKUs

---

docs/outlook/delegate-access.md

- Clarifies that the specified version numbers to support the shared folders feature in an Exchange on-premises environment is for the Outlook on Windows client.
- Updates the link to the supported clients and platforms table.
Related to #3999.

[Outlook] (shared folders) Clarify on-premises support note

---

docs/develop/xml-manifest-overview.md

Doesn't need a review. Remove IconUrl form list of required elements. Verified with the schema XSD. This also makes the page consistent with the reference page for the OfficeApp element.

[All Hosts] (manifest) IconUrl is NOT required

---

docs/outlook/debug-autolaunch.md

- Adds a step to set the debugger port in the registry.
- Removes the outdated `protocol` property from the launch configuration file in VS Code to address #4035.
- Adds a description for the **bundle.js** file and guidance on how to create it if needed. Addresses feedback in #4007.

[Outlook] (event-based) Refine debugging guidance

---

docs/outlook/item-multi-select.md

Adds a note about additional message properties in preview. The link to the Office.SelectedItemDetails page should be resolved after merging DT changes and running the reference build script.
Related PRs:
- https://github.com/OfficeDev/office-js-docs-reference/pull/1614
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65784

[Outlook] (multi-select) Add note about additional message properties in preview

---

docs/outlook/authenticate-a-user-with-an-sso-token.md
docs/outlook/autolaunch.md
docs/outlook/use-sso-in-event-based-activation.md

Rewrites [Enable single sign-on (SSO) in Outlook add-ins that use event-based activation](https://learn.microsoft.com/office/dev/add-ins/outlook/use-sso-in-event-based-activation) to include CORS requests.

[Outlook] (event-based activation) Add CORS guidance

---

docs/excel/custom-functions-json-autogeneration.md

This is a weird one. We have an article about autogenerating the functions.json file, but the article never explained how to run the tool (or even give the name it)! 
Fixes [4094](https://github.com/OfficeDev/office-js-docs-pr/issues/4094).

[Excel] (custom functions) autogenerate functions.json

---

docs/toc.yml

Updates the displayName attribute of Outlook mobile articles in the TOC based on a review suggestion from https://github.com/OfficeDev/office-js-docs-pr/pull/4078.

[Outlook] (TOC) Update keywords for Outlook mobile articles

---

docs/design/using-office-ui-fabric-react.md

This keeps the TypeScript compiler from complaining about the `Word.run` that "Word" isn't defined.

[All Hosts] (ui) small improvement to react quickstart

---

docs/outlook/sideload-outlook-add-ins-for-testing.md

Adds guidance on how to sideload an add-in in Outlook on the web if the **Get add-ins** option doesn't appear in the ribbon.

[Outlook] (sideloading) Update sideloading instructions for Outlook on the web

---

docs/design/authentication-patterns.md
docs/develop/authorize-to-microsoft-graph.md
docs/develop/sso-in-office-add-ins.md
docs/develop/troubleshoot-sso-in-office-add-ins.md
docs/outlook/authenticate-a-user-with-an-sso-token.md
docs/outlook/authentication.md
docs/outlook/implement-sso-in-outlook-add-in.md

Replaces links to <https://social.technet.microsoft.com/wiki/contents/articles/32711.exchange-online-how-to-enable-your-tenant-for-modern-authentication.aspx)> with <https://learn.microsoft.com/exchange/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online>. The latter is hosted on the Learn site and is still being maintained.
Related PR: https://github.com/OfficeDev/office-js-docs-reference/pull/1657

[All hosts] (SSO) Update link to modern authentication resource

---

docs/outlook/spam-reporting.md

- Provides guidance on the use of Office.MailboxEnums.MoveSpamItemTo.
- Updates sample to use the enum.
- Adds links to API references per feedback from PM.
Related PRs:
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66280
- https://github.com/OfficeDev/office-js-docs-reference/pull/1652

[Outlook] (spam reporting) Add enum support

---

docs/develop/unified-manifest-overview.md

Teams is updating their developer docset to reflect branding guidance regarding the shared manifest (omiting "Teams" branding in favor of the general term "app manifest",and using _unified_ as a descriptive adjective / disambiguator as needed). This PR is to shore up terminology on Add-ins side; using "app manifest" for first usage of each section and in title/metadata.

Shore up "app manifest" shared terminology

---

docs/outlook/spam-reporting.md

Based on partner feedback:
- Adds a note that the unified manifest isn't yet supported for the integrated spam-reporting feature.
- Adds guidance on how to implement a task pane in a spam-reporting add-in.

[Outlook] (spam reporting) Add note on unified manifest and task pane implementation

---

docs/outlook/spam-reporting.md

The docs request one to create `spamreporting.js` file that will be used as the entry point for the event handling, but the `xml` file still has the "old" entry point.

Update js file source to be correct one

---

docs/concepts/browsers-used-by-office-web-add-ins.md

Support for WebView2 in WIP-protected documents was released in the July fork. This PR updates the relevant information.

[all hosts] (Runtime) Updating support information for WIP-protected documents

---

docs/onenote/index.yml

This page has low click-through rate and high exit rate. People weren't clicking where we would expect them to. This change restructures the page to guide them to the quick start and a sample.

[OneNote] Refresh OneNote landing page

---

docs/index.yml

Our hub page has higher-than-expected bounce rates and exit rates. This PR removes some of the links to pages with lower clicks. and promotes some scenarios, with the intention to substitute newer scenarios as they come online.

[all hosts] Rework hub page to be more scenario/intent focused 

---

docs/overview/create-an-office-add-in-from-script-lab.md
docs/overview/explore-with-script-lab.md
docs/toc.yml

This PR adjusts the Samples node in the TOC. Previously, a few samples existed there, but it didn't represent the full breadth of our sample library and may have given false impressions. The existing sample pages have been moved elsewhere in the TOC.
This PR also makes a tighter connection between the Script Lab article and the sample to convert a Script Lab snippet into an add-in.

[all hosts] (TOC) Remove Samples node from TOC

---

docs/testing/debug-add-ins-in-office-online.md
docs/testing/debug-add-ins-using-devtools-edge-chromium.md

@elegault updated debugging guidance for new Outlook on Windows in https://github.com/OfficeDev/office-js-docs-pr/pull/4320. This PR adds that guidance to other key debugging articles.

[Outlook] (new Outlook on Windows) Update debugging guidance

---

docs/index.yml

This PR fixes the mislabeled Word quick start link. It also changes the text to prioritize for scanning - the only difference between the links is the application, so that should go first.

[all hosts] (IA) Fix quick start link text on index page

---

docs/outlook/delegate-access.md
docs/outlook/on-new-compose-events-walkthrough.md
docs/outlook/pinnable-taskpane.md
docs/outlook/smart-alerts-onmessagesend-walkthrough.md

Swaps the order of the unified manifest and XML manifest tabs in Outlook walkthroughs. Articles not covered in this PR are being worked on in other PRs.

[Outlook] (manifest) Swap order of manifest tabs in walkthroughs

---

docs/outlook/contextual-outlook-add-ins.md

Adds a retirement note to the contextual add-in article that was missed in https://github.com/OfficeDev/office-js-docs-pr/pull/4362.

[Outlook] (contextual add-ins) Add retirement note

---

docs/outlook/autolaunch.md

Fixes [#3733](https://github.com/OfficeDev/office-js/issues/3733). Replaces the CORS requirements list with a link to the official docs to ensure that the information is always up to date.

[Outlook] (event-based activation) Replace CORS requirements with link

---

docs/word/search-option-guidance.md

Adding example based on verbatim feedback. Clarifies how to search with a wildcard for an escaped special character.

[Word] (wildcard search) Escaped special character

---

docs/outlook/use-rest-api.md

Fixes #4390.
Outlook add-in exemption from the REST endpoint deprecation is no longer identified by the add-in ID. It's now identified through add-in traffic.

[Outlook] (REST) Clarify note on add-in exemption

---

docs/includes/outlook-contextual-add-ins-retirement.md
docs/outlook/use-regular-expressions-to-show-an-outlook-add-in.md

Specifies when entity-based contextual Outlook add-ins will be retired and indicates which APIs will be affected.

[Outlook] (contextual add-ins) Clarify retirement timeline

---

docs/concepts/requirements-for-running-office-add-ins.md
docs/develop/convert-xml-to-json-manifest.md
docs/develop/debug-office-add-ins-in-visual-studio.md
docs/develop/dialog-best-practices.md
docs/develop/dialog-video.md
docs/develop/install-latest-office-version.md
docs/develop/teams-toolkit-overview.md
docs/develop/yeoman-generator-overview.md
docs/excel/excel-add-ins-worksheet-functions.md
docs/excel/excel-data-types-entity-card.md
docs/excel/excel-data-types-overview.md
docs/excludes/excel-quickstart-angular.md
docs/includes/mac-cache-folders.md
docs/powerpoint/insert-slides-into-presentation.md
docs/quickstarts/excel-custom-functions-quickstart.md
docs/quickstarts/excel-quickstart-react.md
docs/quickstarts/outlook-quickstart-json-manifest.md
docs/quickstarts/powerpoint-quickstart.md
docs/quickstarts/sso-quickstart.md
docs/testing/attach-debugger-from-task-pane.md
docs/testing/clear-cache.md
docs/testing/debug-add-ins-using-devtools-edge-chromium.md
docs/testing/debug-add-ins-using-f12-tools-ie.md
docs/testing/runtime-logging.md
docs/testing/testing-and-troubleshooting.md
docs/tutorials/excel-tutorial-create-custom-functions.md
docs/tutorials/excel-tutorial.md
docs/tutorials/migrate-vsto-to-office-add-in-shared-code-library-tutorial.md
docs/tutorials/word-tutorial.md

Based on @samantharamon's feedback in https://github.com/OfficeDev/office-js-docs-pr/pull/4400, current guidance is to refrain from stating an image is a screenshot in the alt text. This PR addresses that.

[admin] (Accessibility) Remove the term 'screenshot' from image alt text

---

docs/project/create-a-project-add-in-that-uses-rest-with-an-on-premises-odata-service.md
docs/project/project-add-ins.md

Fixes #4430.
This PR removes the references to Project 2013, since the same information applies to subsequent versions of Project.

[project] Remove specific references to Project 2013

---

docs/includes/outlook-irm-add-in-activation.md
docs/outlook/outlook-add-ins-overview.md
docs/outlook/privacy-and-security.md
docs/outlook/troubleshoot-outlook-add-in-activation.md

- Clarifies when Outlook add-ins activate on mail items protected by Information Rights Management (IRM).
- Moves guidance to its own section.
- Removes redundant information from "Troubleshoot Outlook contextual add-in activation" already covered by the link to the "Outlook add-ins overview" page.

[Outlook] (IRM) Update guidance

---

docs/outlook/debug-autolaunch.md

Adding `UseDirectDebugger` as a registry key does not work. It needs to be a DWORD value.

[Outlook] (debug) UseDirectDebugger should be a DWORD value not a registry key

---

docs/develop/add-ins-with-angular2.md

We received some feedback that the recommend to use the hash location strategy was outdated. That is necessary for Trident-based browsers, so this PR revises the article to make that clear. This also includes a quick pass for style and whatnot.

[all] (Frameworks) Update Angular article to talk about hash location only for Trident

---

docs/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog.md

The tab name for SharePoint app catalogs is now called "My Organization". This PR updates the article to reflect that.

[all] (Publishing) Update SP App Catalog folder name

---

docs/develop/convert-xml-to-json-manifest.md

[All Hosts] (manifest) document function name length limitation

---

docs/outlook/one-outlook.md

This PR also removes the Insiders requirement to use new Outlook on Windows.

[Outlook] (debugging) Clarify debugging steps for new Outlook on Windows

---

docs/publish/publish-office-add-ins-to-appsource.md
docs/toc.yml

This adds information on how to create an install link for your add-in. Also removes the direct link to the Microsoft AppSource publishing page and instead provides a brief overview in this content library.

[All hosts] (publishing) Add information on creating an install link

---

docs/publish/publish.md

Fixes #4613.
Outlook add-ins can be deployed through Integrated Apps (as mentioned [here](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/test-and-deploy-microsoft-365-apps?view=o365-worldwide#what-controls-are-available-on-the-integrated-apps-portal)). This PR corrects the publishing table to reflect that.

[Outlook] (Deployment) Corrects support for Outlook through Integrated Apps

---

docs/overview/explore-with-script-lab.md

While the ability to save snippets from Script Lab as gists was removed, the import option still exists. This PR clarifies that behavior.

[all] (Script Lab) Add note about importing gist links with Script Lab

---

docs/develop/json-manifest-overview.md
docs/develop/troubleshoot-sso-in-office-add-ins.md
docs/excel/excel-add-ins-events.md
docs/excel/excel-add-ins-multiple-ranges.md
docs/outlook/testing-and-tips.md
docs/tutorials/powerpoint-tutorial.md

Updating [per guidance](https://learn.microsoft.com/en-us/style-guide/grammar/nouns-pronouns#plural-nouns) that we shouldn't use "(s)" to indicate variable singular vs plural. Also, screen readers don't read it properly.

[all hosts] Remove (s)

---

docs/develop/troubleshoot-sso-in-office-add-ins.md
docs/testing/testing-and-troubleshooting.md

Fiddler now has a free trial instead of a free plan. This PR updates our documentation to reflect that. It also adds another HTTP intercept option, Requestly, for people looking for a free (or freemium) service.

[all hosts] (Troubleshooting) Update HTTP intercept recommendations

---

docs/develop/built-in-ui-ids.md

In conjunction with PR [2008](https://github.com/OfficeDev/office-js-docs-reference/pull/2008) in the reference repo, this moves the list of built-in Office ribbon tab IDs from a manifest reference topic to a separate article that can be linked to from both the XML and unified manifest reference. 
This article is not in the ToC because it will soon be moved to the M365 doc set.

[All Hosts] (ui) move list of built-in tab ids to separate article

---

docs/excludes/outlook-quickstart-json-manifest-typescript.md
docs/includes/node-20-warning-note.md
docs/quickstarts/excel-quickstart-jquery.md
docs/quickstarts/excel-quickstart-react.md
docs/quickstarts/onenote-quickstart.md
docs/quickstarts/outlook-quickstart.md
docs/quickstarts/powerpoint-quickstart.md
docs/quickstarts/project-quickstart.md
docs/quickstarts/sso-quickstart.md
docs/quickstarts/word-quickstart.md
docs/tutorials/excel-tutorial-create-custom-functions.md
docs/tutorials/excel-tutorial.md
docs/tutorials/outlook-tutorial.md
docs/tutorials/powerpoint-tutorial.md
docs/tutorials/word-tutorial.md

I haven't seen this warning about Node.js version 20 not being supported. I think the underlying yo office bits have updated. As such, we should remove this note in the docs.

[all hosts] (yo office) Remove warning about Node v20 support

---

docs/quickstarts/outlook-quickstart.md

The Yo Office template now includes the JS code from the Outlook quick start. This PR removes the now redundant step from the quick start.

[Outlook] (quick start) Remove redundant step

---

docs/develop/configure-your-add-in-to-use-a-shared-runtime.md
docs/develop/convert-xml-to-json-manifest.md
docs/develop/create-sso-office-add-ins-nodejs.md
docs/develop/use-sso-to-get-office-signed-in-user-token.md
docs/excel/custom-functions-debugging.md
docs/excludes/outlook-quickstart-json-manifest-typescript.md
docs/outlook/append-on-send.md
docs/outlook/contextless.md
docs/outlook/item-multi-select.md
docs/outlook/on-new-compose-events-walkthrough.md
docs/outlook/onmessagefromchanged-onappointmentfromchanged-events.md
docs/outlook/sideload-outlook-add-ins-for-testing.md
docs/outlook/smart-alerts-onmessagesend-walkthrough.md
docs/overview/create-an-office-add-in-from-script-lab.md
docs/quickstarts/fluent-react-quickstart.md
docs/testing/sideload-office-add-ins-for-testing.md
docs/tutorials/excel-tutorial.md
docs/tutorials/outlook-tutorial.md
docs/tutorials/powerpoint-tutorial.md
docs/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial.md
docs/tutorials/word-tutorial.md

Already added stop / uninstall instructions to quick starts. Now adding instructions for other places that use `npm start` or `npm run start`.

[all hosts] Add stop/uninstall instructions to non quick starts

---

docs/develop/convert-xml-to-json-manifest.md

I tried `npx office-addin-manifest-converter convert -m <relative-path-to-XML-manifest>` but I got an error message "error: unknown option '-m'". When I checked the [npm package docs](https://www.npmjs.com/package/office-addin-manifest-converter), there's no '-m'. I tried without '-m' then the command succeeded.

[all hosts] Remove extra param from convert command

---

docs/develop/create-addin-commands.md
docs/develop/manifest-element-ordering.md

1. Partially fixes verbatim. There will also be a correlative PR in the -reference repo. The `<Tooltip>` element is only supported in Outlook and only as a child of `<Group>`. 
2. Also removing mention of **entirely mythical** `<ControlGroup>` element that I added 4 years ago. I have absolutely no record or memory of why I did.

[All Hosts] (manifest) Tooltip only supported in Outlook Group

---

docs/includes/script-lab-outlook-web.md
docs/outlook/delay-delivery.md
docs/outlook/get-and-set-recurrence.md
docs/overview/explore-with-script-lab.md
docs/overview/set-up-your-dev-environment.md

Script Lab was recently updated to overcome the documented challenge around storage partitioning. Since the add-in now works on Outlook on the web, this PR removes the note indicating it does not.

[Outlook] (Script Lab) Remove note about Script Lab not working on the web

---

docs/outlook/spam-reporting.md

Updates a spam-reporting add-in's behavior when the Reading Pane is turned off and when multiple messages are being reported.

[Outlook] (spam reporting) Update behavior in certain scenarios

---

docs/publish/maintain-breaking-changes.md

Based on [this response](https://github.com/OfficeDev/office-js/issues/4683#issuecomment-2349818725), we should avoid suggesting folks can use the office.js NPM package.

[all hosts] (office.js) Remove mention of office.js npm package use

---

docs/design/contextual-tabs.md

- Documents how to specify icons used in the contextual tab in the XML manifest. (The unified manifest will be addressed in a separate PR.)
- Updates icon guidance for contextual tabs.
- Moves notes to their own section.

[Excel] (contextual tabs) Add step to specify icons in manifest

---

docs/design/fabric-core.md
docs/tutorials/excel-tutorial.md
docs/tutorials/outlook-tutorial.md

This PR updates the stylesheet URLs for Fabric Core, in alignment with the current [Fabric Core documentation](https://developer.microsoft.com/en-us/fluentui#/get-started/web#fabric-core).
Sometime on 2024-09-18 the CORS policy changed for the files hosted on https://static2.sharepointonline.com.
This caused a broad outage for our Outlook Addin and users were prevented from sending specific emails. It would appear that the CORS policy has been reverted for now.

Update Fabric Core URLs which were blocked by CORS policy

---

docs/outlook/onmessagesend-onappointmentsend-events.md
docs/outlook/smart-alerts-onmessagesend-walkthrough.md

Documents support to modify the **Don't Send** button of a Smart Alerts dialog to run a function.

[Outlook] (Smart Alerts) Document support for function commands in dialog

---

docs/onenote/index.yml
docs/project/index.yml
docs/visio/index.yml

This PR adds links to landing page that are in the "Resource" swimlane of the dev portals. We are retiring Visio, Project, OneNote and so I added these missing resources to the landing page so the transition from Portal back to Learn has the same content.

Update landing page

---

docs/powerpoint/powerpoint-add-ins.md

This article had low engagement last month

[PowerPoint] (overview) Refresh

---

docs/develop/development-kit-overview.md

The link for downloading VS Code was pointing to Visual Studio instead. This PR fixes that.

[admin] Fix VS Code link

---

docs/develop/enable-nested-app-authentication-in-your-add-in.md
docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md

This updates the walkthrough and FAQ with latest updates around NAA preview and GA.

[All hosts] (NAA) Latest NAA updates

---

docs/outlook/debug-autolaunch.md
docs/testing/runtime-logging.md

The Windows-only instructions for runtime logging aren't needed, since the easier-to-use tool now works with all supported versions of npm.

[all hosts] (DevX) Remove unnecessary Windows-specific runtime logging instructions

---

docs/toc.yml

A quick PR to remove the SSO quick start from prominence in the TOC. When we get an NAA quick start, we should reexamine where to put that.

[admin] (TOC) Deprioritize SSO quick start

---

docs/develop/convert-xml-to-json-manifest.md

The teamsfx CLI has been deprecated. It is being replaced by the teamsapp CLI.

[All Hosts] (sideloading) change teamsfx CLI to teamsapp CLI

---

docs/includes/outlook-bundle-js.md
docs/outlook/debug-autolaunch.md
docs/outlook/troubleshoot-event-based-and-spam-reporting-add-ins.md

- Documents how to debug event-based and spam-reporting add-ins using the Microsoft Edge Inspect tool.
- Adds guidance on how to access an add-in's **bundle.js** file. Fixes #4931.

[Outlook] (debugging) Document how to debug add-ins using Microsoft Edge Inspect

---

docs/develop/enable-nested-app-authentication-in-your-add-in.md
docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md
docs/outlook/turn-exchange-tokens-on-off.md
docs/publish/publish-nested-app-auth-add-in.md
docs/toc.yml

This article is a how to on adding admin consent to your Office add-in deployment when updating. You can use either an admin consent URI, or the unified manifest.
also some updates to the FAQ and other articles based on recent activity.

[All hosts](deployment) Add article on admin consent

---

docs/testing/sideload-office-add-ins-for-testing.md

We had a comment saying the reader couldn't find the Outlook sideloading instructions. If you're skimming the article, I think it's easy to miss the link in the second list, so I added an explicit note up top. Open to thoughts on the necessity or strategy.

[Outlook] (DevX) Add note referencing Outlook

---

docs/develop/asynchronous-programming-in-office-add-ins.md

The [Asynchronous programming in Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/asynchronous-programming-in-office-add-ins?view=common-js-preview) article has a low engagement score according to our internal metrics. This PR aims to spruce up the article in the following ways:
- Assume the reader has greater knowledge of JS programming patterns.
- Increase the number of indications this pertains to the Common APIs.
- Apply a general style check and writing refresh.
If you think I've pruned too much or changed the meaning of something, please let me know.

[all hosts] (Common APIs) Trimming down Common async article

---

docs/develop/asynchronous-programming-in-office-add-ins.md
docs/overview/core-concepts-office-add-ins.md

This PR refreshes the stale lifecycle overview page. It removes an early link and clarifies some of the text with important keywords.
This PR also includes some changes meant to be in #4975 that were accidentally omitted.

[all hosts] (Overview) Refresh lifecycle overview page

---

docs/develop/manifest-element-ordering.md

These are children of DefaultSettings, not peers. 
Doesn't need a review.
Fixes [4974](https://github.com/OfficeDev/office-js-docs-pr/issues/4974)

[All Hosts] (manifest) correct placement of RequestedWidth/Height elements

---

docs/develop/referencing-the-javascript-api-for-office-library-from-its-cdn.md

This PR documents that Office.js nulls out a couple web APIs when loaded. This has been brought up in a few customer issues:
- https://github.com/OfficeDev/office-js/pull/2808
- https://github.com/OfficeDev/office-js/issues/1344
- https://stackoverflow.com/questions/42642863/office-js-nullifies-browser-history-functions-breaking-history-usage

[all hosts] (Initialization) Document browser state method null workaround

---

docs/outlook/add-mobile-support.md

Related to https://github.com/OfficeDev/office-js-docs-pr/issues/4995.

[Outlook] (mobile) Clarify MobileFormFactor code snippet

---

docs/concepts/correlated-objects-pattern.md

As a follow up to improving the correlated objects pattern article's engagement (https://github.com/OfficeDev/office-js-docs-pr/pull/4992), I've added a Script Lab sample readers can use to interactively follow along. This PR adds the links to that sample.

[all hosts] (Performance) Update correlated objects pattern article with sample link

---

docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md

Adding testing guidance for NAA add-ins for Outlook on Windows versions.

[Outlook](NAA) add testing guidance to FAQ

---

docs/design/content-add-ins.md
docs/develop/requirements-property-unified-manifest.md

DO NOT MERGE UNTIL PUBLIC PREVIEW OF UNIFIED MANIFEST IN WXP.

[Excel PowerPoint] (content addins) add support for unified manifest

---

docs/design/contextual-tabs.md

Describes how to define icons for the contextual tab in an add-in that uses the unified manifest.

[Excel] (contextual tab) Define icons in the unified manifest

---

docs/overview/set-up-your-dev-environment.md

Based on upstream changes to the Office Add-ins tooling for the linter: https://github.com/OfficeDev/Office-Addin-Scripts/pull/917

[all hosts] (Developer Experience) Adjust lint configuration for eslint v9

---

docs/design/contextual-tabs.md
docs/develop/application-specific-api-model.md

Application-specific APIs no longer universally clear the undo stack. This PR changes the docs to reflect that. It also removes a warning linked to a closed issue.

[Excel, Word, PowerPoint] (Application-specific APIs) Document partial undo support

---

.openpublishing.redirection.json

The toolkits link is redirecting to a non-existent link: https://learn.microsoft.com/en-us/office/dev/add-ins/design/office/dev/add-ins/design/add-in-design-language

[all hosts] Fix bug in redirection file

---

docs/outlook/add-and-remove-attachments-to-an-item-in-a-compose-form.md
docs/outlook/smart-alerts-onmessagesend-walkthrough.md

Related to https://github.com/OfficeDev/office-js-snippets/pull/962.

[Outlook] (attachment) Update addFileAttachmentFromBase64Async code samples

---

docs/develop/dialog-api-in-office-add-ins.md
docs/develop/dialog-best-practices.md

- Adds a note about the `window.name` property in Outlook on the web and new Outlook on Windows.
- Replaces "gotcha" to align with the style guide.
- Adds behaviors/limitations from the Remarks section of the `displayDialogAsync` method.
- Applies minor formatting fixes for consistency.

[All hosts] (dialog) Update Dialog API articles

---

docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md
docs/outlook/turn-exchange-tokens-on-off.md

Adds documentation for how to get a list of add-ins using legacy Exchange Online tokens.

[Exchange](legacy tokens) How to get list of add-ins using Exchange tokens

---

docs/develop/dialog-handle-errors-events.md

Fixes https://github.com/OfficeDev/office-js/issues/3926.
Related PR: https://github.com/OfficeDev/office-js-docs-reference/pull/2224

[Outlook] (dialog) Update description for error 12004

---

docs/outlook/add-and-remove-attachments-to-an-item-in-a-compose-form.md

Related PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/72187

[Outlook] (attachments) Clarify support for BMP attachments

---

docs/outlook/item-multi-select.md

Replaces the platform check to a requirement set check for the `loadItemByIdIAsync` call.

[Outlook] (item multi-select) Update walkthrough

---

docs/design/contextual-tabs.md

support for overridenByRibbonApi was mistakenly left out of the "ribbons.tabs.groups" property in the manifest schema. It is now supported, so updating the docs to match.

[All Hosts] (ui) overriddenByRibbonAPI support for groups

---

docs/testing/debug-add-ins-overview.md

We have these debug versions of office.js on the CDN. They occasionally get referenced on Stack, so it seems like we should have an official statement about them.

[all hosts] (Debugging) Add section about the debug versions of office.js

---

docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md

Priority Matrix for Outlook was in the first wave of add-ins that migrated to using NAA, and was featured in Microsoft's own post about it: https://techcommunity.microsoft.com/blog/microsoft_365blog/app-assure-puts-security-first-for-microsoft-outlook-customers/4398151
It has also been in the "Editor's choice" category for years.

Include Appfluence Priority Matrix in the list of updated add-ins

---

docs/design/add-in-icons-monoline.md
docs/develop/configure-your-add-in-to-use-a-shared-runtime.md
docs/develop/json-manifest-overview.md
docs/develop/unified-manifest-overview.md
docs/includes/deploy-updates-that-require-admin-consent.md
docs/publish/maintain-breaking-changes.md
docs/publish/publish-nested-app-auth-add-in.md
docs/tutorials/excel-tutorial.md

This PR updates some links that sent readers to the Teams docs instead of the common M365 docs.

[all hosts] (Unified Manifest) Update links to the Teams version of the unified manifest reference

---

Contributing.md
docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md
docs/outlook/outlook-on-send-addins.md
docs/outlook/turn-exchange-tokens-on-off.md

Fixes #4996.
Commands pasted into the command line should use the standard dash character, not the en dash (that text editors would replace the hyphen with).

Replace en dashes with hyphens in command lines

---

docs/powerpoint/work-with-tables.md

In the current version of the [Table object](https://learn.microsoft.com/javascript/api/powerpoint/powerpoint.table), the properties and methods seem to be read-only / gets, including `values`.

[PowerPoint] (tables) Change way to update values in existing table

---

docs/develop/convert-xml-to-json-manifest.md
docs/develop/import-teams-toolkit.md
docs/toc.yml

This PR responds to customer confusion by splitting an article in two. There are now separate articles for (1) converting an XML manifest to JSON, and (2) importing a project into Teams Toolkit.

[All Hosts] (devx) Split manifest conversion and Teams Toolkit articles

---

docs/develop/create-addin-commands-unified-manifest.md
docs/develop/unified-manifest-overview.md
docs/includes/non-unified-manifest-clients.md
docs/outlook/compare-outlook-add-in-support-in-outlook-for-mac.md
docs/outlook/outlook-mobile-addins.md

- Clarifies that add-ins that use the unified manifest for Microsoft 365 must be a published AppSource add-in to run on platforms that don't directly support the unified manifest.
- Moves the information about platform support to its own section in [Office Add-ins with the unified app manifest for Microsoft 365](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/unified-manifest-overview).

[All hosts] (unified manifest) Correct support for platforms that aren't directly supported

---

docs/quickstarts/powerpoint-quickstart-vs.md
docs/toc.yml

- Work with low engagement article: Confirmed that PowerPoint VS quick start is in a good state so updated ms.date
- Moved the VS quick starts and tutorial from the VSTO/COM transition section: Hoping to improve engagement by placing in VS section of TOC

[all hosts] (TOC) Move VS quick starts and tutorials

---

docs/testing/clear-cache.md

If the Office cache is missing a manifest that was manually deleted, all add-ins can fail to load. Users should follow the standard cache clearing protocol.

[all hosts] (Troubleshooting) Add note about partial cache clearing

---

docs/develop/dialog-api-in-office-add-ins.md
docs/overview/learning-path-beginner.md
docs/overview/learning-path-transition.md

https://github.com/MicrosoftDocs/learn-m365-pr/pull/10063 removes the underutilized and poor performing Office Learn Training modules. This PR removes the references to those in this doc set.

[admin] (Links) Remove references to outdated training content

---

docs/design/add-in-commands.md

Mainly removes misleading info about "default" ribbon tabs. A few other small improvements.

[All Hosts] (ui) remove 'default' verbiage from add-in commands

---

docs/excel/make-custom-functions-compatible-with-xll-udf.md

Removes link for now to prevent it from appearing in the broken link report. The link will be added once the schema reference documentation is updated.

[Excel] (custom functions) Remove broken link

---

docs/excel/excel-add-ins-troubleshooting.md

The related issue appears to have been fixed, so the troubleshooting note needs to be removed.

[excel] (Images) Remove Range.getImage note for Mac

---

docs/excel/excel-add-ins-data-validation.md
docs/excel/excel-add-ins-delay-in-cell-edit.md
docs/excel/excel-add-ins-multiple-ranges.md
docs/excel/excel-add-ins-ranges-large.md
docs/excel/excel-add-ins-ranges-precedents-dependents.md
docs/excel/excel-add-ins-ranges-special-cells.md
docs/excel/performance.md

This PR updates Excel articles flagged for low engagement, using suggestions from GitHub Copilot that have then been reviewed and revised by a human. 
Related PRs: 
#5364
#5378

[Excel] Update low engagement articles

---

docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md
docs/outlook/turn-exchange-tokens-on-off.md

This is an update to the FAQ and cmdlets article now that all legacy tokens are off on all tenants.
- Removed time dependent references that are old.
- Added notes about exemptions which some admins previously requested.
- Added info about cmdlet behavior when tokens are disabled.
-

[Outlook](legacy tokens) Update FAQ now that all legacy tokens off

---

.openpublishing.redirection.json
docs/develop/automatically-open-a-task-pane-with-a-document.md
docs/develop/run-code-on-document-open.md
docs/publish/manage-trust-options.md
docs/toc.yml

A new setting, `Office.context.document.settings.set("Office.DisableTrustUX", true);` can be used to stop Office from prompting users to trust an add-in that they don't have, but the document references.

[all hosts] (Trust Prompts) Add information about suppressing the trust prompt for non-installed add-ins
