- docs/design/disable-add-in-commands.md
Too trivial to require a review.
> [PowerPoint] (ui) PPT now supports enable/disable commands

- docs/outlook/index.yml
Change SO to Q&A
Change UV to TC Ideas forum
> Update resources in index.yml

- docs/outlook/autolaunch.md
Based on feedback on PR https://github.com/OfficeDev/office-js-docs-pr/pull/2680
> [Outlook] (preview) Note why registry key needed for beta event-based

- docs/reference/manifest/override.md
- docs/reference/manifest/runtime.md
- docs/reference/manifest/runtimes.md
Related to issue https://github.com/OfficeDev/office-js-docs-pr/issues/2657
> [Outlook] (preview) Runtime Override element

- docs/outlook/autolaunch.md
Related to issue https://github.com/OfficeDev/office-js/issues/1861.
> [Outlook] (event-based) No imports allowed

- docs/overview/office-add-ins-community-call.md
Added links for April and May 2021 calls.
> [All hosts](community call)

- docs/powerpoint/add-slides.md
Fixes #2723 by adding the steps to enable preview APIs in an API to the add slides topic.
> [PowerPoint] Clarifying Slide add/delete availability

- docs/excel/excel-add-ins-events.md
- docs/excel/excel-add-ins-worksheets.md
This PR adds: 
- A note about onFormulaChanged in the Events article
- An article section about onFormulaChanged in the Worksheets article
> [Excel] (Events) (Worksheets) Add onFormulaChanged conceptual docs

- docs/outlook/delegate-access.md
@JuaneloJuanelo This update should be published by early next week
> [Outlook] (delegate) Update getSharedPropertiesAsync anchor

- .gitignore
- docs/excel/excel-add-ins-events.md
- docs/excel/excel-add-ins-workbooks.md
This PR adds:
- A note about Workbook.onActivated in the Events article
- An article section about onActivated in the Workbook article
> [Excel] (Workbook) Add onActivated conceptual docs

- docs/reference/manifest/action.md
- docs/reference/manifest/group.md
fixes [2737](https://github.com/OfficeDev/office-js-docs-pr/issues/2737)
> [Outlook] (manifest) specify non-support for some elements in Outlook

- docs/includes/file-get-the-whole-document-from-an-add-in-for-powerpoint-or-word.md
> [Word] (typo) Fix code sample

- docs/quickstarts/outlook-quickstart.md
Helps address issue https://github.com/OfficeDev/office-js-docs-pr/issues/2707.
> [Outlook] (quick start) How to handle unauthorized with VS

- docs/develop/create-sso-office-add-ins-aspnet.md
- docs/includes/sso-tutorial-prereqs.md
Also adds a way of forcing a test of the fallback path.
> [All Hosts] (auth) Update SSO ASP.NET tutorial to use MSAL 4.x.x

- docs/quickstarts/excel-quickstart-vue.md
> [excel] (Quick Start) Update Vue quickstart for Vue3

- docs/concepts/browsers-used-by-office-web-add-ins.md
- docs/develop/support-ie-11.md
- docs/overview/explore-with-script-lab.md
- docs/testing/ie-11-testing.md
Fixes [2756](https://github.com/OfficeDev/office-js-docs-pr/issues/2756)
> [All Hosts] (ie) clarify non-significance of IE deprecation

- docs/excel/excel-add-ins-events.md
- docs/excel/excel-add-ins-pivottables.md
- docs/excel/excel-add-ins-ranges-precedents-dependents.md
- docs/excel/excel-add-ins-ranges-set-get.md
- docs/excel/excel-add-ins-tables.md
- docs/excel/excel-add-ins-workbooks.md
- docs/excel/excel-add-ins-worksheets.md
- docs/reference/requirement-sets/excel-api-1-13-requirement-set.md
- docs/reference/requirement-sets/excel-api-online-requirement-set.md
- docs/reference/requirement-sets/excel-preview-apis.md
This PR: 
- Adds a new ExcelApi 1.13 requirement set article 
- Updates the ExcelApiOnline and Preview articles 
- Removes Preview and Online-only tags from the article sections for APIs released to GA with 1.13
> [Excel] Promote ExcelApi 1.13 requirement set to GA

- docs/outlook/outlook-addin-design.md
Fixes [2778](https://github.com/OfficeDev/office-js-docs-pr/issues/2778)
This is too trivial to need a review.
> [Outlook] (ui) Change recommendation from Framework7 to Fluent UI

- docs/outlook/use-rest-api.md
Related to issue https://github.com/OfficeDev/office-js-docs-pr/issues/2382.
> [Outlook] (REST) APIs deprecated

- docs/reference/requirement-sets/excel-api-1-13-requirement-set.md
I was looking at this page and saw an opportunity to increase conceptual article discoverability. Please let me know if there link destinations make sense.
> [excel] (ExcelApi 1.13) Adding links to new conceptual article sections

- docs/outlook/online-meeting.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2774.
> [Outlook] (online meeting) Include timeout length

- docs/design/contextual-tabs.md
* [Excel] (ribbon) open task panes from contextual tabs
Co-authored-by: Linda Lu Cannon <lindalu@microsoft.com>
* get rid of unnecessary 'can's
Co-authored-by: David Chesnut <davech@microsoft.com>
* review change
Co-authored-by: Linda Lu Cannon <lindalu@microsoft.com>
Co-authored-by: David Chesnut <davech@microsoft.com>
> [Excel] (ribbon) open task panes from contextual tabs (#2803)

- docs/concepts/browsers-used-by-office-web-add-ins.md
Looks like the original page as taken down or moved. @Rick-Kirkham feel free to suggest a better link if you know of one.
> [admin] (Links) Fix ms-overflow-style link

- docs/develop/auth-with-office-dialog-api.md
- docs/develop/dialog-api-in-office-add-ins.md
- docs/develop/dialog-best-practices.md
- docs/reference/requirement-sets/dialog-api-requirement-sets.md
- docs/reference/requirement-sets/dialog-origin-requirement-sets.md
- docs/reference/requirement-sets/office-add-in-requirement-sets.md
- docs/toc.yml
Note to reviewers: The two "TBD"s in the requirement set article are intentional. We need to publish before these values are available.
> [All Hosts] (dialog) support for cross-domain messaging

- docs/testing/clear-cache.md
- docs/testing/sideload-office-add-ins-for-testing.md
Customer issue #1137 and [internal work item](https://office.visualstudio.com/OC/_workitems/edit/4924870).
> [All hosts] (Debugging) Update cache clear article to include web link

- docs/outlook/outlook-on-send-addins.md
Also related to issue https://github.com/OfficeDev/office-js-docs-pr/issues/2557.
> [Outlook] (on-send) Clarify, include policy rename

- docs/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial.md
> [Excel] (Custom Functions) Fix typo in custom functions data share tutorial

- docs/overview/office-add-ins-community-call.md
Adding the link for the June 9 2021 community call.
> [All hosts](community call) Add June blog link

- docs/quickstarts/excel-custom-functions-quickstart.md
> [Excel] (Custom Functions) Move certificate note

- docs/concepts/browsers-used-by-office-web-add-ins.md
> [script lab] (Support) Explicitly state Script Lab no longer supports IE11

- docs/outlook/outlook-addin-design.md
Fixes [2778](https://github.com/OfficeDev/office-js-docs-pr/issues/2778)
> [Outlook] (design) remove recommendation for any design framework

- docs/reference/manifest/customtab.md
This is simple enough to go without a review.
> [PowerPoint] (ui) custom tab positioning support clarification

- docs/develop/support-ie-11.md
- docs/testing/ie-11-testing.md
Update alerts in these articles based on info in [Browsers used by Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins).
> [all hosts] (Script Lab) No longer works with IE

- docs/excel/make-custom-functions-compatible-with-xll-udf.md
> [Excel] (Custom Functions) Update XLL article

- docs/excel/custom-functions-overview.md
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview
#PingMSFTDocs
> Typo "Typescript"→"TypeScript"

- docs/excel/call-excel-apis-from-custom-function.md
Addressing part of #2839.
The rest of #2389 is converted an [internal work item](https://office.visualstudio.com/OC/_workitems/edit/5383233).
> [Excel] (Custom Functions) Update call Excel JS APIs code sample

- docs/develop/configure-your-add-in-to-use-a-shared-runtime.md
Fixes #2706 by adding note on element order.
> [All hosts](shared runtime)

- docs/excel/excel-add-ins-error-handling.md
My PR from yesterday #2898 was based on incorrect error strings provided by eng. Eng detected mistake. This PR updates docs to match actual error strings.
> [Excel] (Errors) Update error codes based on feedback

- docs/concepts/browsers-used-by-office-web-add-ins.md
Small fixing an issue where formatting could not be done due to extra table column instructions.
> Small fix for broken markdown table.

- docs/outlook/item-data.md
- docs/reference/objectmodel/requirement-set-1.8/outlook-requirement-set-1.8.md
- docs/testing/troubleshoot-development-errors.md
Internal link to MSFT style guide: https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=28837
> [admin] (style) Standardize 'read-only'

- docs/outlook/outlook-mobile-addins.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2890.
> [Outlook] (Gmail) Not currently supported on mobile

- docs/reference/manifest/desktopformfactor.md
- docs/reference/manifest/getstarted.md
Add a note about the behavior when GetStarted is omitted from the manifest.
Fixes #2940
> [All hosts](manifest) Add note about omitting GetStarted element

- docs/excel/excel-add-ins-error-handling.md
@AlexJerabek My plan is to include a shorter error message for OperationCellsExceedLimit in the product (simply "The attempted operation affects more than the limit of 33554000 cells." + a link to this page) and then display the short error message + expanded guidance on this page. Let me know if you have any questions!
> [Excel] (Error codes) New error code descriptions and solution

- docs/toc.yml
@ElizabethSamuel-MSFT, was this what you were thinking?
> [resources] (External resources) Making a resources TOC entry

- docs/concepts/browsers-used-by-office-web-add-ins.md
- docs/design/add-in-commands.md
- docs/develop/support-ie-11.md
- docs/includes/equivalent-add-in-support-note.md
- docs/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog.md
- docs/quickstarts/excel-custom-functions-quickstart.md
- docs/reference/requirement-sets/custom-functions-requirement-sets.md
- docs/reference/requirement-sets/excel-api-requirement-sets.md
- docs/reference/requirement-sets/word-api-requirement-sets.md
- docs/testing/ie-11-testing.md
- docs/tutorials/excel-tutorial-create-custom-functions.md
Some minor changes to reflect the new perpetual version of Office.
> [requirement sets] (Office 2021) Updating availability to reflect Office 2021

- docs/overview/office-add-ins-community-call.md
Adding community call agenda for October 13th.
> [All hosts](community call agenda)

- docs/reference/requirement-sets/excel-api-1-1-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-10-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-11-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-12-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-2-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-3-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-5-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-6-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-7-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-8-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-9-requirement-set.md
- docs/reference/requirement-sets/excel-api-online-requirement-set.md
- docs/reference/requirement-sets/excel-preview-apis.md
- docs/reference/requirement-sets/powerpoint-preview-apis.md
- docs/reference/requirement-sets/word-api-1-1-requirement-set.md
- docs/reference/requirement-sets/word-api-1-2-requirement-set.md
- docs/reference/requirement-sets/word-api-1-3-requirement-set.md
This also refreshes those tables with typo/grammar fixes that have recently been added.
Could I get a quick look from 
- @alison-mk in the Excel pages?
- @Rick-Kirkham in the PowerPoint pages?
- @ElizabethSamuel-MSFT in the Word pages (I did not update Word Preview, as per your request)?
One other note: I intentionally only updated the dates in the preview/online articles. Those were the ones with new content, instead of the basic fixes.
> [requirement sets] Alphabetize the requirement set tables

- docs/reference/requirement-sets/excel-api-1-5-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-8-requirement-set.md
Can we tweak the -reference script to avoid this issue?
> [all hosts] Fix column-header-missing build suggestions

- docs/overview/office-add-ins-community-call.md
This just clears the agenda with a placeholder for November.
> [All hosts](clear community call agenda)

- docs/overview/office-add-ins-community-call.md
Updates the links to point to the archived location for older blogs.
> [All hosts](community call) update links for archived blogs

- docs/outlook/get-set-or-add-recipients.md
Related to issue https://github.com/OfficeDev/office-js-docs-pr/issues/2962.
> [Outlook] (web) Note issue when create message from profile card

- docs/testing/debug-add-ins-using-devtools-edge-legacy.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/3024
> [All Hosts] (debugging) add link to debugging article

- docs/testing/troubleshoot-manifest.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/3025
Doesn't need a review.
> [All Hosts] (manifest) update npx command

- docs/reference/manifest/icon.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/3017
> [All Hosts] (manifest) info for Icon scale attribute

- docs/excel/pnp-open-in-excel.md
The archive of codeplex is no longer available so I removed the link to OOXML JavaScript SDK.
> [Excel](sample) Fix broken link

- docs/reference/requirement-sets/excel-api-requirement-sets.md
Based on https://github.com/OfficeDev/Office-Js-Requirement-Sets/pull/95
> [Excel] (ExcelApi 1.14) Update Excel builds requirement table

- docs/overview/office-add-ins-community-call.md
* clear agenda
* update call agenda for November
* shorten names
> [All hosts](Community call) November agenda (#3059)

- docs/excel/performance.md
Fixed the code in the example that the variable was invoked incorrectly.
> [Excel] (Performance) Update performance.md to fix error

- docs/reference/objectmodel/requirement-set-1.10/outlook-requirement-set-1.10.md
Related PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56978
> [Outlook] (office-runtime) Mailbox 1.10 supports Storage

- docs/develop/add-in-manifests.md
> [typo] (Broken link)  Fix add-in commands link

- docs/testing/test-debug-office-add-ins.md
- docs/testing/unit-testing.md
- docs/toc.yml
* [All Hosts] (testing) new unit testing article
* added Common API test and dynamic mock creation
* remove 'stub' terminology
* small fixes
* fix note indentation
* fix note indentation
* remove misleading note
* add Outlook example
* add prerequisites
* fix build errors
* fix build errors
* review changes
* typo
* removing misleading item from the library's virtues
* Update docs/testing/unit-testing.md
Co-authored-by: Alex Jerabek <38896772+AlexJerabek@users.noreply.github.com>
* Update docs/testing/unit-testing.md
Co-authored-by: Alex Jerabek <38896772+AlexJerabek@users.noreply.github.com>
* Update docs/testing/unit-testing.md
Co-authored-by: Alex Jerabek <38896772+AlexJerabek@users.noreply.github.com>
* Update docs/testing/unit-testing.md
Co-authored-by: Alex Jerabek …
> [All Hosts] (testing) How to use the Office mocking library (#3079)

- docs/design/using-office-ui-fabric-react.md
Fixes [3097](https://github.com/OfficeDev/office-js-docs-pr/issues/3097)
This doesn't need a review.
> [All Hosts] (ui) update Fluent React tutorial for new library structure

- docs/word/create-better-add-ins-for-word-with-office-open-xml.md
Updating the sample links to reflect https://github.com/OfficeDev/PnP-OfficeAddins/pull/219.
> [Word] (OOXML) Update sample link

- docs/testing/unit-testing.md
Addressing the results of the Broken Links report from OPS.
> [links] (Unit Testing) Fixing broken links

- docs/testing/unit-testing.md
@Rick-Kirkham Looks like the Storybook unit testing page is no longer available so I'm opting to remove it. If you would like me to solve this differently, let me know.
> [all hosts] Fix broken links

- docs/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial.md
Fixes #3104. Also fixes a typo and adds a whitespace line to the HTML block for for readability.
> [Excel] (Custom Functions) Fix filepath in shared runtime tutorial

- docs/design/keyboard-shortcuts.md
Clarify keyboard customization api capabilities
> Clarify keyboard customization api capabilities

- .openpublishing.publish.config.json
Related PR: https://github.com/OfficeDev/office-js-docs-reference/pull/1110
> [versioning] (Common APIs) Adding common-js-preview moniker

- docs/publish/publish.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/3120
> [Outlook] (deployment) Update link to Exchange guidance

- docs/excel/excel-add-ins-events.md
- docs/excel/excel-add-ins-worksheets.md
Adding docs for a feature released with ExcelApi 1.14.
> [Excel] (Worksheet) Add Worksheet.onProtectionChanged docs

- docs/excel/excel-add-ins-worksheets.md
This PR updates an existing article section to include information about an ExcelApi 1.14 API, `AutoFilter.clearColumnCriteria`. This PR also adds introductory comments to the nearby code samples in the article sections, for visual consistency.
> [Excel] (Worksheet) Update AutoFilter article section

- docs/overview/office-add-in-code-samples.md
This expands the list of samples to include the hello world samples for each Office host.
> [All hosts](samples) Add hello world samples

- docs/outlook/autolaunch.md
Fixes https://github.com/OfficeDev/office-js/issues/2308
> [Outlook] (preview) Specify Beta Channel for Smart Alerts

- docs/excel/excel-data-types-concepts.md
This PR documents the JSON schema for data types currently in preview. [Work item](https://office.visualstudio.com/OC/_workitems/edit/5624721).
> [Excel] (Data types) Update JSON schema information

- docs/testing/debug-add-ins-in-office-online.md
- docs/testing/debug-add-ins-overview.md
- docs/testing/test-debug-office-add-ins.md
- docs/toc.yml
This new article is part of a long-term project to improve our debugging documentation. We anticipate that near the end of that project, this article will be updated to handle more special cases and to include a decision tree diagram.
> [All Hosts] (debugging) new debugging overview article

- docs/design/using-office-ui-fabric-react.md
- docs/develop/develop-overview.md
- docs/includes/alert-use-https.md
- docs/includes/quickstart-yo-start-server-excel.md
- docs/overview/explore-with-script-lab.md
- docs/quickstarts/excel-custom-functions-quickstart.md
- docs/quickstarts/onenote-quickstart.md
- docs/quickstarts/outlook-quickstart.md
- docs/quickstarts/powerpoint-quickstart.md
- docs/quickstarts/project-quickstart.md
- docs/quickstarts/sso-quickstart-customize.md
- docs/quickstarts/sso-quickstart.md
- docs/quickstarts/word-quickstart.md
- docs/tutorials/excel-tutorial.md
- docs/tutorials/outlook-tutorial.md
- docs/tutorials/word-tutorial.md
This just converts a common note into an include since the same text appears in so many articles.
> [All hosts](tutorials) Convert common text to include

- docs/concepts/privacy-and-security.md
Addresses issue mentioned in #3192.
> [All hosts] (Security) Clarify web add-in terminology

- docs/testing/clear-cache.md
Fixes #3153. This clarification is based on a discussion with @jargil, who can further verify the accuracy of this option.
> [Developer Experience] (Office Cache) Clarify cache clearing option behavior

- docs/overview/office-add-ins-community-call.md
* add january call link
Co-authored-by: Elizabeth Samuel <elizs@microsoft.com>
* add February agenda
* Update docs/overview/office-add-ins-community-call.md
Co-authored-by: Alex Jerabek <38896772+AlexJerabek@users.noreply.github.com>
* Update docs/overview/office-add-ins-community-call.md
Co-authored-by: Alex Jerabek <38896772+AlexJerabek@users.noreply.github.com>
Co-authored-by: Elizabeth Samuel <elizs@microsoft.com>
Co-authored-by: Alex Jerabek <38896772+AlexJerabek@users.noreply.github.com>
> [admin] Publish 

- docs/reference/javascript-api-for-office-error-codes.md
> [Outlook] (API error codes) Add error code 9020 and troubleshooting link

- docs/resources/resources-glossary.md
- docs/toc.yml
Reviewers: I plan to request a review from our editor **after** incorporating feedback from a first round of reviews by writers.
The internal [work item](https://office.visualstudio.com/OC/_workitems/edit/5326821) for this task includes background information on the concept and goals.
> [all hosts] Add Glossary of terms article

- docs/excel/excel-data-types-concepts.md
Incorporating feedback from eng.
> [Excel] (Data types) Adding type annotations

- docs/toc.yml
- docs/word/create-better-add-ins-for-word-with-office-open-xml.md
Related to issue https://github.com/OfficeDev/Office-Add-in-samples/issues/223
> [Word] (ooxml) Note RichApi as first option

- docs/tutorials/powerpoint-tutorial.md
Fixes [3258](https://github.com/OfficeDev/office-js-docs-pr/issues/3258)
> [PowerPoint] (tutorial) add missing step

- docs/reference/manifest/getstarted.md
Fixes [3266](https://github.com/OfficeDev/office-js-docs-pr/issues/3266)
This just copies previously reviewed sentences to another place, so I don't think it needs a review.
> Manifest getstarted fix

- docs/reference/overview/excel-add-ins-reference-overview.md
Adding link per [internal request](https://office.visualstudio.com/OC/_workitems/edit/5826576).
> [Excel] (Overview) Add data types link

- docs/develop/develop-add-ins-vscode.md
- docs/includes/vs-code-open-project-via-command-line.md
- docs/includes/webview-stop-on-load-cancel-dialog.md
- docs/testing/debug-desktop-using-edge-chromium.md
- docs/tutorials/outlook-tutorial.md
> [Outlook] (tutorial) Fix ModuleNotFoundError

- docs/excel/index.yml
Incorporating [internal feedback](https://office.visualstudio.com/OC/_workitems/edit/5826585).
> [Excel] (Landing) Add data types link

- docs/quickstarts/excel-quickstart-jquery.md
- docs/tutorials/excel-tutorial.md
This PR is another in the series to modernize the JavaScript in our samples. This updates the Excel quick start and tutorial to use the `async`/`await` pattern.
> [Excel] (quick start) Update JS in Excel quick start and tutorial

- docs/includes/outlook-loopback-exemption.md
Related to issue https://github.com/OfficeDev/office-js/issues/2312
> [Outlook] (event-based activation) Note re port other than default

- docs/overview/office-add-ins-community-call.md
Update agenda for March community call.
> [All hosts] (community call) Update agenda for March community call

- docs/design/disable-add-in-commands.md
- docs/reference/manifest/enabled.md
- docs/reference/requirement-sets/add-in-commands-requirement-sets.md
Fixes [3302](https://github.com/OfficeDev/office-js-docs-pr/issues/3302)
These changes are already approved by SME and are too trivial to need a review.
> [PowerPoint Word] (ui) enable/disable commands supported in PPT Word

- docs/design/contextual-tabs.md
- docs/reference/requirement-sets/ribbon-api-requirement-sets.md
This doesn't need a review. And the SMEs have approved it.
> [Excel] (ui) contextual tabs now supported on Mac

- docs/includes/mac-cache-folders.md
- docs/testing/clear-cache.md
- docs/testing/debug-office-add-ins-on-ipad-and-mac.md
Answers question asked in #3296.
> [All hosts] Update MacOS cache clear instructions

- docs/word/word-add-ins-core-concepts.md
Fixes #3317. I also did a quick pass on the text for clarity.
> [Word] (overview) Fix typos and clarify some text in the Word core concepts

- docs/outlook/use-sso-in-event-based-activation.md
Removes details about the custom response header as there is a product issue that needs to be addressed.
> [Outlook](SSO) Remove custom response header details

- docs/develop/configure-your-add-in-to-use-a-shared-runtime.md
Fixes [3327](https://github.com/OfficeDev/office-js-docs-pr/issues/3327)
> [Excel PowerPoint] (runtimes) clarify yo office syntax

- docs/develop/configure-your-add-in-to-use-a-shared-runtime.md
Updates the yo office step to include Word as an option (as well as indicate there are other options to that are supported.)
> [All hosts](shared runtime) add Word support

- docs/overview/office-add-ins-community-call.md
Adding agenda for April 13, 2022 community call.
> [All hosts](Community call) Add agenda for April 2022

- .openpublishing.redirection.json
Fixes https://github.com/OfficeDev/office-js-docs-reference/issues/1210.
> [admin] (links) Add individual Outlook requirement set redirects

- docs/tutorials/excel-tutorial.md
> [Excel] (Tutorial) Update npm stop instructions

- docs/concepts/requirements-for-running-office-add-ins.md
- docs/outlook/outlook-mobile-addins.md
> [Outlook] (mobile) Clarify add-in support for on-prem accounts

- docs/excel/excel-data-types-concepts.md
This PR incorporates feedback from the feature crew.
> [Excel] (Data types) Add list of CellValue types

- docs/outlook/debug-autolaunch.md
> [Outlook] (debugging) Remove preview tags and notes

- docs/publish/maintain-breaking-changes.md
- docs/toc.yml
There's isn't a clear place in the documentation where we describe our backwards compatibility policies. This article aims to address that gap.
Staging site link: https://review.docs.microsoft.com/en-us/office/dev/add-ins/publish/maintain-breaking-changes?branch=AlexJ-Maintainability
> [all hosts] (Publishing) Consolidating documentation about backwards compatibility and support

- docs/excel/custom-functions-web-reqs.md
This PR resolves issue #3395 and aligns the article with current style guidelines and practices.
> [Excel] (Custom functions) Add note to fetch example

- docs/includes/install-office-that-uses-legacy-edge-or-ie.md
Fixes [3412](https://github.com/OfficeDev/office-js-docs-pr/issues/3412)
> [All Hosts] (ie) add step to install instructions

- docs/design/add-in-commands.md
> [All Hosts] (ui) some ribbon enhancements are released

- docs/tutorials/powerpoint-tutorial.md
Fixes [3397](https://github.com/OfficeDev/office-js-docs-pr/issues/3397)
> [PowerPoint] (tutorial) warn about bug in VS2019

- docs/publish/maintain-breaking-changes.md
This PR expands our maintainability story by listing our deprecation timeline. This is consistent with the promises made by the Graph team: https://docs.microsoft.com/en-us/graph/versioning-and-support#support-policy-and-deprecation-information.
> [all hosts] (Publishing) Deprecation information

- .openpublishing.publish.config.json
- docs/excel/excel-add-ins-ranges-precedents-dependents.md
- docs/excel/excel-add-ins-tables.md
This PR updates a Range article section describing the getDependents method and updates a Table article section to include a description of the new alwaysInsert parameter. 
This PR also removes a number of antiquated ExcelApi 1.2 if statements from the Table article.
> [Excel] (ExcelApi 1.15) Release ExcelApi 1.15 to GA

- docs/develop/office-versions-and-requirement-sets.md
I don't think this needs a review.
> [All Hosts] (req sets) update list of common req sets

- docs/overview/set-up-your-dev-environment.md
Fixes [3231](https://github.com/OfficeDev/office-js-docs-pr/issues/3231)
> [All Hosts] (setup) rewrite and expand article for environment setup

- docs/excel/excel-data-types-concepts.md
[Internal work item](https://office.visualstudio.com/OC/_workitems/edit/6018828).
> [Excel] (Data types) Add linked data types to concepts article

- docs/excel/custom-functions-debugging.md
Fixes [3229](https://github.com/OfficeDev/office-js-docs-pr/issues/3229)
> [Excel] (custom functions) debugging with manifest-only option

- docs/quickstarts/outlook-quickstart-json-manifest.md
This pure code change has product team approval and doesn't need additional review.
> [Outlook] (quickstart) update to use associate method

- docs/outlook/online-meeting.md
Update the GitHub issue location for registering online meeting add-ins to office-js from office-js-pr.
> [Outlook] (link) Change GitHub issue location to office-js repo

- docs/develop/create-sso-office-add-ins-aspnet.md
- docs/develop/create-sso-office-add-ins-nodejs.md
Adding a small client secret description to address #3342
> [All hosts](security) Add client secret description

- docs/quickstarts/excel-custom-functions-quickstart.md
- docs/quickstarts/excel-quickstart-angular.md
- docs/quickstarts/excel-quickstart-jquery.md
- docs/quickstarts/excel-quickstart-react.md
- docs/quickstarts/excel-quickstart-vue.md
- docs/quickstarts/onenote-quickstart.md
- docs/quickstarts/outlook-quickstart-json-manifest.md
- docs/quickstarts/outlook-quickstart.md
- docs/quickstarts/powerpoint-quickstart.md
- docs/quickstarts/project-quickstart.md
- docs/quickstarts/sso-quickstart-customize.md
- docs/quickstarts/sso-quickstart.md
- docs/quickstarts/word-quickstart.md
This is response to a customer request on Stack Overflow. Doesn't need a review.
> [All Hosts] (quickstarts) add 'see also' to publishing article

- docs/testing/testing-and-troubleshooting.md
This was a request from a verbatim comment.
> [All Hosts] (troubleshooting) link to manifest validation article

- docs/develop/authorize-to-microsoft-graph.md
Remove text that implies mobile is supported for SSO.
> [All hosts](security)

- docs/overview/office-add-in-code-samples.md
This adds the Excel and Word Blazor samples to the list of samples.
> [All hosts](samples) Add Blazor samples

- docs/tutorials/outlook-tutorial.md
> [Outlook] (tutorial) Address #3361 GH issue, fix CSS format, and fix contractions

- .openpublishing.publish.config.json
- docs/powerpoint/shapes.md
> [PowerPoint] (shapes) Shapes APIs are GA as req set 1.4

- docs/publish/publish.md
@lindalu-MSFT We should keep the AppSource reference too (separate from "See also" link to the AppSource page)
> [all hosts] Minor cleanup

- docs/outlook/outlook-on-send-addins.md
In response to internal bug 6100326.
> [Outlook] (ItemSend) Add support for dynamically created event handlers

- .openpublishing.publish.config.json
Related to https://github.com/OfficeDev/office-js-docs-reference/pull/1301
> [Word] (Desktop only) Add moniker

- docs/project/create-your-first-task-pane-add-in-for-project-by-using-a-text-editor.md
- docs/project/project-add-ins.md
Fix links reported in [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).
Use of var keyword in JS code is being addressed in a separate PR.
> [Project] (links) Fix links and remove trailing spaces

- docs/word/create-better-add-ins-for-word-with-office-open-xml.md
- docs/word/dictionary-task-pane-add-ins.md
- Updates var in Word JavaScript code.
- Minor formatting fixes.
> [Word] (JS) Replace var with let/const in JS code

- docs/excel/call-excel-apis-from-custom-function.md
- docs/excel/custom-functions-authentication.md
- docs/excel/custom-functions-errors.md
- docs/excel/custom-functions-json-autogeneration.md
- docs/excel/custom-functions-parameter-options.md
- Updates var in Excel JavaScript code, where applicable.
- Minor formatting fixes.
> [Excel] (JS) Replace var with let/const in JS code

- docs/outlook/apis.md
Reverts OfficeDev/office-js-docs-pr#3562
> Revert "[Outlook] (manifest) updating API overview to account for JSON manifest"

- docs/outlook/apis.md
This restores something that was already approved, so doesn't need another review.
> [Outlook] (manifest) Re-reverting JSON manifest info in APIs overview

- docs/develop/show-hide-add-in.md
> [ui] (Task Panes) Update condition statements in show/hide code samples

- docs/develop/yeoman-generator-overview.md
> [All Hosts] (tools) add link to yo office repo

- docs/excel/excel-add-ins-comments.md
- docs/excel/excel-data-types-concepts.md
Per [style guide](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=28837), once it's not the code `readonly`, should be read-only.
Tagging @alison-mk as FYI...
> [all hosts] Should be read-only

- docs/excel/call-excel-apis-from-custom-function.md
Expanding description in response to customer issue #3506.
> [Excel] (Custom Functions) Further explain custom function limitations

- docs/testing/runtimes.md
Fixes [3605](https://github.com/OfficeDev/office-js-docs-pr/issues/3605)
> [All Hosts] (runtimes) correct support for LocalStorage

- docs/overview/set-up-your-dev-environment.md
Fixes [3604](https://github.com/OfficeDev/office-js-docs-pr/issues/3604)
This doesn't need a review.
> [All Hosts] (setup) use hemisphere-sensitive-dating

- docs/excel/excel-data-types-concepts.md
Adding a missing object with a unique version of the property name.
> [Excel[ (Data types) Add valueAsJson note

- docs/develop/create-sso-office-add-ins-nodejs.md
In a pending PR (https://github.com/OfficeDev/Office-Add-in-samples/pull/370) I did some refactoring and updates to the sample for this walkthrough. This updates the steps to match all the code changes.
> [All hosts][SSO] Update walkthrough for latest changes to sample

- docs/outlook/use-rest-api.md
Source: Update on REST exemption announced during the August community call.
> [Outlook] (REST) Update REST exemption guidance

- README.md
**Global effort to fix build validation errors**
The Microsoft Skilling team is fixing build validation errors and specific brand inconsistencies in Microsoft technical documentation for the rest of FY23 Q1. This will help address various accessibility, security, and usability issues. This PR was generated using DocuTune. It includes only targeted fixes and minor formatting adjustments.
DocuTune PRs improve quality of technical content by finding and automatically correcting a broad set of issues only where the correction is suitable. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!
CorrelationId: 0df9c2d6-63f8-4d1e-8b57-b33611a06514
InitiativeId: docutune-build-validation-issues-2022-05
PointOfContact: Alex Buck
> [BULK] DocuTune - Fix build validation issues: docs-link-absolute

- docs/overview/office-add-in-code-samples.md
Same addition as https://github.com/OfficeDev/Office-Add-in-samples/pull/395
> [Excel] (Data types) Add new Data types explorer link

- README.md
- docs/index.yml
- docs/outlook/delegate-access.md
- docs/outlook/use-rest-api.md
- docs/overview/learning-path-beginner.md
- docs/overview/learning-path-transition.md
- docs/powerpoint/insert-slides-into-presentation.md
**Global effort for the Microsoft Learn platform rebrand**
The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.
Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.
This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.
CorrelationId: d8c4c3ac-d49a-4c95-9ddc-9822ca297907
InitiativeId: docutune-rebranding-2022-09
PointOfContact: Alex Buck
> [BULK] DocuTune - Rebranding

- docs/develop/application-specific-api-model.md
Fixes [3650](https://github.com/OfficeDev/office-js-docs-pr/issues/3650)
I don't think this needs a review.
> [PowerPoint] (apis) update app-specific overview to include PowerPoint

- docs/toc.yml
[Internal work item](https://office.visualstudio.com/OC/_workitems/edit/5922308)
> [Excel] (Custom Functions) Re-add batching article to TOC

- docs/excel/custom-functions-batching.md
Reviewed code and updated to support both JS and TS.
> [Excel](custom functions) Refresh batching article

- docs/excel/custom-functions-debugging.md
- docs/includes/mac-command-line.md
- docs/includes/start-web-sideload-instructions.md
Fixes [3667](https://github.com/OfficeDev/office-js-docs-pr/issues/3667)
> [All Hosts] (sideload) note about Mac command line syntax

- docs/outlook/autolaunch-store-options.md
- docs/outlook/autolaunch.md
- docs/outlook/debug-autolaunch.md
- docs/outlook/outlook-on-send-addins.md
- docs/outlook/smart-alerts-onmessagesend-walkthrough.md
THIS MUST NOT BE MERGED UNTIL A VERSION OF OFFICE THAT SUPPORTS THE JSON MANIFEST PROPERTY "autoRunEvent" IS AVAILABLE IN SOME PUBLIC CHANNEL (e.g., Insiders).
> [Outlook] (manifest) event-based activation with the JSON manifest

- docs/outlook/autolaunch.md
- docs/outlook/smart-alerts-onmessagesend-walkthrough.md
Related reference PR: https://github.com/OfficeDev/office-js-docs-reference/pull/1435
> [Outlook] (1.12) Mailbox 1.12 support on new Mac UI

- docs/includes/register-sso-add-in-aad-v2-include.md
Fix link that appears in the broken link report.
> [All hosts] (SSO) Fix link

- docs/outlook/get-or-set-the-location-of-an-appointment.md
Conceptual change related to [DT PR #63147](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63147/files).
> [Outlook] (enhancedLocation) Add note about personal contact groups

- docs/develop/loading-the-dom-and-runtime-environment.md
- docs/outlook/autolaunch.md
> [Outlook] (event-based activation ) Clarify use of initialization functions in event-based add-ins on Windows

- docs/design/content-add-ins.md
Fixes #3725.
Based on the feedback in #3725, highlighting these necessary manifest changes would be helpful to know up front. I'm open to feedback on if there's a better way to display this information, or if it's incomplete.
> [all hosts] (Content Add-ins) Add manifest basics for content add-ins

- docs/testing/debug-add-ins-overview.md
I don't think this needs a review.
> [All Hosts] (debugging) remove erroneous instruction from overview

- docs/develop/troubleshoot-sso-in-office-add-ins.md
- docs/testing/troubleshoot-development-errors.md
> [All hosts] (SSO) Update links

- docs/excel/excel-data-types-entity-card.md
- docs/excel/excel-data-types-overview.md
This PR is in response to internal feedback. The goal is to guide readers through the published documentation options (articles, Script Lab, sample in GitHub). 
This learning path is also described at the end of each data types article — an update previously added in PR #3703.
> [Excel] (Data types) Clarify data types learning path

- docs/outlook/web-services.md
Adds note that EWS operations aren't supported in add-ins running in Outlook on iOS and Android.
Related PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63494
> [Outlook] (EWS) Clarify EWS support in mobile clients

- docs/excel/custom-functions-dynamic-arrays.md
- docs/excel/custom-functions-web-reqs.md
[Internal work item](https://office.visualstudio.com/OC/_workitems/edit/6057195).
Addressing customer issue #3411.
> [Excel] (Custom functions) Add streaming spill array snippet

- docs/develop/addressing-same-origin-policy-limitations.md
This XMLHttpRequest2 was merged into XMLHttpRequest. This updates the section to link to a good resource for learning more about CORS.
Fixes #3766
> [All hosts](Auth) Update CORS resource link

- docs/testing/debug-desktop-using-edge-chromium.md
Reverting a port number change for one document as per the SME.
> [All Hosts] (tools) revert port number change

- docs/overview/explore-with-script-lab.md
The goal of these changes is to improve the Bounce Rate and Scroll Rate of the article, as well as increase the clicks to the download SL links.
> [all hosts] (Script Lab) Refactor Explore SL article to improve metrics

- docs/quickstarts/excel-quickstart-jquery.md
- docs/quickstarts/outlook-quickstart.md
- docs/quickstarts/powerpoint-quickstart.md
- docs/quickstarts/word-quickstart.md
Adds a link to the quick starts to hello world samples. This will help with discovery if someone wants to learn more without using yo office or VS.
> [All hosts](getting started) Add hello world sample links to quick starts

- docs/outlook/use-rest-api.md
Adds a link to the [most recent REST blog post](https://devblogs.microsoft.com/microsoft365dev/outlook-rest-api-v2-0-beta-deprecation-update/).
> [Outlook] (REST) Add link to most recent blog post

- docs/develop/troubleshoot-sso-in-office-add-ins.md
This PR fixes the account terminology in the 13007 error troubleshooting.
> [All hosts](SSO) Update 13007 error

- docs/develop/make-office-add-in-compatible-with-existing-com-add-in.md
- docs/includes/new-outlook-vsto-com-support.md
- docs/outlook/one-outlook.md
- docs/outlook/outlook-add-ins-overview.md
- docs/overview/learning-path-transition.md
- docs/overview/office-add-ins.md
- docs/toc.yml
- docs/tutorials/migrate-vsto-to-office-add-in-shared-code-library-tutorial.md
Creates an article that provides information on the new Outlook on Windows desktop client and which add-ins it supports.
> [Outlook] (preview) Add-in support in the new Outlook on Windows 

- docs/outlook/mobile-log-appointments.md
Related PR: https://github.com/OfficeDev/office-js-docs-reference/pull/1513
> [Outlook] (CRM) Add Outlook on iOS support

- docs/outlook/append-on-send.md
- docs/outlook/autolaunch-store-options.md
- docs/outlook/autolaunch.md
- docs/outlook/debug-autolaunch.md
- docs/outlook/debug-ui-less.md
- docs/outlook/item-multi-select.md
- docs/outlook/mobile-log-appointments.md
- docs/outlook/one-outlook.md
- docs/outlook/online-meeting.md
- docs/outlook/onmessagefromchanged-onappointmentfromchanged-events.md
- docs/outlook/smart-alerts-onmessagesend-walkthrough.md
ms.topic will default to "conceptual"
> [all hosts] Remove deprecated 'article' topic

- docs/testing/sideload-an-office-add-in-on-mac.md
Fixes [3851](https://github.com/OfficeDev/office-js-docs-pr/issues/3851)
> [All Hosts] (sideloading) clarify sideloading on Mac

- docs/develop/localization.md
Mainly what the title indicates. 
Also, corrects a section title and heading levels.
> [All Hosts] (localization) localization of JSON manifest

- docs/resources/resources-links-help.md
Rather than do it via email, added some edits here - what do you think of these?
> some suggestions

- docs/develop/create-sso-office-add-ins-nodejs.md
- docs/includes/register-sso-add-in-aad-v2-include.md
This is an update to the SSO walkthrough to match latest changes in the sample code. The sample changes are in https://github.com/OfficeDev/Office-Add-in-samples/pull/486.
> Update SSO walkthrough to match updates in sample

- docs/excel/custom-functions-overview.md
- docs/includes/excel-custom-functions-definition.md
- docs/resources/resources-glossary.md
> [Excel] (Custom functions) Update CF definition based on customer feedback

- docs/excel/custom-functions-json-autogeneration.md
Follow up change to customer-submitted PR #3880
> [Excel] (Custom functions) Update helpurl code snippet

- docs/resources/resources-links-help.md
Adds aka links and also community call link.
> [All hosts](community) add aka links

- docs/includes/register-sso-add-in-aad-v2-include.md
- Updates some Azure Portal navigation steps.
- Applies minor formatting fixes.
> [All hosts] (SSO) Update steps

- docs/excel/custom-functions-batching.md
- docs/excel/custom-functions-data-types-concepts.md
- docs/excel/custom-functions-debugging.md
- docs/excel/custom-functions-troubleshooting.md
- docs/excel/excel-add-ins-core-concepts.md
- docs/excel/excel-add-ins-ranges-large.md
- docs/excel/excel-add-ins-troubleshooting.md
- docs/excel/excel-data-types-concepts.md
- docs/excel/excel-data-types-entity-card.md
- docs/excel/excel-data-types-overview.md
- docs/excel/performance.md
- docs/excel/pnp-open-in-excel.md
Internal tracking: [Excel](https://office.visualstudio.com/OC/_workitems/edit/7612542), [Custom functions](https://office.visualstudio.com/OC/_workitems/edit/7612543), [PowerPoint](https://office.visualstudio.com/OC/_workitems/edit/7612545)
Note: PowerPoint metadata doesn't need any updates at this time.
> [Excel][PowerPoint] Review ms.topic settings, update based on guidance

- docs/powerpoint/shapes.md
> [PowerPoint] (Shapes) Fix typo in addLine code snippet

- docs/design/contextual-tabs.md
- docs/design/keyboard-shortcuts.md
- docs/develop/extended-overrides.md
- docs/develop/localization.md
- docs/excel/custom-functions-json.md
Reverts change in #3910 as links have now been fixed.
> [All hosts] Revert temporary fix for links

- docs/includes/file-get-the-whole-document-from-an-add-in-for-powerpoint-or-word.md
- docs/powerpoint/get-the-whole-document-from-an-add-in-for-powerpoint.md
- docs/word/get-the-whole-document-from-an-add-in-for-word.md
@alison-mk Take a look re: PowerPoint aspect. Should update the ms.date for the PowerPoint page as well?
Tried in Word and PowerPoint
> [Word] (Get whole doc) Refresh

- docs/outlook/extract-entity-strings-from-an-item.md
> [Outlook] (entities) Correct variables

- docs/quickstarts/outlook-quickstart-json-manifest.md
> [Outlook] (tooling) remove obsolete Yo Office option

- docs/develop/json-manifest-overview.md
> [Outlook] (manifest) remove obsolete note

- docs/develop/automatically-open-a-task-pane-with-a-document.md
- docs/includes/excel-shared-runtime-preview-note.md
- docs/includes/quickstart-vs-prerequisites.md
- docs/powerpoint/powerpoint-add-ins.md
- docs/quickstarts/excel-custom-functions-quickstart.md
- docs/quickstarts/excel-quickstart-jquery.md
- docs/quickstarts/excel-quickstart-react.md
- docs/quickstarts/outlook-quickstart.md
- docs/testing/debug-office-add-ins-on-ipad-and-mac.md
- docs/tutorials/excel-tutorial.md
- docs/tutorials/word-tutorial.md
Fixed some old portal links that aren't updated to the correct location.
> [All hosts] Update old links

- docs/tutorials/powerpoint-tutorial.md
Addressing bug raised in #3921.
> [PowerPoint] (Tutorial) Add step to fix jQuery discrepancy

- docs/testing/debug-office-add-ins-on-ipad-and-mac.md
For background, see https://github.com/OfficeDev/office-js/issues/3005#issuecomment-1336806523
> [All Hosts] (debugging) Mac debugging only if installed from office.com

- docs/outlook/append-on-send.md
Related PR: https://github.com/OfficeDev/office-js-docs-reference/pull/1563
> [Outlook] (prepend-on-send) Add Outlook on Mac support

- .openpublishing.publish.config.json
Aligns with https://github.com/OfficeDev/office-js-docs-reference/pull/1566
> [Excel] (ExcelApi 1.17) Update config to include ExcelApi 1.17

- docs/outlook/contextless.md
- docs/outlook/item-multi-select.md
- docs/outlook/pinnable-taskpane.md
- docs/toc.yml
Related PR: https://github.com/OfficeDev/office-js-docs-reference/pull/1573
> [Outlook] (contextless) Create article

- docs/outlook/delay-delivery.md
Reorder content in the "Feature behavior and limitations" section based on feedback.
> [Outlook] (delay delivery) Minor content organization

- docs/develop/automatically-open-a-task-pane-with-a-document.md
- docs/develop/install-latest-office-version.md
- docs/testing/runtime-logging.md
This fixes a couple old links to the archived commands sample repo. Updates them to the new location (or places text inline as needed).
> [All hosts](commands) Update links to archived repos

- docs/concepts/browsers-used-by-office-web-add-ins.md
> [All Hosts] (mobile) conditional access not supported on Android

- docs/quickstarts/outlook-quickstart-json-manifest.md
> [Outlook] (tools) link from Yo creation to TTK creation

- docs/publish/government-cloud-guidance.md
Doesn't need review.
Fixes [4023](https://github.com/OfficeDev/office-js-docs-pr/issues/4023)
> [All Hosts] (publish) Office.js CDNs for government

- docs/concepts/browsers-used-by-office-web-add-ins.md
- docs/develop/develop-overview.md
One article was just updated yesterday, so it already had the correct metadata date.
> [All Hosts] (various) combining small fixes into one PR

- docs/outlook/debug-autolaunch.md
> [Outlook] (format) Remove invisible characters

- docs/includes/outlook-bundle-js.md
- docs/outlook/autolaunch.md
- docs/outlook/debug-autolaunch.md
> [Outlook] (event-based activation) Correct bundle.js information

- docs/includes/sso-yeoman-project-structure.md
Fixes [4082](https://github.com/OfficeDev/office-js-docs-pr/issues/4082)
> [All Hosts] (auth) fix out-of-date SSO file descriptions

- docs/outlook/internet-headers.md
Removes "x-" from the internet header code snippets as this isn't a requirement and isn't enforced by the API.
> [Outlook] (internet headers) Correct snippets

- docs/overview/office-add-ins-community-call.md
Agenda for July 12th Office Add-ins community call.
> Updating agenda for this month's community call.

- docs/includes/file-get-the-whole-document-from-an-add-in-for-powerpoint-or-word.md
- docs/word/get-the-whole-document-from-an-add-in-for-word.md
> [Word] (get whole doc) Include full .js

- docs/overview/office-add-ins-community-call.md
> [All hosts] (community call) Reset agenda

- docs/includes/outlook-irm-add-in-activation.md
Adds Outlook client version number for consistency.
Reference: [Update history for Microsoft 365 Apps (listed by date)](https://learn.microsoft.com/officeupdates/update-history-microsoft365-apps-by-date)
> [Outlook] (version) Add client version number

- docs/overview/office-add-in-code-samples.md
Add new Outlook SSO events sample to the list.
> [Outlook](SSO) Add new sample to list

- docs/develop/support-ie-11.md
Fixes [4112](https://github.com/OfficeDev/office-js-docs-pr/issues/4112)
> [All Hosts] (webviews) update article for IE11 and graceful failure

- docs/develop/add-in-manifests.md
- docs/develop/convert-xml-to-json-manifest.md
- docs/develop/create-addin-commands-unified-manifest.md
- docs/develop/json-manifest-overview.md
- docs/develop/localization.md
- docs/develop/teams-toolkit-overview.md
- docs/develop/yeoman-generator-overview.md
- docs/quickstarts/outlook-quickstart-json-manifest.md
Fixes [4117](https://github.com/OfficeDev/office-js-docs-pr/issues/4117)
> [Outlook] (manifest) unified manifest only supported on Windows

- docs/develop/addressing-same-origin-policy-limitations.md
> [All Hosts] (security) fix link to blog post

- docs/outlook/get-attachments-of-an-outlook-item.md
Updates snippet in article to use the Office.AsyncResultStatus enum and remove an unused parameter.
> [Outlook] (code) Update snippet

- docs/quickstarts/outlook-quickstart-json-manifest.md
Fixes [4128](https://github.com/OfficeDev/office-js-docs-pr/issues/4128)
> [Outlook] (manifest) update the unified manifest quickstart

- docs/develop/office-versions-and-requirement-sets.md
- docs/publish/publish.md
Fixes https://github.com/OfficeDev/office-js-docs-reference/issues/1655
> [Deployment] Note that selected option can affect add-in availability

- docs/outlook/get-or-set-the-subject.md
- docs/outlook/get-or-set-the-time-of-an-appointment.md
- docs/outlook/get-set-or-add-recipients.md
- docs/outlook/insert-data-in-the-body.md
- Updates samples to remove the requirement to configure the **\<Rule>** element in the manifest. 
- Reorganizes information and applies minor formatting fixes.
> [Outlook] (compose) Update samples

- docs/testing/sideload-office-add-ins-for-testing.md
Fixes [4139](https://github.com/OfficeDev/office-js-docs-pr/issues/4139)
> [All Hosts] (sideloading) must be admin to sideload to web

- docs/outlook/add-mobile-support.md
- Fixes #4146.
- Updates linked articles.
> [Outlook] (mobile) Fix guidance on child elements required for mobile extension points

- docs/outlook/autolaunch.md
- docs/outlook/mobile-event-based.md
- docs/outlook/outlook-on-send-addins.md
- docs/outlook/smart-alerts-onmessagesend-walkthrough.md
- docs/outlook/spam-reporting.md
Related PRs: 
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66485
- https://github.com/OfficeDev/office-js-docs-reference/pull/1670
- https://github.com/OfficeDev/Office-Add-in-samples/pull/584
> [Outlook] (event) Update event.completed links

- docs/develop/parent-to-dialog.md
Adds Firefox to the list of browsers in which the Local Storage isn't shared by the dialog and task pane.
> [All hosts] (dialog) Add Firefox to list of browsers affected by bug

- docs/develop/usability-testing.md
The articles in UserTesting.com changed their links. This PR fixes that and does a quick refresh on some of the text, with regards to style.
> [all hosts] (Testing) Refresh user testing article and fix links

- docs/resources/resources-glossary.md
Fixes [4162](https://github.com/OfficeDev/office-js-docs-pr/issues/4162)
> [All Hosts] (glossary) clarify definition of shared runtime

- docs/tutorials/powerpoint-tutorial.md
Also link to completed version of tutorial found on Office-Add-in-samples repo
> [PowerPoint] (tutorial) Add web.config update to avoid csc.exe error

- docs/tutorials/word-tutorial.md
Completed version: https://github.com/OfficeDev/Office-Add-in-samples/pull/603
> [Word] (tutorial) Link to completed version

- docs/docfx.json
Seems like sending users to M365 product is too broad.
> [all hosts] Refine product feedback link

- docs/concepts/privacy-and-security.md
- docs/includes/office-store-validate.md
- docs/outlook/autolaunch-store-options.md
- docs/publish/deploy-office-add-in-sso-to-azure.md
- docs/publish/government-cloud-guidance.md
- docs/resources/resources-links-help.md
- docs/testing/troubleshoot-manifest.md
Also fixes a couple places where "Office Store" should be "AppSource".
> [All Hosts] (deploy) update name of 'in-app' add-in store

- docs/outlook/contextless.md
> [Outlook] (contextless) Add guidance for users with existing projects

- .github/policies/resourceManagement.yml
- Issue_Template.md
- README.md
- docs/docfx.json
- docs/excel/index.yml
- docs/includes/landing-page-resources-no-script-lab.md
- docs/includes/landing-page-resources.md
- docs/index.yml
- docs/outlook/index.yml
- docs/powerpoint/index.yml
- docs/project/index.yml
- docs/publish/deploy-office-add-in-sso-to-azure.md
- docs/testing/troubleshoot-development-errors.md
- docs/visio/index.yml
- docs/word/index.yml
Also, make links to ask questions and request features more consistent.
> [all hosts] Fix build suggestions

- docs/outlook/contextless.md
> [Outlook] (contextless) Clarify feature support in Outlook on the web

- docs/develop/application-specific-api-model.md
I couldn't find this information in the docs. Since this came up in an internal thread, I'm adding a small section about loading from a collection. If I'm mistaken and this information exists elsewhere (or I've oversimplified something), please let me know.
> [WXP] (Application-specific model) Add a section on loading properties from a collection

- docs/outlook/smart-alerts-onmessagesend-walkthrough.md
Based on feedback, changes implemented send mode option in walkthrough to **soft block**.
> [Outlook] (Smart Alerts) Change implemented send mode option in walkthrough

- docs/excel/make-custom-functions-compatible-with-xll-udf.md
- docs/toc.yml
Editing pass of article to remove future tense and clarify some confusing sentences. Also updating TOC title to make it more clear what the article content contains.
> [Excel] (Custom functions) Updating equivalent XLL article

- docs/concepts/browsers-used-by-office-web-add-ins.md
Some of the lines in this table have two Office versions, others have one. This PR makes this table more consistent.
> [all hosts] (Browser controls) Make browser table for perpetual versions more consistent

- docs/outlook/smart-alerts-onmessagesend-walkthrough.md
Addresses #4256.
Related PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67401
> [Outlook] (Smart Alerts) Document how to retrieve the contextData property

- docs/outlook/sideload-outlook-add-ins-for-testing.md
Caching issue has now been fixed.
> [Outlook] (sideloading) Remove caching note for Outlook on the web

- docs/develop/trusted-domains.md
- docs/toc.yml
After this is merged, I'll put a link to it in the appropriate manifest reference pages.
> [All Hosts] (security) technique for wildcards in trusted domain names

- docs/overview/office-add-ins-community-call.md
- Adds a link to the Office Add-ins video playlist on YouTube.
- Removes a redundant link to the Microsoft 365 dev YouTube channel.
> [All hosts] (community call) Update links

- docs/excel/excel-add-ins-ranges-precedents-dependents.md
- docs/toc.yml
This PR clarifies the introduction to the precedents and dependents article, removes a redundant paragraph, and updates the TOC title.
> [Excel] (Range) Refresh precedents and dependents article

- docs/overview/office-add-ins.md
User pointed out this mistake in a November 2023 verbatim.
> [All Hosts] (overview) correct mistake in overview

- docs/develop/xml-manifest-overview.md
These two blocks of code are from the PowerPoint VS manifest. 
1. I'm removing the domains block from the PowerPoint manifest and including it here instead. 
2. I'm keeping the GetStarted block in the PPT manifest but removing the code comments in that version (and adding the entire block + comments here).
> [all hosts] (Manifest) Adding sections to manifest example

- docs/outlook/autolaunch.md
- docs/outlook/mobile-event-based.md
Fixes #4294.
Related PR: https://github.com/OfficeDev/office-js-docs-reference/pull/1758
> [Outlook] (event-based activation) Remove Outlook on iOS as a supported client

- docs/quickstarts/fluent-react-quickstart.md
> [UI/UX] (Fluent) Clarify instructions on how to run add-in in Outlook

- docs/includes/node-20-warning-note.md
- docs/quickstarts/excel-quickstart-jquery.md
- docs/quickstarts/excel-quickstart-react.md
- docs/quickstarts/onenote-quickstart.md
- docs/quickstarts/outlook-quickstart-json-manifest.md
- docs/quickstarts/outlook-quickstart.md
- docs/quickstarts/powerpoint-quickstart.md
- docs/quickstarts/project-quickstart.md
- docs/quickstarts/sso-quickstart.md
- docs/quickstarts/word-quickstart.md
- docs/tutorials/excel-tutorial-create-custom-functions.md
- docs/tutorials/excel-tutorial.md
- docs/tutorials/outlook-tutorial.md
- docs/tutorials/powerpoint-tutorial.md
- docs/tutorials/word-tutorial.md
Fixes [4304](https://github.com/OfficeDev/office-js-docs-pr/issues/4304)
> [All Hosts] (quickstarts) note about Node.js version 20

- docs/overview/office-add-ins-community-call.md
- Adds a link to the November blog post.
- Adds the agenda for the December call.
> [All hosts] (community call) Update community call page

- docs/outlook/outlook-add-ins-overview.md
- docs/publish/publish.md
> [Outlook] (requirement sets) Add link to requirement set support tables

- docs/overview/office-add-ins-community-call.md
- Resets the agenda.
- Updates the start time.
- Replaces blog post links with a single link.
> [All hosts] (community call) Reset agenda and update start time

- docs/outlook/delegate-access.md
Updates the behavior of add-ins in shared mailboxes opened in Outlook on the web.
> [Outlook] (shared mailbox) Update add-in behavior in Outlook on the web

- docs/outlook/authenticate-a-user-with-an-sso-token.md
Deletion only. Already approved by product team. So, doesn't need a review.
> [Outlook] (sso) now fully supported with unified manifest

- docs/develop/authorize-to-microsoft-graph-without-sso.md
- docs/develop/authorize-to-microsoft-graph.md
- docs/develop/itp-and-third-party-cookies.md
- docs/develop/sso-in-office-add-ins.md
- docs/includes/chrome-tracking-prevention.md
Adds a note with links to resources about Google phase out of 3rd party cookies (tracking preventions).
> [All hosts] Auth: Google Tracking Prevention

- docs/develop/xml-manifest-overview.md
Mainly around how we mention task pane.
> [all hosts] (xml manifest) Minor refinements

- docs/toc.yml
Creates a task pane section in the 'UI and UX' portion of the TOC.
> [All hosts] (TOC) Create task pane section in TOC

- docs/outlook/append-on-send.md
Updates unified manifest support for the prepend-on-send feature.
> [Outlook] (prepend on send) Update unified manifest support

- docs/outlook/autolaunch.md
- docs/outlook/mobile-event-based.md
- docs/outlook/outlook-mobile-apis.md
Fixes #4360.
Related PRs:
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68514
- https://github.com/OfficeDev/office-js-docs-reference/pull/1827
> [Outlook] (event-based activation) Update Outlook on iOS support

- docs/develop/yeoman-generator-overview.md
- docs/includes/yo-office-command-guidance.md
There was customer feedback the quickstarts should let you know yo office is going to create a folder for your project. This PR addresses that. If the reviewers think this is overkill, I'm happy to cancel the PR.
> [all hosts] (yo office) Add folder information for yo office

- docs/testing/sideload-an-office-add-in-on-mac.md
> [All hosts] (Sideloading) Adjust steps in sideload on Mac article

- docs/develop/persisting-add-in-state-and-settings.md
- docs/excel/excel-add-ins-workbooks.md
- docs/toc.yml
This PR documents the new `partitionKey` API. It also reorganizes the persistence article to account for the mix of new/relevant Common APIs, older Common APIs, and app-specific APIs.
> [all hosts] (Storage) Add information about partition local storage and partitionKey

- docs/outlook/item-multi-select.md
> [Outlook] (item multi-select) Correct multi-select behavior in conversations

- docs/develop/xml-manifest-overview.md
Related PR: https://github.com/OfficeDev/office-js-docs-pr/pull/4381
> [All hosts] (manifest) Fixes formatting of XML comments and button text

- docs/design/built-in-button-integration.md
> [all hosts] Update supported clients for AddinCommands 1.3

- docs/includes/sso-yeoman-project-structure.md
fixes [4406](https://github.com/OfficeDev/office-js-docs-pr/issues/4406)
Doesn't need a review.
> [All Hosts] (auth) typo in path

- docs/outlook/append-on-send.md
This change is already in Office, so this is urgent and it is too trivial to need a review anyway.
> [Outlook] (manifest) JSON property name has changed

- docs/develop/automatically-open-on-installation.md
This is just a deletion that is requested by the product team, so it doesn't need a review.
> [All Hosts] (ux) open-on-install now supported on all platforms

- docs/develop/use-sso-to-get-office-signed-in-user-token.md
- docs/includes/file-get-the-whole-document-from-an-add-in-for-powerpoint-or-word.md
- docs/overview/create-an-office-add-in-from-script-lab.md
- docs/powerpoint/insert-slides-into-presentation.md
- docs/quickstarts/excel-quickstart-jquery.md
- docs/quickstarts/powerpoint-quickstart.md
- docs/quickstarts/word-quickstart.md
- docs/testing/application-specific-api-error-handling.md
- docs/tutorials/powerpoint-tutorial.md
This PR changes deprecated jQuery calls to the correct equivalents.
> [all hosts] (jQuery) Change jQuery click/change to on.('click'/'change')

- docs/outlook/one-outlook.md
The guidance on non-Microsoft accounts addresses https://github.com/OfficeDev/office-js/issues/4230.
> [Outlook] (new Outlook on Windows) Add guidance on non-Microsoft accounts and add-in location

- docs/outlook/onmessagesend-onappointmentsend-events.md
> [Outlook] (Smart Alerts) Document that icons in dialog can't be customized

- docs/excel/excel-add-ins-workbooks.md
> [excel] (Workbook) Clarify DocumentProperties doesn't have every property

- docs/develop/debug-office-add-ins-in-visual-studio.md
Update VS debugging article because some old problems are now fixed.
> [All Hosts] (debugging) Update VS debugging article because issues are fixed

- docs/overview/explore-with-script-lab.md
We've noticed an occasional comment or thread in the wild that seems to indicate people are using Script Lab as an automation solution. We want to make sure people are aware of Office Scripts, because of its simpler synchronous model.
> [excel] (Script Lab) Add note that Script Lab is unrelated to Office Scripts

- docs/develop/requirements-property-unified-manifest.md
…rty (#4507)
* [All Hosts] (manifest) supplementary reference for requirements property
---------
> [Admin] publish to live 

- docs/testing/debug-desktop-using-edge-chromium.md
Doesn't need a review.
Fixes [4517](https://github.com/OfficeDev/office-js-docs-pr/issues/4517)
> [All Hosts] (debugging) section title typo

- SECURITY.md
- docs/concepts/privacy-and-security.md
This PR removes militaristic language from these docs.
> [all] (Language) Adjust language for new security guidelines

- docs/develop/json-manifest-overview.md
- docs/develop/unified-manifest-overview.md
This update can be reviewed now, but will not be merged until the GA of the unified manifest for Outlook add-ins.
Fixes [4457](https://github.com/OfficeDev/office-js-docs-pr/issues/4457)
> [Outlook] (manifest) update for unified support of mobile and web

- docs/develop/unified-manifest-overview.md
> [Outlook] (manifest) fix JSON manifest sample

- docs/testing/runtimes.md
Updates the note and makes another change requested by the product team
> [All Hosts] (runtimes) Note about JS versions for the JS-only runtime

- docs/develop/dialog-api-in-office-add-ins.md
- docs/develop/dialog-best-practices.md
- docs/develop/dialog-handle-errors-events.md
Internal ADO work item: 8897602
> [All hosts] (dialog) Document Cross-Origin-Opener-Policy requirement

- docs/outlook/delegate-access.md
- Adds support for new Outlook on Windows.
- Remove content as requested by the feature crew.
> [Outlook] (shared mailbox) Update supported clients and remove content

- docs/develop/grant-admin-consent-to-an-add-in.md
- docs/outlook/authenticate-a-user-with-an-sso-token.md
- docs/toc.yml
Fixes [4527](https://github.com/OfficeDev/office-js-docs-pr/issues/4527)
> [All Hosts] (auth) add info for revoking permissions

- docs/excel/excel-add-ins-ranges-cut-copy-paste.md
Cross-linking relevant Script Lab sample in article.
> [Excel] (Range) Add Script Lab link for cut, copy, paste APIs

- docs/develop/enable-nested-app-authentication-in-your-add-in.md
Updates API changes for MSAL browser 3.15.0 and later.
> [All hosts] (NAA) update for changes in MSAL library

- docs/outlook/add-and-remove-attachments-to-an-item-in-a-compose-form.md
Related PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69733
> [Outlook] (attachments) Document how to remove inline attachments

- docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md
(Based on customer feedback)
The add-ins pop-up window changed a UI string. This PR updates the docs to reflect that.
> [all] (Sideloading) Update network share instructions to reflect current UI

- docs/develop/install-latest-office-version.md
The original link now redirects.
> [all hosts] Remove support.office.com links

- docs/develop/make-office-add-in-compatible-with-existing-com-add-in.md
- Documents how to obtain the ProgId of a COM add-in.
- Removes VSTO references as these add-ins don't have a ProgId.
> [All hosts] (COM) Document how to obtain the ProgId of a COM add-in

- docs/design/built-in-button-integration.md
> [PowerPoint] (UI) Clarify OfficeGroup ribbon support is for PowerPoint only

- docs/design/keyboard-shortcuts.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/4568.
> [Excel] (keyboard shortcut) Update code snippet that calls Office.actions.associate

- docs/outlook/one-outlook.md
> [Outlook] (new Outlook) Clarify support for classic Outlook on Windows

- docs/develop/json-manifest-overview.md
- docs/develop/requirements-property-unified-manifest.md
- docs/develop/unified-manifest-overview.md
Related PR https://github.com/MicrosoftDocs/msteams-docs/pull/11204
> [all hosts] (context menu) Document support in unified manifest

- docs/excel/excel-add-ins-events.md
@AlexJerabek Do we want to make any other updates here based on [Word PR feedback](https://github.com/OfficeDev/office-js-docs-pr/pull/4651)?
> [Excel] (events) Update based on Word article feedback

- docs/overview/learning-path-beginner.md
Update based on [feedback](https://github.com/OfficeDev/office-js-docs-pr/pull/4675#pullrequestreview-2186674009) from related PR.
> [all hosts] Include scenarios in beginner's guide

- docs/onenote/index.yml
- docs/onenote/onenote-add-ins-programming-overview.md
Also updating the ms.date to reflect recent reviews.
> [OneNote] (IA) Paring down links in the OneNote overview page

- docs/reference/javascript-api-for-office.md
I think the PPT space has grown enough to remove this comment. Thoughts?
> [PowerPoint] (general) Removing note about limited PPT API support

- docs/develop/develop-overview.md
- docs/overview/learning-path-beginner.md
- docs/overview/set-up-your-dev-environment.md
This can merge right away. Doesn't have to wait till WXP support of unified manifest is in public preview.
> [All Hosts] (get started) update for unified manifest and Teams toolkit

- docs/design/disable-add-in-commands.md
Related PR: https://github.com/OfficeDev/office-js-docs-reference/pull/2005
> [WXP] (RibbonApi 1.1) Document support in Office on the web

- docs/develop/custom-protocol-handler.md
- docs/publish/custom-protocol-handler.md
- docs/toc.yml
This PR describes how to setup custom protocol handlers that launch add-ins.
> [all hosts] (Launch) Add article about custom protocol handlers

- docs/publish/host-an-office-add-in-on-microsoft-azure.md
- docs/toc.yml
This procedure can only be done on the developer's computer, so it's not a way to host a production application. Need to clarify that. 
Fixes [4666](https://github.com/OfficeDev/office-js-docs-pr/issues/4666)
> [All Hosts] (devx) Clarify staging on Azure from VS

- docs/publish/host-an-office-add-in-on-microsoft-azure.md
Responds to verbatim from customer.
> [All Hosts] (publish) update Azure staging article

- docs/develop/enable-nested-app-authentication-in-your-add-in.md
- docs/outlook/authentication.md
Related PR: https://github.com/OfficeDev/office-js-docs-pr/pull/4698
> [All hosts] (auth) Correct Insider channel and add link to supported hosts

- docs/publish/host-an-office-add-in-on-microsoft-azure.md
> [Outlook] (publish) non-support of Outlook in Azure staging article

- Contributing.md
Based on a customer PR submission that never signed the MS Contributor Agreement.
> [admin] (Contributing) Edit pass on the contributing file

- docs/outlook/one-outlook.md
- Links to information on the installation of web add-in counterparts when a user switches to new Outlook on Windows.
- Updates links.
> [Outlook] (new Outlook) Update admin guidance

- docs/design/contextual-tabs.md
As reported in https://github.com/OfficeDev/office-js/issues/4814
> [excel] (UX) Add note about undo behavior for contextual tabs

- docs/design/data-visualization-guidelines.md
> Fix broken link

- docs/testing/sideload-an-office-add-in-on-ipad.md
Fixes [4764](https://github.com/OfficeDev/office-js-docs-pr/issues/4764).
Fixes a verbatim.
> [Excel Word] (iPad) update iPad sideload article

- docs/testing/clear-cache.md
Related to https://github.com/OfficeDev/office-js/issues/4447.
> [Outlook] (cache) Document how to clear the cache in new Outlook on Windows

- docs/develop/install-latest-office-version.md
- Update links to Insider content
- Remove extraneous info from xml example
- Change branch name to CurrentPreview in xml example (FirstRelease naming is very old)
Screenshot needs to be updated as well. "First Release" is very old out-dated branding/naming.
> Insider related changes

- docs/outlook/sideload-outlook-add-ins-for-testing.md
> [Outlook] (manifest) Update manifest term

- docs/excel/custom-functions-debugging.md
- docs/excel/make-custom-functions-compatible-with-xll-udf.md
- docs/toc.yml
Reordering articles in TOC to better approximate relevance to a new customer. This PR also updates the XLL article title per August low engagement and high bounce rate data.
> [Excel] (Custom functions) Refactor custom functions articles

- docs/outlook/delay-delivery.md
Related to https://github.com/OfficeDev/office-js/issues/4847.
> [Outlook] (delay delivery) Clarify behavior setAsync API

- docs/develop/unified-manifest-overview.md
- docs/outlook/add-mobile-support.md
- docs/outlook/mobile-log-appointments.md
- docs/outlook/online-meeting.md
- docs/outlook/outlook-mobile-addins.md
Fixes [4806](https://github.com/OfficeDev/office-js-docs-pr/issues/4806)
> [Outlook] (manifest) update key and property name

- docs/outlook/on-new-compose-events-walkthrough.md
- docs/outlook/onmessagefromchanged-onappointmentfromchanged-events.md
- docs/outlook/smart-alerts-onmessagesend-walkthrough.md
- docs/outlook/spam-reporting.md
- docs/outlook/troubleshoot-event-based-and-spam-reporting-add-ins.md
Related PR: https://github.com/OfficeDev/Office-Add-in-samples/pull/846
> [Outlook] (event-based activation) Remove platform check from walkthroughs

- docs/design/keyboard-shortcuts.md
- docs/overview/office-add-in-code-samples.md
Related PR: https://github.com/OfficeDev/Office-Add-in-samples/pull/853
> [Word] (keyboard shortcuts) Update sample

- docs/outlook/pinnable-taskpane.md
Rewords AppSource requirement for Outlook add-ins that implement a pinnable task pane based on customer feedback.
> [Outlook] (pinning) Clarify AppSource requirement

- docs/design/disable-add-in-commands.md
Related to https://github.com/OfficeDev/office-js/issues/3422.
> [All hosts] (add-in commands) Document supported add-in commands to enable or disable

- docs/concepts/browsers-used-by-office-web-add-ins.md
Related PR: https://github.com/OfficeDev/office-js-docs-reference/pull/2093
> [All hosts] (platform) Document support for Office LTSC 2024

- docs/design/add-in-commands.md
Fixes [4854](https://github.com/OfficeDev/office-js-docs-pr/issues/4854)
> [All Hosts] (ui) dialog + add-in command timeout

- docs/develop/enable-nested-app-authentication-in-your-add-in.md
- docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md
* Latest NAA updates
* edits
* updates around GA support
* typo
* minor update
* updates from review feedback
> [Admin] (Publish)

- docs/design/design-toolkits.md
Related PR: https://github.com/OfficeDev/office-js-docs-pr/pull/4808
> [All hosts] (UI) Update Fabric Core URL

- docs/develop/convert-javascript-to-typescript.md
Fixes #4867.
Some of the steps in this article were out-of-date with UI and template changes. This PR should address that.
> [all hosts] (Visual Studio) Revise VS JS->TS steps

- docs/develop/troubleshoot-sso-in-office-add-ins.md
Also updates the title of a referenced article.
> [Outlook] (SSO) Update error 13001 scenario

- docs/develop/dialog-api-in-office-add-ins.md
Fixes #4870.
Also applies minor formatting fixes.
> [All hosts] (dialog) Correct code sample

- docs/publish/publish-office-add-ins-to-appsource.md
- docs/publish/publish.md
> [Excel, PowerPoint, Word] (publish) include add-in in Windows/COM/VSTO installation

- docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md
> [Outlook](NAA) fix link

- docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md
This is just to fix a broken link.
> [Outlook](FAQ) fix link

- docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md
- docs/outlook/turn-exchange-tokens-on-off.md
This fixes a couple of broken links.
> [Outlook](NAA) fix links

- docs/design/keyboard-shortcuts.md
Related to https://github.com/OfficeDev/Office-Add-in-samples/pull/897.
> [Word] (keyboard shortcuts) Clarify feature support in Word on the web

- docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md
Documents a common question about moving from the old Exchange token scenario of validating the ID token to use it in services.
> [Outlook](NAA) Add section about identity and your services

- docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md
- Add a publisher
- Clarify a few MSAL statements.
> [Outlook](NAA) update to FAQ

- docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md
> [Outlook](NAA) Fix typo

- docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md
- docs/outlook/turn-exchange-tokens-on-off.md
Updates for the tooling to turn tokens on or off. Tooling now supports production tenants.
> [Outlook](Exchange tokens) Updates on tooling to turn tokens on or off

- docs/outlook/onmessagesend-onappointmentsend-events.md
Reverts OfficeDev/office-js-docs-pr#4951
> [Outlook] (Smart Alerts) Revert changes

- docs/develop/create-addin-commands-unified-manifest.md
- docs/develop/get-the-whole-document-from-an-add-in-for-powerpoint-or-word.md
- docs/develop/referencing-the-javascript-api-for-office-library-from-its-cdn.md
- docs/develop/specify-office-hosts-and-api-requirements.md
- docs/develop/support-ie-11.md
- docs/includes/office-js-access-library.md
- docs/outlook/apis.md
- docs/outlook/item-multi-select.md
- docs/outlook/mobile-log-appointments.md
- docs/project/create-a-project-add-in-that-uses-rest-with-an-on-premises-odata-service.md
- docs/tutorials/excel-tutorial.md
- docs/tutorials/outlook-tutorial.md
- docs/word/dictionary-task-pane-add-ins.md
Reverts https://github.com/OfficeDev/office-js-docs-pr/pull/4830 based on internal guidance.
> [All hosts] Revert previous change to CDN URL

- docs/develop/usability-testing.md
InVision appears to have shut down, so we should guide readers to a new UI prototyping tool. Figma seems to be the logical choice.
> [all hosts] (Testing) Replace UI prototyping tool recommendation

- docs/concepts/correlated-objects-pattern.md
- docs/concepts/resource-limits-and-performance-optimization.md
A couple of our performance articles were flagged for low engagement. This PR gives them a refresh. It cleans up some minor style things and tries to make them slightly more concise.
> [all hosts] (Performance) Refresh performance articles for engagement

- docs/outlook/turn-exchange-tokens-on-off.md
- Adds info on how to use the Get-AuthenticationPolicy command for legacy token status.
- Adds info to clarify -Identity must always be set to LegacyExchangeTokens.
> [Outlook](legacy tokens) Add information on how to get token status

- docs/outlook/debug-autolaunch.md
- docs/outlook/troubleshoot-event-based-and-spam-reporting-add-ins.md
Related to https://github.com/OfficeDev/office-js/issues/5220.
> [Outlook] (debug) Clarify JS engine used when debugging event-based and spam-reporting add-ins

- docs/publish/government-cloud-guidance.md
jonahkarpman has approved by email
> [All Hosts] (DevX) GCC now has a special URL

- docs/concepts/requirements-for-running-office-add-ins.md
Related to https://github.com/OfficeDev/office-js/issues/3559#issuecomment-2637894778.
> [Outlook] (mobile) Document supported iPadOS versions

- docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md
- update add-in complete list.
- minor edits.
> [Outlook](legacy tokens) update add-in list

- .openpublishing.publish.config.json
Awaiting https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71857 and https://github.com/OfficeDev/office-js-docs-reference/pull/2198
> [Excel] Release ExcelApi 1.18 to GA

- docs/outlook/turn-exchange-tokens-on-off.md
Add missing parameter to command
> [Outlook](legacy tokens) add missing parameter

- docs/develop/debug-office-add-ins-in-visual-studio.md
Refreshes low engagement article
> [All Hosts] (debugging) refresh VS debugging

- docs/includes/calendar-availability.md
- docs/outlook/outlook-add-ins-overview.md
- docs/outlook/outlook-addin-design.md
- docs/overview/office-add-ins.md
Fixes [5048](https://github.com/OfficeDev/office-js-docs-pr/issues/5048)
> [Outlook] (calendar) Add-ins not supported in Teams calendar

- docs/outlook/outlook-add-ins-overview.md
> [Outlook] Fix link

- docs/outlook/delegate-access.md
- Fixes #5019. Related to https://github.com/OfficeDev/office-js/issues/5270.
- Updates which platforms support the Message Compose behavior.
> [Outlook] (shared folder/mailbox) Correct platform support

- docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md
Add SalesForce to the NAA complete list.
> [Outlook](Exchange tokens) Add publisher

- docs/develop/specify-office-hosts-and-api-requirements-unified.md
- docs/develop/specify-office-hosts-and-api-requirements.md
Fixes the CDN URL and removes trailing spaces.
> [All hosts] Fix Office.js CDN URL

- docs/outlook/extension-module-outlook-add-ins.md
Fixes [#2208](https://github.com/OfficeDev/office-js-docs-reference/issues/2208).
> [Outlook] (module extensions) Clarify supported Outlook client

- docs/develop/create-addin-commands.md
Related PR: https://github.com/OfficeDev/office-js-docs-reference/pull/2217
> [All hosts] (add-in commands) Add guidance about the Office.actions.associate call

- docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md
- docs/outlook/turn-exchange-tokens-on-off.md
Update docs to indicate report tooling delayed.
> [Exchange](tokens) Report tooling update

- docs/design/keyboard-shortcuts.md
- docs/develop/configure-your-add-in-to-use-a-shared-runtime.md
- docs/develop/develop-overview.md
Also adds links to the unified manifest schema.
> [Word] (keyboard shortcuts) Document support in Word on the web

- docs/outlook/outlook-mobile-apis.md
Documents support for the Office.EventCompletedOptions object on Outlook on mobile devices.
> [Outlook] (mobile) Update list of supported APIs

- docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md
Clarifying the messaging around ID tokens to be super clear about how and when to use them.
And add some error info about what happens when Exchange tokens are off.
> [Outlook](Exchange tokens) Update FAQ for ID token scenarios

- docs/publish/publish-office-add-ins-to-appsource.md
Purely technical change doesn't require a review.
> [All Hosts] (publish) new parameter on installation links

- docs/develop/convert-xml-to-json-manifest.md
Fixes [5124](https://github.com/OfficeDev/office-js-docs-pr/issues/5124)
> [All Hosts] (devx) new step for converting to unified manifest

- docs/outlook/turn-exchange-tokens-on-off.md
Some customers see IDs getting listed in the allowed blocked lists from the command but it's just old data. Adding note to clarify this.
> [Outlook] (NAA) add note about allowed blocked list

- docs/includes/alert-use-https.md
- docs/includes/outlook-manual-sideloading.md
- docs/outlook/contextless.md
- docs/outlook/item-multi-select.md
- docs/outlook/sideload-outlook-add-ins-for-testing.md
- docs/quickstarts/excel-quickstart-jquery.md
> [All hosts] (Yeoman) Add note about workaround to sign in

- docs/develop/convert-javascript-to-typescript.md
Removes note about issue with VS template now that the typo has been fixed.
Related to #4868.
> [All hosts] (Visual Studio) Remove note about template issue

- docs/design/agent-and-add-in-overview.md
- docs/develop/agent-and-add-in.md
- docs/quickstarts/agent-and-add-in-quickstart.md
Doesn't need a review. And the current metadata date is today anyway.
> [All Hosts] (copilot) update schema version

- docs/quickstarts/sso-quickstart.md
> [Outlook] (quickstart) fix confusing step on sideloading

- docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md
Fixes #5189. 
Updating the instructions to match the new UI.
> [WXP] (DevEx) Update network share UI steps

- docs/outlook/faq-nested-app-auth-outlook-legacy-tokens.md
Adds link to support help for more info on admin exceptions.
> [Exchange] (legacy tokens) Add link for support help

- docs/outlook/turn-exchange-tokens-on-off.md
Adds information on how the telemetry reporting works with dates and updates.
> [Outlook] (legacy tokens) information on how the report works

- docs/develop/manifest-element-ordering.md
fixes [5199](https://github.com/OfficeDev/office-js-docs-pr/issues/5199)
> [Outlook] (manifest) update element-ordering article

- docs/includes/quickstart-troubleshooting-yo.md
Fixes #5203.
This PR adds a note to the quick start troubleshooting section about npm install warnings. It gives some guidance about the severity and how to fix them.
> [all hosts] (Quick starts) Add quickstart troubleshooting note about outdated packages

- docs/develop/dialog-best-practices.md
> [All hosts] (Device Permission) Clarify which clients support access to geolocation

- docs/publish/publish.md
Remove row that was mistakenly left in a table when this article was last updated.
Does not require a review.
> [All Hosts] (publish) remove table row

- docs/testing/application-specific-api-error-handling.md
- docs/testing/testing-and-troubleshooting.md
Based on a recent incident, we should provide guidance for configuring antivirus software to not block add-in functionality in Office.
> [all hosts] (Troubleshooting) Add instructions for dealing with antivirus related access denied errors

- docs/project/create-a-project-add-in-that-uses-rest-with-an-on-premises-odata-service.md
This Project article had a broken link. This PR fixes that and does a quick style pass on the content.
> [admin] (Links) Fix link and improve style

- docs/outlook/onmessagesend-onappointmentsend-events.md
On-Send feature is supported on New Outlook for Windows.
> Update Differences between Smart Alerts and the on-send feature

- docs/design/content-add-ins.md
- docs/design/fabric-core.md
- docs/excel/excel-add-ins-overview.md
- docs/quickstarts/excel-quickstart-content.md
Also removing the link from the Fabric article, since the UI in that sample changed.
> [excel] (Content Add-in) Adjust links to point to new sample location

- docs/word/word-add-ins-events.md
Although this article no longer has engagement flags as of Jul data, I'm taking the opportunity to make a few updates anyway, including upleveling several sections.
> [Word] (Refresh) Update events article

- docs/design/add-in-commands.md
- docs/outlook/one-outlook.md
Add-ins in Outlook on the web and the new Outlook on Windows now appear on the ribbon again.
> [Outlook] (ribbon) Update guidance on add-in location

- docs/design/first-run-experience-patterns.md
- docs/tutorials/first-run-experience-tutorial.md
> [all hosts] (FRE) Refresh patterns and tutorial

- docs/develop/agents-toolkit-overview.md
- docs/includes/unified-manifest-sideload-restrictions-note.md
- docs/testing/sideload-add-in-with-unified-manifest.md
This deletion approved by product team. Needs no review.
> [All Hosts] (devx) cut bad info about Mac and unified manifest

- docs/excel/custom-functions-parameter-options.md
This PR incorporates internal feedback.
> [Excel] (Custom functions) Update range parameter sample

- docs/design/add-in-icons-fresh.md
Removes outdated Fabric UI link.
> [All hosts] (UI) Remove outdated link

- docs/develop/persisting-add-in-state-and-settings.md
Customer requested this information.
> [All Hosts] (devx) partitioning criterion

- docs/excel/excel-add-ins-dot-functions.md
This PR is a combination of a GitHub Copilot review and a human editing pass of the dot notation article. It fixes typos, better aligns to article to Microsoft Style Guide, and makes minor changes to improve clarity.
> [Excel] (Data types) Editing pass of dot notation article

- docs/project/project-add-ins.md
- docs/quickstarts/project-quickstart.md
This PR gets our Project articles better aligned with our other intro material.
> [Project] Refresh Project articles

- docs/resources/resources-office-add-in-known-issues.md
Moved the inline images in signature known issue to **Recently resolved** section.
> Resolve issue

- docs/develop/dialog-video.md
This page has a high bounce rate and a low copy/try/scroll rate. This PR hopes to address that.
> [UI/UX] (Dialog) Refresh dialog video article

- docs/resources/resources-office-add-in-known-issues.md
Per product team input:
- Update known issue [10529994](https://office.visualstudio.com/OC/_workitems/edit/10529994)
- Add fixed issue [10607166](https://office.visualstudio.com/OC/_workitems/edit/10607166) to recently fixed section
> Update Excel known issues
