OfficeDev/office-js-docs-pr

- Issue_Template.md
This is latest sync to bring repo up to date with original office-js-docs repo.
> synced latest changes from upstream master

- docs/excel/custom-functions-overview.md
- docs/publish/publish.md
sync latest changes from office-js-docs before going live
> sync latest changes

- docs/index.yml
> Update links in index.yml (docs landing page).

- docs/toc.yml
- docs/tutorials/excel-tutorial-protect-worksheet.md
Add **displayName** attribute in TOC.yml to enable accurate results when filtering TOC by product (host) name.
> Improve TOC filtering accuracy

- docs/develop/persisting-add-in-state-and-settings.md
update persistence article, mainly adding XML parts
> Merge to live!

- docs/design/using-office-ui-fabric-react.md
- Rescoped the body variable from `var `to `let `( fixes issue #58 )
- Corrected minor markdown issues
> Corrected Variable Scope

- docs/excel/excel-add-ins-advanced-concepts.md
> Typo in excel-add-ins-advanced-concepts.md

- docs/design/content-add-ins.md
> merge to live! 

- docs/excel/excel-add-ins-events.md
remove onDeletedEvent because it was icluded in 1.8, and rename onDataChanged to onChanged
> Update the event intro up to date

- docs/design/content-add-ins.md
> fix relative URL

- docs/toc.yml
> Update to Quick Start

- docs/develop/create-and-debug-office-add-ins-in-visual-studio.md
- docs/excel/script-lab-test.md
- docs/testing/debug-add-ins-in-office-online.md
Program: https://developer.microsoft.com/en-us/office/dev-program
Docs: https://docs.microsoft.com/en-us/office/developer-program/office-365-developer-program
> Updated links to Office 365 Dev Program

- docs/testing/debug-office-add-ins-on-ipad-and-mac.md
This adds instructions to allow debugging of Office add-ins on recent Office 365 builds.
> Update Mac Debugging topic

- docs/includes/file-get-started-onenote.md
- docs/onenote/onenote-add-ins-getting-started.md
- docs/quickstarts/onenote-quickstart.md
> Update OneNote quick start

- docs/excel/excel-add-ins-data-validation.md
@Rick-Kirkham I didn't want to merge directly to the master branch, so I created a PR. I'll let you accept it. Thanks, lindalu
> minor fixes

- docs/excel/custom-functions-overview.md
The Gif does not appear in preview? I assume it will when published?
> minor edits

- docs/excel/custom-functions-overview.md
The JSON schema details have been moved to the Sample readme.
Also added a bunch of Known Issues.
> Last edits to the custom functions topic before Build

- docs/design/accessibility-guidelines.md
- docs/design/voice-guidelines.md
- docs/toc.yml
gave voice and accessibility their own pages
> separate guidelines

- docs/concepts/add-in-development-best-practices.md
Long running lower bound should be >5 seconds, not ms.
> Small typo fix

- docs/excel/excel-add-ins-charts.md
The Chart APIs discussed in the article are in GA as of 1.7.
> Remove beta notes from Excel chart story

- docs/includes/file-get-started-onenote.md
This was causing the text box input to not be read and inserted in the sample.
> Removing initialize line from snippet

- docs/includes/file-get-started-excel-jquery.md
Addressing issue https://github.com/OfficeDev/office-js-docs-pr/issues/267
> update file name

- docs/excel/excel-add-ins-events.md
Added the beta events based on what's in the [open spec](https://github.com/OfficeDev/office-js-docs/blob/ExcelJs_OpenSpec/reference/new-events.md).
> Adding beta events

- docs/excel/excel-add-ins-core-concepts.md
Also correcting a dev.office link that gets redirected anyway.
> Fixing perf links

- docs/concepts/privacy-and-security.md
- docs/concepts/resource-limits-and-performance-optimization.md
- docs/design/using-motion-office-addins.md
- docs/develop/addressing-same-origin-policy-limitations.md
Deals with 1-5. Following up with editors re 6 and 7.
> fix broken links

- docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md
- docs/testing/sideload-office-addin-using-sideload-command.md
* clarifying when the 2 methods can and cannot be used
* fix broken links
> Clarify two sideload methods (#291)

- docs/includes/file-get-started-excel-react.md
The spaces were preventing the image and note from displaying properly.
> Fixing MD spacing

- docs/develop/localization.md
- docs/includes/file-get-started-excel-react.md
- docs/includes/file-get-started-project.md
- docs/includes/file-get-started-word.md
Mainly applied to the quick start samples, not tutorials.
> update other broken app.js mentions

- docs/excel/excel-add-ins-events.md
A section explaining the upcoming event enable/disable feature.
> Event enabling documentation

- docs/develop/create-sso-office-add-ins-aspnet.md
The text instructions are not aligned with the subsequent commands for the MSAL library.
> Update MSAL client library version in text

- docs/develop/create-and-debug-office-add-ins-in-visual-studio.md
Fixing this issue: https://github.com/OfficeDev/office-js-docs-pr/issues/316
> clarifying which project properties to open

- Contributing.md
Updating this file with changes recently applied to the same file in `OfficeDev/office-js-docs-reference`.
> Minor updates to the Contributing.md file.

- docs/develop/asynchronous-programming-in-office-add-ins.md
There was a broken link in this file, so I took the liberty of updating it and the rest to point at the new reference docs.
> Updating links

- docs/develop/understanding-the-javascript-api-for-office.md
> update initialization section to describe onReady

- docs/overview/office-add-in-availability.md
Also took the opportunity to update dev.office.com links
> update host and platform support

- docs/design/add-in-commands.md
- docs/design/add-in-icons.md
- docs/design/content-add-ins.md
- docs/design/task-pane-add-ins.md
- docs/develop/convert-javascript-to-typescript.md
- docs/develop/install-latest-office-version.md
- docs/develop/usability-testing.md
- docs/excel/co-authoring-in-excel-add-ins.md
- docs/excel/excel-add-ins-advanced-concepts.md
- docs/excel/excel-add-ins-core-concepts.md
- docs/includes/file-get-started-word.md
- docs/includes/quickstart-vs-prerequisites.md
- docs/publish/centralized-deployment.md
- docs/publish/host-an-office-add-in-on-microsoft-azure.md
- docs/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog.md
- docs/publish/publish.md
- docs/testing/debug-add-ins-in-office-online.md
- docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md
Updated some pages to make them version-inclusive/agnostic. I didn't change some references because I think the reference to the version was needed. Let me know if you have any questions.
> Linda scrub 828

- docs/design/task-pane-add-ins.md
- docs/develop/convert-javascript-to-typescript.md
- docs/excel/excel-add-ins-advanced-concepts.md
- docs/excel/excel-add-ins-core-concepts.md
- docs/includes/quickstart-vs-prerequisites.md
- docs/publish/centralized-deployment.md
Rollback some of the recent changes made via PR #361 .
> Rollback some recent changes

- docs/develop/create-sso-office-add-ins-nodejs.md
The inner steps, indented by one space, will render as
a. blah blah blah
b. blah blah blah
c. blah blah blah
> add instructions to enable Developer tab

- docs/excel/custom-functions-overview.md
New runtime no longer needs that
> remove initialization section as it is not needed

- docs/overview/office-add-in-availability.md
add 1.7 availability - pending https://github.com/OfficeDev/office-js-docs-reference/pull/174
> Outlook September updates

- docs/excel/excel-add-ins-data-validation.md
- docs/excel/excel-add-ins-events.md
- docs/excel/excel-add-ins-pivottables.md
- docs/excel/excel-add-ins-ranges.md
Removing the beta notes from concepts that are now in GA.
@JuaneloJuanelo and @Zlatkovsky, Please advise about the OLAP warning for PivotTables.
> Updating Excel articles for GA

- docs/excel/custom-functions-best-practices.md
Apparently in the new yo office Sept Refresh this is no longer optional
> Updating Custom Functions Mappings

- docs/excel/custom-functions-best-practices.md
> Changing to make CustomFunctionMappings required

- docs/excel/custom-functions-best-practices.md
- docs/excel/custom-functions-json.md
- docs/excel/custom-functions-overview.md
- docs/excel/custom-functions-runtime.md
There was an ask to change any outstanding helpUrls and other random made-up urls to go to contoso.com
> changing ts to typescript and changing urls to contoso

- docs/excel/custom-functions-best-practices.md
Add info about using `debugger;` statement with F12 developer tools.
> Update Debugging section

- docs/excel/custom-functions-best-practices.md
- docs/excel/custom-functions-json.md
- docs/excel/custom-functions-overview.md
- docs/excel/excel-add-ins-error-handling.md
- docs/excel/excel-add-ins-overview.md
- docs/excel/excel-add-ins-pivottables.md
This PR contains the following changes:
- Updated section title to better describe contents of the section
- Added introductory info to provide context about what the mappings are, what they do...if the reader doesn't understand this first, then the 'best practices' info won't make much sense to them.
- Reworded sentence that introduces list of best practices to be written in an active voice (i.e., to eliminate the clause at the beginning of the sentence and avoid using the passive phrase "there are several best practices...")
- Updated the list of best practices.
- Removed list item for "Function names and ids should match in the functions JSON file." list item because this isn't true. The whole point of having an `id` property in addition to the `name` property is so that you can set …
> Kim's edits to Best Practices updates

- docs/excel/custom-functions-best-practices.md
- docs/excel/custom-functions-json.md
- docs/excel/custom-functions-overview.md
- docs/excel/excel-add-ins-error-handling.md
- docs/excel/excel-add-ins-overview.md
- docs/excel/excel-add-ins-pivottables.md
Since CFMapping is now required, Kim & I plan to move that content to the overview. Thus, the best practices should reflect actual guidance and not a definition of what it is.
> Updates to best practices to give guidance

- docs/excel/excel-add-ins-data-validation.md
> Removing "Preview" from Data Validation

- docs/includes/file-get-started-word.md
Addresses customer complaint: Issue https://github.com/OfficeDev/office-js-docs-pr/issues/454
> availability of custom button note to Word quickstart

- docs/includes/file-get-started-onenote.md
- docs/includes/file-get-started-powerpoint.md
- docs/includes/file-get-started-project.md
- docs/includes/quickstart-yo-start-server.md
Fix issues that were created when Yo Office was recently rev'd.
> Update Project quick start

- docs/excel/excel-add-ins-error-handling.md
- docs/includes/file-get-started-word.md
- docs/onenote/onenote-add-ins-getting-started.md
- docs/powerpoint/powerpoint-add-ins-get-started.md
- docs/project/project-add-ins-get-started.md
- docs/quickstarts/onenote-quickstart.md
- docs/quickstarts/powerpoint-quickstart.md
- docs/quickstarts/project-quickstart.md
- docs/quickstarts/word-quickstart.md
- docs/word/word-add-ins.md
- Fix issues that were created when Yo Office was recently rev'd.
- Update ms.date for each of the quick starts that I've updated today.
- Minor update to wording in Excel - Error Handling article.
> Update Word quick start and a few other things

- docs/testing/debug-add-ins-using-f12-developer-tools-on-windows-10.md
Fixes issue #220 (and other minor problems with this article).
> Update F12 developer tools article

- docs/powerpoint/powerpoint-add-ins.md
Numerous editorial changes, made during the course of investigating issue #157.
> Update PowerPoint add-ins overview article

- docs/excel/excel-add-ins-events.md
Capturing the information in Issue #432.
> Clarifying event handler lifecycle

- docs/testing/attach-debugger-from-task-pane.md
Added debugging steps in case the personality menu is not available.
> Added debugging steps for Visual Studio

- docs/excel/excel-add-ins-get-started-jquery.md
- docs/includes/file-get-started-excel-jquery.md
- docs/quickstarts/excel-quickstart-jquery.md
Fix issues that were created when Yo Office was recently rev'd.
> Update Excel (jQuery) quick start

- docs/excel/excel-add-ins-get-started-react.md
- docs/includes/file-get-started-excel-jquery.md
- docs/includes/file-get-started-excel-react.md
- docs/quickstarts/excel-quickstart-react.md
Fix issues that were created when Yo Office was recently rev'd. 
(Also fix a mistake in the Excel jQuery quick start.)
> Update Excel (React) quick start

- docs/develop/create-sso-office-add-ins-aspnet.md
To see references, left-click on expand icon is required.
> Right-click on References doesn't show references.

- docs/excel/custom-functions-best-practices.md
moved it up to troubleshooting section as it's a common issue that people seem to be hitting this week
> Make runtime logging note stand out more

- docs/excel/custom-functions-overview.md
update change log (we'll need a seperate update on the any type)
> add note about the ID change

- docs/excel/excel-add-ins-data-validation.md
This is to address Issue #492. 
The corresponding DT change is [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30065).
> Fixing ListDataValidation.source type

- docs/testing/troubleshoot-manifest.md
> Update runtime logging info

- docs/reference/overview/excel-add-ins-reference-overview.md
- docs/reference/overview/onenote-add-ins-javascript-reference.md
- docs/reference/overview/word-add-ins-reference-overview.md
- docs/toc.yml
Addresses VSO item [2618377](https://office.visualstudio.com/OC/_workitems/edit/2618377).
You can see the revised TOC here: [https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/javascript-api-for-office?branch=kb-update-ref-toc-20181030](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/javascript-api-for-office?branch=kb-update-ref-toc-20181030)
> Restructure Reference section of TOC

- docs/excel/custom-functions-runtime.md
Adding clarification as flagged by both Madhav and RE: a customer on Stack-Overflow
> More clarification on AsyncStorage

- docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.md
- docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.userProfile.md
- docs/reference/objectmodel/requirement-set-1.1/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.1/office.context.mailbox.md
- docs/reference/objectmodel/requirement-set-1.1/office.context.mailbox.userProfile.md
- docs/reference/objectmodel/requirement-set-1.2/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.2/office.context.mailbox.md
- docs/reference/objectmodel/requirement-set-1.2/office.context.mailbox.userProfile.md
- docs/reference/objectmodel/requirement-set-1.3/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.3/office.context.mailbox.md
- docs/reference/objectmodel/requirement-set-1.3/office.context.mailbox.userProfile.md
- docs/reference/objectmodel/requirement-set-1.4/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.4/office.context.mailbox.md
- docs/reference/objectmodel/requirement-set-1.4/office.context.mailbox.userProfile.md
- docs/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.5/office.context.mailbox.md
- docs/reference/objectmodel/requirement-set-1.5/office.context.mailbox.userProfile.md
- docs/reference/objectmodel/requirement-set-1.6/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.6/office.context.mailbox.md
- docs/reference/objectmodel/requirement-set-1.6/office.context.mailbox.userprofile.md
- docs/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.7/office.context.mailbox.md
- docs/reference/objectmodel/requirement-set-1.7/office.context.mailbox.userProfile.md
Addresses feedback from https://github.com/OfficeDev/office-js-docs-pr/pull/518
> Add language to Outlook samples

- docs/develop/convert-javascript-to-typescript.md
Fixes issues: #317, #318, #319, and #320.
> Update instructions in the Convert JS to TS (in VS) article

- docs/reference/overview/excel-add-ins-reference-overview.md
The overview page needed showcase some of the newer features.
> Updating the Excel overview with objects from 1.6+

- docs/develop/create-and-debug-office-add-ins-in-visual-studio.md
- docs/includes/excel-tutorial-create-table.md
- docs/includes/excel-tutorial-protect-worksheet.md
- docs/includes/file-get-started-excel-angular.md
- docs/includes/file-get-started-excel-jquery.md
- docs/includes/file-get-started-excel-vue.md
- docs/includes/file-get-started-powerpoint.md
- docs/includes/file-get-started-project.md
- docs/includes/file-get-started-word.md
- docs/includes/word-tutorial-insert-text.md
- docs/testing/sideload-office-add-ins-for-testing.md
The content implied that you can debug In Office online using the web. This isn't possible, or recommended. I updated the content to be clearer so that developers will find the guidance for debugging using the browser tools.
> Updating Office online debugging content

- docs/develop/create-and-debug-office-add-ins-in-visual-studio.md
Addresses issues #222 and #324.
**_Note_**: Given the scope of changes I've made to this article, it's probably easiest to review by looking at the updated article on the staging site (instead of just looking at the file diff in this PR): https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/create-and-debug-office-add-ins-in-visual-studio?branch=kb-update-VS-article-222#debug-your-add-in.
> Update 'Create and debug Office Add-in in Visual Studio' article

- docs/develop/add-ins-with-angular2.md
Added a short section that describes the benefits of using Angular's AOT compiler
> Add section for Angular’s AOT compiler

- docs/design/add-in-commands.md
- docs/develop/add-in-manifests.md
- docs/develop/automatically-open-a-task-pane-with-a-document.md
- docs/develop/localization.md
- docs/excel/excel-add-ins-error-handling.md
- docs/includes/excel-tutorial-create-chart.md
- docs/includes/excel-tutorial-create-table.md
- docs/includes/excel-tutorial-filter-and-sort-table.md
- docs/includes/excel-tutorial-freeze-header.md
- docs/includes/excel-tutorial-open-dialog.md
- docs/includes/word-tutorial-content-control.md
- docs/includes/word-tutorial-insert-image-html-table.md
- docs/includes/word-tutorial-insert-text.md
- docs/includes/word-tutorial-replace-text.md
- docs/overview/office-add-in-availability.md
- docs/overview/schemas/mail/MailAppVersionOverridesV1_0.xsd
- docs/overview/schemas/mail/MailAppVersionOverridesV1_1.xsd
- docs/overview/schemas/taskpane/MailAppVersionOverridesV1_0.xsd
- docs/overview/schemas/taskpane/TaskPaneAppVersionOverridesV1_0.xsd
- docs/reference/manifest/action.md
- docs/reference/objectmodel/requirement-set-1.5/office.context.mailbox.md
- docs/reference/objectmodel/requirement-set-1.5/outlook-requirement-set-1.5.md
- docs/reference/objectmodel/requirement-set-1.6/office.context.mailbox.md
- docs/testing/debug-office-add-ins-on-ipad-and-mac.md
- docs/word/create-better-add-ins-for-word-with-office-open-xml.md
Update "taskpane" to "task pane" where applicable. Also took opportunity to clean up some whitespace and typos in those files.
> Clean up taskpane

- docs/reference/requirement-sets/word-api-requirement-sets.md
> Fix issue in Word req. sets topic

- docs/develop/add-in-manifests.md
> Update info about HighResolutionIconUrl in manifest article

- docs/develop/add-in-manifests.md
- docs/develop/manifest-element-ordering.md
- docs/toc.yml
Eventually we want to link to the new article from all the manifest reference topics, but that is out-of-scope for this PR.
> new article on ordering of manifest elements

- docs/includes/excel-tutorial-open-dialog.md
The repo that contains the starting state of the tutorial is also be updated to use onReady.
> update Excel tutorial to use onReady

- docs/includes/excel-tutorial-open-dialog.md
Reverts OfficeDev/office-js-docs-pr#566
> Revert "update Excel tutorial to use onReady"

- docs/reference/javascript-api-for-office-error-codes.md
> Merge to live

- docs/excel/excel-add-ins-advanced-concepts.md
- docs/excel/excel-add-ins-workbooks.md
- docs/excel/excel-add-ins-worksheets.md
- docs/toc.yml
This article discusses the Excel JavaScript API's workbook object. It handles the documentation requests for workbook creation, calculations, and protection. It also adds a protection section to the worksheet article.
I'm open to suggestions for layout, additional content needs, or other issues. Thanks!
> Excel Workbook Article

- docs/reference/manifest/rule.md
> Fix typo in manifest docs

- docs/excel/custom-functions-best-practices.md
- docs/excel/custom-functions-json.md
1. Changing title according to feedback from Reeza 
2. Documentation write up for CF optional parameters
> Custom Functions Optional Parameters

- README.md
Clarifying the purpose of the repo and the types of issues to file here.
> [GitHub] (Readme) Update readme with issue advice

- docs/concepts/resource-limits-and-performance-optimization.md
- docs/excel/performance.md
This adds a section about `Application.suspendScreenUpdatingUntilNextSync()`. I also did minor organizational changes to the Performance article.
> [Excel] (performance) suspendScreenUpdatingUntilNextSync method

- docs/reference/manifest/appdomain.md
- docs/reference/manifest/appdomains.md
Please see [internal task](https://office.visualstudio.com/OC/_workitems/edit/2725287) for more details.
> AppDomain needs protocol

- docs/excel/excel-add-ins-workbooks.md
This adds a small section on custom XML parts to the Workbook article. It also converts tabs to spaces in the article's code samples.
> [excel] (Custom XML) Adding section about custom XML parts

- docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.1/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.2/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.3/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.4/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.6/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item.md
[Internal task](https://office.visualstudio.com/OC/_workitems/edit/2750372)
> Remove attachmentId char limit

- docs/excel/excel-add-ins-multiple-ranges.md
- docs/excel/excel-add-ins-ranges-advanced.md
Also changing `const` to `var` in the RangeAreas snippets.
> [excel] (RangeAreas) Linking to the RangeAreas article from the advanced ranges article

- docs/powerpoint/use-document-themes-in-your-powerpoint-add-ins.md
- docs/project/create-your-first-task-pane-add-in-for-project-by-using-a-text-editor.md
- docs/project/project-add-ins.md
- docs/word/create-better-add-ins-for-word-with-office-open-xml.md
Updates to articles to move them from VS 2015 to VS 2017
> Updates for VS 2017 version

- docs/develop/dialog-api-in-office-add-ins.md
> [Dialog API] (sample code) - Added a note about the showNotification function

- docs/develop/create-sso-office-add-ins-nodejs.md
I updated the dependencies in the SSO sample on GitHub, and needed to make a few code changes as a result. I added these changes to the walkthrough.
> Code updates to NodeJS SSO walkthrough

- docs/develop/add-in-manifests.md
> [Common] (manifest) Fix issues with sample XML manifests

- docs/excel/excel-add-ins-ranges.md
- docs/excel/excel-add-ins-worksheets.md
This adds sections about the upcoming string searching methods of Range and Worksheet. It also cleans up the spacing in the Worksheet article.
> [excel] (Range, Worksheet) Adding information about preview find methods

- docs/excel/custom-functions-best-practices.md
- docs/excel/custom-functions-overview.md
We updated everything for the new template that Adam had but now that we rolled back and are holding Adam's template until later in Feb, I'm updating docs to have the correct filenames with yo office
> [Excel](Custom Functions) Changing filenames so they match rollback

- docs/tutorials/excel-tutorial-create-custom-functions.md
Various updates to improve readability and ensure follows latest template changes.
> [Excel] (Custom Functions) Tutorial updates for next publish (associate changes)

- docs/excel/excel-add-ins-workbooks.md
Also cleaning up a couple typos and extra spaces.
> Adding section about inserting workbooks

- docs/excel/custom-functions-best-practices.md
- docs/excel/custom-functions-changelog.md
- docs/excel/custom-functions-json.md
- docs/excel/custom-functions-overview.md
- docs/excel/custom-functions-runtime.md
- docs/toc.yml
- docs/tutorials/excel-tutorial-create-custom-functions.md
Changes related to changing binding to the Associate method, and some other updates
- splitting out changelog
- tutorial updates.
> [Excel] (custom functions) Associate and related updates

- docs/develop/loading-the-dom-and-runtime-environment.md
- docs/tutorials/excel-tutorial.md
The bug fix that was holding this up was finally moved to prod this week.
> Onready updates

- docs/reference/manifest/versionoverrides.md
> [Manifest] (typo) - Fix issue with example in VersionOverrides element article.

- docs/powerpoint/powerpoint-add-ins.md
Adding a description of the new `createPresentation` method to the PowerPoint article. Also cleaning up a couple spacing warnings.
> [powerpoint] (Presentation) Adding createPresentation section

- docs/tutorials/excel-tutorial-create-custom-functions.md
Adding a bug to address this customer issue: https://github.com/OfficeDev/Excel-Custom-Functions/issues/87
> Add note for bug impacting tutorial

- docs/testing/debug-office-add-ins-on-ipad-and-mac.md
Related issue: https://github.com/OfficeDev/office-js/issues/127
> (Mac) Update debug article

- docs/docfx.json
- docs/index.yml
- docs/quickstarts/excel-quickstart-angular.md
- docs/quickstarts/excel-quickstart-jquery.md
- docs/quickstarts/excel-quickstart-react.md
- docs/quickstarts/excel-quickstart-vue.md
- docs/quickstarts/onenote-quickstart.md
- docs/quickstarts/powerpoint-quickstart.md
- docs/quickstarts/project-quickstart.md
- docs/quickstarts/word-quickstart.md
- docs/reference/overview/excel-add-ins-reference-overview.md
- docs/reference/overview/onenote-add-ins-javascript-reference.md
- docs/reference/overview/visio-javascript-reference-overview.md
- docs/reference/overview/word-add-ins-reference-overview.md
- docs/reference/requirement-sets/add-in-commands-requirement-sets.md
- docs/reference/requirement-sets/dialog-api-requirement-sets.md
- docs/reference/requirement-sets/excel-api-requirement-sets.md
- docs/reference/requirement-sets/identity-api-requirement-sets.md
- docs/reference/requirement-sets/office-add-in-requirement-sets.md
- docs/reference/requirement-sets/onenote-api-requirement-sets.md
- docs/reference/requirement-sets/outlook-api-requirement-sets.md
- docs/reference/requirement-sets/powerpoint-and-project-note.md
- docs/reference/requirement-sets/word-api-requirement-sets.md
- docs/tutorials/excel-tutorial-create-custom-functions.md
- docs/tutorials/excel-tutorial.md
- docs/tutorials/powerpoint-tutorial.md
- docs/tutorials/word-tutorial.md
This PR updates metadata attribute values to improve our ability to generate reports about this doc set. It does the following: 
- sets metadata attribute **ms.technology** to `add-ins` for all files in this doc set (by using **globalMetadata** config setting in **docfx.json**)
- sets metadata attribute **ms.prod** to the appropriate value in all files (by using **fileMetadata** config setting in **docfx.json** where feasible, and otherwise by setting this metadata attribute value in individual .md files)
**ms.prod** values set at the folder-level for the following folders:
| folder | **ms.prod** value |
|:-------|:----------------------|
|concepts |  non-product-specific|
|design | non-product-specific|
|develop | non-product-specific|
|excel | excel|
|onenote | onenote|
|overview | …
> [Admin] (docs metadata) Update metadata attribute values for docs.

- docs/tutorials/excel-tutorial-create-custom-functions.md
Issue: https://github.com/OfficeDev/Excel-Custom-Functions/issues/112
Proposal: Update not to put runtime logging info inline of tutorial
> [Excel] (Custom Functions) Addressing feedback from Customer Issue

- docs/reference/requirement-sets/identity-api-requirement-sets.md
Also fixes this issue in another repo: https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO/issues/26
> [All hosts] (auth) clarify SSO support

- docs/excel/custom-functions-requirements.md
This reverts commit 1dd87dd82510d3c1e3fd2e34ccb0e545a3355727.
> Revert "Update custom-functions-requirements.md"

- docs/excel/custom-functions-best-practices.md
Add note in the our troubleshooting docs
> [Excel] (Custom Functions) Update custom-functions-best-practices.md

- docs/design/add-in-icons.md
Fixes issue https://github.com/OfficeDev/office-js-docs-pr/issues/798
> [All hosts] (design) clarify intention of icon color text

- docs/reference/manifest/extensionpoint.md
> [Manifest] - (typo) Fix broken link

- docs/overview/office-add-in-availability.md
**Issue**: Project section not showing up correctly (see image). Also moved/copied note to applicable tables.
> Fix formatting

- docs/excel/custom-functions-authentication.md
- docs/toc.yml
This is to start to link in PnP samples associated with content in custom functions. They will go in a separate "solution guidance" node. There will be a few more of these down the road. Also some parts of the sample are pulled in to help explain how to store a token value.
> [Excel] (custom functions) Creating solution guidance section

- docs/excel/custom-functions-best-practices.md
- docs/excel/custom-functions-errors.md
- docs/excel/custom-functions-overview.md
- docs/toc.yml
Separating out error handling into it's own article. Content should be the same as it was!
> [Excel] (Custom functions) Error handling

- docs/excel/custom-functions-troubleshooting.md
- docs/toc.yml
This article is pretty short compared now but there will definitely be more to add as things get more solid come GA (errors, etc). Let me know if there are sections that should be added for a v1!
> [Excel] (Custom functions) Troubleshooting article

- docs/excel/custom-functions-best-practices.md
- docs/excel/custom-functions-errors.md
- docs/excel/custom-functions-runtime.md
I changed the sample we had for AsyncStorage to be one from the PnP example.
> [Excel] (Custom functions) Updating samples to be only JS (not TS)

- docs/reference/manifest/appdomain.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/835
> [All hosts] (manifest) Add note about closing slash in AppDomain element

- docs/excel/excel-add-ins-pivottables.md
I'll welcome any phrasing or placement suggestions.
> [excel] (PivotTable) Adding note about Power Pivot not being supported

- docs/excel/custom-functions-troubleshooting.md
New build dropped this week with the error change name :)
> #GETTING_DATA is now #BUSY!

- docs/excel/custom-functions-web-reqs.md
> [Excel] (Custom Functions) Add sample link to XHR

- docs/concepts/privacy-and-security.md
This is in response to #821. It specifies the settings an admin would adjust using the Office Deployment Tool to control add-in access.
> [security] (Registry Settings) Adding section for relevant ODT settings

- docs/reference/manifest/supportssharedfolders.md
Related to issue https://github.com/OfficeDev/office-js-docs-pr/issues/863
> [Outlook] (manifest) Add link to preview requirement set

- docs/reference/manifest/supportssharedfolders.md
Addresses issue https://github.com/OfficeDev/office-js-docs-pr/issues/863.
> [Outlook] (manifest) Update ordering of SupportsSharedFolders element

- docs/excel/excel-add-ins-events.md
I'm also cleaning up the ordering. Alphabetical makes the most sense to me.
> [excel] (Events) Adding events that are currently in preview

- docs/includes/file-get-the-whole-document-from-an-add-in-for-powerpoint-or-word.md
Clarification as requested by: https://github.com/OfficeDev/office-js-docs-pr/issues/861
> [PowerPoint Word] (file slicing) clarify what server must do

- docs/reference/requirement-sets/identity-api-requirement-sets.md
- docs/reference/requirement-sets/office-add-in-requirement-sets.md
[Staging site](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/office-add-in-requirement-sets?branch=AlexJ-ReqSet)
This change breaks up the large table specifying requirement sets for Common API members into smaller subsections. This allows us to link to those subsections from other parts of the documentation.
> [common] (Requirement Sets) Clean up common requirement set table

- docs/develop/create-and-debug-office-add-ins-in-visual-studio.md
Added a comment about the for the multi-factor auth setting in the Outlook project
Added a comment about a prompt for the localhost self-signed certificate
Added a Note about the prompt that may occur for the loopback setting
> Updated the create and debug office add-ins doc

- docs/reference/requirement-sets/office-add-in-requirement-sets.md
These entries were conflating coercion types with method names.
> [common] (Requirement Sets) Removing inaccurate method names

- docs/reference/requirement-sets/office-add-in-requirement-sets.md
Adding the missing methods from the Settings Common API to the requirement set.
> [common] (Requirement Sets) Filling out Settings requirement set

- docs/develop/create-sso-office-add-ins-aspnet.md
- docs/develop/create-sso-office-add-ins-nodejs.md
The new registration procedure has them copy the tenancy ID. This is where they use it.
> Sso walkthroughs

- docs/publish/centralized-deployment.md
Note Mac support based on [Centralized Deployment article](https://docs.microsoft.com/en-us/office365/admin/manage/centralized-deployment-of-add-ins#client-requirements)
> [All] (Centralized deployment) Note Mac supported

- docs/excel/excel-add-ins-tables.md
- docs/excel/excel-add-ins-worksheets.md
This adds sections to the [table](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-tables?branch=AlexJ-Autofilter#autofilter) and [worksheet](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-worksheets?branch=AlexJ-Autofilter#filter-data) articles (links are to the staging site).
> [excel] (Table, Worksheet) Describing the AutoFilter APIs

- docs/excel/custom-functions-troubleshooting.md
Added the "local loopback exception" info to our troubleshooting article. I'm not sure if there are other instances in which this happens - it might be worth talking to Juan quickly on this because I know he didn't hit a specific error.
> [Excel] (Custom Functions) Added link to local loopback exception article

- docs/reference/requirement-sets/office-add-in-requirement-sets.md
Currently GetFileAsync compressedFile doesnt support iOS. so update this document
> Update the description for compressedFile

- docs/excel/excel-add-ins-worksheets.md
This section discusses the new page layout and print setting APIs, currently in preview.
> [excel] [Worksheet] Adding section about page layout APIs

- docs/excel/excel-add-ins-core-concepts.md
This update is in response to [this issue](https://github.com/OfficeDev/office-js-docs-reference/issues/354).
This PR also cleans up some minor formatting and code styling in the article.
> [excel] (Online) Adding explict limits for Excel Online payload size

- docs/excel/custom-functions-batching.md
- docs/toc.yml
This is an article that shows how to create a batching pattern in your web add-in. You can batch up multiple custom function calls into a single batch that is passed in one network call to a remote service.
> [Excel] (custom functions) adding batching article

- docs/excel/custom-functions-json-autogeneration.md
- docs/excel/custom-functions-overview.md
- docs/excel/custom-functions-web-reqs.md
- docs/excel/excel-add-ins-worksheets.md
- docs/toc.yml
1. Takes out JSON examples in other topics
2. Updates optional params info to have a note about passing in null.
> [Excel] (Custom functions) Updates to Autogeneration topic

- docs/design/add-in-commands.md
- docs/overview/office-add-in-availability.md
Addresses issue https://github.com/OfficeDev/office-js-docs-pr/issues/906.
> [All] Note versions as one-time purchase

- docs/reference/manifest/customtab.md
> [Manifest] Remove 'Control' as a child element of 'CustomTab'.

- docs/develop/add-ins-with-angular2.md
- docs/develop/referencing-the-javascript-api-for-office-library-from-its-cdn.md
- docs/includes/quickstart-yo-start-server.md
- docs/quickstarts/excel-custom-functions-quickstart.md
- docs/quickstarts/excel-quickstart-angular.md
- docs/quickstarts/excel-quickstart-jquery.md
- docs/quickstarts/excel-quickstart-react.md
- docs/quickstarts/excel-quickstart-vue.md
- docs/quickstarts/onenote-quickstart.md
- docs/quickstarts/powerpoint-quickstart.md
- docs/quickstarts/project-quickstart.md
- docs/quickstarts/word-quickstart.md
- docs/testing/troubleshoot-manifest.md
- docs/tutorials/excel-tutorial-create-custom-functions.md
Please note that I intentionally didn't update ms.date in any of these articles, since this isn't a substantive change.
> [Admin] Update language designation for command line code blocks.

- docs/excel/excel-add-ins-ranges.md
change the sample description on line 21 to match the address range shown in the code sample on line 26
> fix range B5 -> C5 to match example code

- docs/excel/custom-functions-naming.md
Misc recommendations for naming page per Linda's suggestions a while ago
> [Excel] (Custom functions) Naming updates

- docs/excel/excel-add-ins-events.md
- docs/excel/excel-add-ins-multiple-ranges.md
- docs/excel/excel-add-ins-pivottables.md
- docs/excel/excel-add-ins-ranges-advanced.md
- docs/excel/excel-add-ins-ranges.md
- docs/excel/excel-add-ins-shapes.md
- docs/excel/excel-add-ins-tables.md
- docs/excel/excel-add-ins-workbooks.md
- docs/excel/excel-add-ins-worksheets.md
- docs/excel/performance.md
- docs/reference/requirement-sets/excel-api-requirement-sets.md
This removes any preview tags from API descriptions going out with the 1.9 release.
> [excel] (ExcelAPI 1.9) Removing preview tags for Excel 1.9

- docs/excel/custom-functions-dialog.md
Minor changes to Dialog sample to reflect new template and d.ts info
> [Excel] (Custom functions) Minor updates to Dialog page RE: new d.ts

- docs/excel/make-custom-functions-compatible-with-xll-udf.md
> Clarification: XLL Compat functions

- docs/reference/requirement-sets/add-in-commands-requirement-sets.md
- docs/reference/requirement-sets/dialog-api-requirement-sets.md
- docs/reference/requirement-sets/identity-api-requirement-sets.md
- docs/reference/requirement-sets/office-add-in-requirement-sets.md
> [All] Note one-time purchase

- docs/reference/requirement-sets/excel-api-requirement-sets.md
> [excel] (Requirement Set 1.9] Adding links to conceptual content

- docs/includes/excel-custom-functions-note.md
* GA branch with preview mentions but doesn't have latest bug bash changes
* XLL compat preview info
* link fixes
* link fixes
* add preview for xll requirements
* quote
* update note
> Build 2019: merge to live!

- docs/develop/troubleshoot-sso-in-office-add-ins.md
- docs/excel/custom-functions-debugging.md
- docs/testing/sideload-office-add-ins-for-testing.md
> Policheck branding fix

- docs/develop/troubleshoot-sso-in-office-add-ins.md
- docs/excel/custom-functions-debugging.md
- docs/testing/sideload-office-add-ins-for-testing.md
> Build 2019: merge to live

- docs/reference/requirement-sets/excel-api-requirement-sets.md
[staging branch](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets?branch=AlexJ-ExcelPreview)
Here's the Excel APIs currently in preview, according to the latest Definitely Typed entries. The table was generated with the [What's New](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/tools/WhatsNew.ts) tool.
> [excel] (Preview APIs) What's New

- docs/reference/manifest/supertip.md
Addresses issue https://github.com/OfficeDev/office-js-docs-pr/issues/902.
> [Manifest] (Outlook) Note restricted support for Supertip Description

- docs/concepts/requirements-for-running-office-add-ins.md
Also, since IE11 is the last version, I removed "or later".
> [All] (browser) IE11 or Edge

- docs/testing/debug-add-ins-in-office-online.md
Fix for Issue: [1016](https://github.com/OfficeDev/office-js-docs-pr/issues/1016)
> [All hosts] (testing) guidance about bypassing cert warnings, issue 1016

- docs/reference/manifest/iconurl.md
> [Manifest] (clarification) Specify that setting IconUrl value at runtime is not supported.

- docs/includes/mac-cache-folders.md
- docs/testing/debug-office-add-ins-on-ipad-and-mac.md
- docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md
- docs/testing/testing-and-troubleshooting.md
- docs/testing/troubleshoot-manifest.md
- docs/tutorials/excel-tutorial.md
> [All] (clearing cache) Update guidance about how to clear the Office Cache on a Mac.

- docs/includes/quickstart-yo-prerequisites.md
> [All] (Yo Office prerequisities) Update list of prerequisites for Yo Office to include Git.

- docs/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog.md
This updates the instructions to match the latest UI when creating and publishing Office Add-ins to a SharePoint catalog on Office 365.
> [All](SharePoint catalog) Updates to match latest UI

- docs/includes/quickstart-yo-start-server-excel.md
- docs/quickstarts/excel-custom-functions-quickstart.md
- docs/quickstarts/onenote-quickstart.md
- docs/quickstarts/powerpoint-quickstart.md
- docs/quickstarts/project-quickstart.md
- docs/quickstarts/word-quickstart.md
- docs/tutorials/excel-tutorial-create-custom-functions.md
@ElizabethSamuel-MSFT here's a PR into your branch with the changes we discussed. If it looks good, please go ahead and merge into your branch (and subsequently make any updates there that you deem necessary) -- then I'll review/approve your outstanding PR. Thanks again for taking on this work item!
> Update certificate guidance in quick starts and tutorials.

- docs/includes/quickstart-yo-start-server-excel.md
- docs/quickstarts/excel-custom-functions-quickstart.md
- docs/quickstarts/onenote-quickstart.md
- docs/quickstarts/powerpoint-quickstart.md
- docs/quickstarts/project-quickstart.md
- docs/quickstarts/word-quickstart.md
- docs/tutorials/excel-tutorial-create-custom-functions.md
Should address server error issue raised in https://github.com/OfficeDev/office-js-docs-pr/issues/978.
> [All] (Mac) Add note about npm run dev-server

- docs/develop/specify-office-hosts-and-api-requirements.md
- docs/reference/requirement-sets/onenote-api-requirement-sets.md
- docs/reference/requirement-sets/outlook-api-requirement-sets.md
> [Outlook] (isSetSupported) Users can check for Mailbox support

- docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.3/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.4/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.6/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item.md
See feedback on PR https://github.com/OfficeDev/office-js-docs-pr/pull/1045.
> [Outlook] (Mac) Update saveAsync note based on feedback

- docs/excel/custom-functions-naming.md
Jakob asked for some guidance on naming streaming functions as a GH issue. So, added a tiny blurb to address.
> [Excel] (Custom functions) Streaming guidance

- docs/concepts/add-in-development-lifecycle.md
- docs/concepts/privacy-and-security.md
- docs/concepts/requirements-for-running-office-add-ins.md
- docs/develop/loading-the-dom-and-runtime-environment.md
- docs/includes/grant-admin-consent-to-an-add-in-include.md
- docs/project/create-a-project-add-in-that-uses-rest-with-an-on-premises-odata-service.md
- docs/project/project-add-ins.md
- docs/publish/centralized-deployment.md
- docs/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog.md
- docs/publish/publish.md
- docs/testing/debug-add-ins-in-office-online.md
- docs/toc.yml
These are updates to the UI instructions for how to create an app catalog, and how to register an Office add-in for the on-premises SharePoint Server scenario.
> [All](SharePoint) Update app catalog instructions for on-premise

- docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md
Fixes sample bug noted in issue https://github.com/OfficeDev/outlook-dev-docs/issues/604.
> [Outlook] (sample) Update for getAttachmentContentAsync

- docs/excel/custom-functions-authentication.md
> [Typo] Fix broken link.

- docs/tutorials/excel-tutorial-create-custom-functions.md
The stock API changed and users need to get an account. Added a note clarifying this with correct API call.
> [Exchange](custom functions) update for stock api change

- docs/overview/explore-with-script-lab.md
@ElizabethSamuel-MSFT sorry for the delay on this! This PR contains the changes we discussed on Friday. Please feel free to merge it into your branch, then make any subsequent changes you deem necessary, and ping me whenever you're ready for me to do a final review of your PR (#1084). Thanks!
- updates ms.date
- simplifies headings to "Key features" and "Supported clients" (no need to mention Script Lab in each section heading, since the entire article is about Script Lab)
- moves info about contributing new snippets out of the `What is Script Lab` section into the `Next steps` section and removed TIP about Office Insider program from the `What is Script Lab` section (since this info is more relevant to the `Key features` section)
- updates the `Key features` section as we discussed -- …
> Suggested updates to elizs-script-lab-features PR

- docs/excel/custom-functions-web-reqs.md
> [Excel] (Custom Functions) Update IEX request URL and add info about acquiring a token.

- docs/develop/persisting-add-in-state-and-settings.md
Typographical error in the markdown
> Remove extra closing parentheses

- docs/excel/custom-functions-json-autogeneration.md
Related to PR https://github.com/OfficeDev/office-js-docs-pr/pull/1138.
> [Excel] (custom functions) Minor tweaks

- docs/testing/debug-add-ins-using-f12-developer-tools-on-windows-10.md
- docs/toc.yml
Split the debugging on Win 10 article into separate sections for IE and Edge. Resolves https://github.com/OfficeDev/office-js-docs-pr/issues/1145
> Edge debugging

- docs/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog.md
This updates the link for where to find policy info to manage the SharePoint catalog.
> [Office] Updated link to admin policy info

- docs/testing/troubleshoot-manifest.md
Reworked content in article for validation. Now it only mentions how to use office-toolbox package for validation. Both for yo office, and for custom projects.
Some other minor cleanup work was done as well.
> [All] updating validation tool info

- docs/develop/convert-javascript-to-typescript.md
> [All] (convert Visual Studio project to TypeScript) Updated instructions

- docs/overview/explore-with-script-lab.md
Removes locale from 3 hyperlinks, per review suggestions in #1182.
> [Admin] Fix typos.

- docs/design/using-motion-office-addins.md
Addresses issue https://github.com/OfficeDev/office-js-docs-pr/issues/1189.
> [Admin] (design) Fix link to animation guidelines

- docs/reference/requirement-sets/excel-api-1-1-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-2-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-3-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-4-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-5-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-6-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-7-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-8-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-9-requirement-set.md
- docs/reference/requirement-sets/image-coercion-requirement-sets.md
> [excel] (Requirement Sets) Removing load option and update data table entries

- docs/excel/custom-functions-dialog.md
Fixed typo w/ OfficeRuntime.displayWebDialog
> Fixed typo w/ OfficeRuntime.displayWebDialog

- docs/develop/manifest-element-ordering.md
We will be adding a link to this page to every manifest reference page, but that will be a separate PR.
> Manifest element ordering

- docs/excel/excel-add-ins-ranges-advanced.md
I think this makes the behavior more clear.
> [excel] (Range) Clarify copyFrom example

- docs/reference/objectmodel/preview-requirement-set/office.md
- docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md
- docs/reference/objectmodel/requirement-set-1.1/office.md
- docs/reference/objectmodel/requirement-set-1.2/office.md
- docs/reference/objectmodel/requirement-set-1.3/office.md
- docs/reference/objectmodel/requirement-set-1.4/office.md
- docs/reference/objectmodel/requirement-set-1.5/office.md
- docs/reference/objectmodel/requirement-set-1.6/office.md
- docs/reference/objectmodel/requirement-set-1.7/office.md
- docs/reference/requirement-sets/outlook-api-requirement-sets.md
Note production and preview CDN links. Also some minor formatting and update preview MailboxEnums to link to top enum.
> [Outlook] CDN links

- docs/reference/manifest/action.md
This fixes internal bug OC 3512687
> [All Hosts] (manifest) clarify Title element in Action element

- docs/reference/manifest/authorization.md
- docs/reference/manifest/authorizations.md
- docs/reference/manifest/scopes.md
- docs/reference/manifest/versionoverrides.md
- docs/reference/manifest/webapplicationinfo.md
- docs/toc.yml
This fixes internal item OC 3468497
The TOC changes in include adding EqivalentAddins and EquivalentAddin. Those articles were already published. They just weren't in the TOC.
> doc new manifest elements and update toc

- docs/develop/create-sso-office-add-ins-nodejs.md
@abidrahman-MSFT went through this tutorial recently and encountered difficulties after missing this note in question. This better highlights the information to developers and reduces the number of links they have to follow to find their information.
> [SSO] (Certifiates) Better emphasis on self-signing certificate note

- docs/docfx.json
- docs/excel/custom-functions-overview.md
- docs/excel/excel-add-ins-overview.md
- docs/onenote/onenote-add-ins-programming-overview.md
- docs/overview/explore-with-script-lab.md
- docs/overview/office-add-ins.md
- docs/powerpoint/powerpoint-add-ins.md
- docs/project/project-add-ins.md
- docs/reference/overview/visio-javascript-reference-overview.md
- docs/tutorials/excel-tutorial-create-custom-functions.md
- docs/tutorials/excel-tutorial.md
- docs/tutorials/powerpoint-tutorial.md
- docs/tutorials/word-tutorial.md
- docs/word/word-add-ins-programming-overview.md
This PR updates metadata attribute values for `ms.topic` (for all articles) and `scenarios` (in just overview, quickstart, and tutorial articles). Some settings are specified by folder in **docfx.json** (where all files in a given folder should have the same attribute value) and other settings are specified in individual files (in cases where only some file(s) in a given folder need the metadata attribute/value).
> [Admin] (metadata updates) Specify values for metadata attributes ms.topic and scenarios.

- docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.2/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.3/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.4/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.6/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item.md
Helps address issue https://github.com/OfficeDev/office-js-docs-pr/issues/1322.
> [Outlook] GetSelectedDataAsync - Update minimum perm level

- docs/excel/excel-add-ins-events.md
> [excel] (Events) Adding warning note about onSelectionChanged

- docs/excel/excel-add-ins-workbooks.md
Documentation for this issue: https://github.com/OfficeDev/office-js/issues/781
> [excel] (Workbook) Adding platform support note for insert worksheets

- .openpublishing.publish.config.json
- docs/excel/excel-add-ins-comments.md
- docs/excel/excel-add-ins-events.md
- docs/excel/excel-add-ins-pivottables.md
- docs/excel/excel-add-ins-ranges-advanced.md
- docs/excel/excel-add-ins-tables.md
- docs/excel/excel-add-ins-worksheets.md
- docs/reference/requirement-sets/excel-api-1-10-requirement-set.md
- docs/reference/requirement-sets/excel-api-requirement-sets.md
- docs/reference/requirement-sets/excel-preview-apis.md
- docs/toc.yml
Many APIs graduated from preview into the Excel 1.10 requirement set. This updates the documentation for that transition.
> [exce] (ExcelApi 1.10) Documenting the new release

- docs/develop/common-coding-issues.md
- docs/toc.yml
This documents some confusing edge-case situations our developers may encounter. I'm open to feedback on the structure and phrasing of the article. I'll also welcome additional scenarios to document.
Note that I'm still waiting on subject-matter expertise on the event handler issue. I can't figure out how to remove events handlers under any circumstance. I'll add the proper advice for developers once I learn it.
> [all] (Programming Guidance) Common coding issues and unexpected platform behaviors

- docs/testing/troubleshoot-manifest.md
Added correct name of "RuntimeLogging" for creating registry key.
> [Office] Add correct key name for runtime logging

- docs/testing/troubleshoot-manifest.md
Addresses [#788](https://github.com/OfficeDev/office-js-docs-pr/issues/788)
> [Office Add-ins] Adds npx runtime logging commands

- docs/excel/custom-functions-debugging.md
- docs/excel/custom-functions-errors.md
This article documents how to return built in errors like `#N/A` from your custom function.
> [Excel](custom functions) error handling preview

- docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.1/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.2/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.3/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.4/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.6/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.8/office.context.mailbox.item.md
Addresses docs part of https://github.com/OfficeDev/office-js-docs-pr/issues/1329.
> [Outlook] (itemId) Link to EWS item ID docs

- docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.2/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.3/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.4/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.6/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.8/office.context.mailbox.item.md
While issue https://github.com/OfficeDev/office-js/issues/800 is in the backlog, adding note about OWA bug.
> [Outlook] (getSelectedDataAsync) Add note about OWA bug

- docs/powerpoint/powerpoint-add-ins.md
Updating based on info from [SOT](https://github.com/OfficeDev/Office-Js-Requirement-Sets/blob/master/mapping/requirements_officejs.json):
> [PowerPoint] (typo) Note iPad support instead of iOS

- docs/overview/office-add-in-availability.md
- docs/reference/requirement-sets/excel-api-online-requirement-set.md
- docs/reference/requirement-sets/excel-api-requirement-sets.md
- docs/toc.yml
Adding a page to describe the upcoming ExcelApi Online requirement set. This explains its function and what developers can expect.
> [excel] (Requirement Sets) ExcelApi Online requirement set page

- docs/develop/create-sso-office-add-ins-nodejs.md
* update sso node walkthrough with new version
* [All hosts] (auth) updating Node.js SSO walkthrough
* remove language from URL
* Update docs/develop/create-sso-office-add-ins-nodejs.md
Co-Authored-By: Elizabeth Samuel <elizs@microsoft.com>
* Update docs/develop/create-sso-office-add-ins-nodejs.md
Co-Authored-By: Elizabeth Samuel <elizs@microsoft.com>
* Update docs/develop/create-sso-office-add-ins-nodejs.md
Co-Authored-By: Elizabeth Samuel <elizs@microsoft.com>
* Update docs/develop/create-sso-office-add-ins-nodejs.md
Co-Authored-By: Elizabeth Samuel <elizs@microsoft.com>
* Update docs/develop/create-sso-office-add-ins-nodejs.md
Co-Authored-By: Elizabeth Samuel <elizs@microsoft.com>
* Update docs/develop/create-sso-office-add-ins-nodejs.md
Co-Authored-By: Elizabeth Samuel …
> Sso node walkthrough (#1442)

- docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.2/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.3/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.4/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.6/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item.md
- docs/reference/objectmodel/requirement-set-1.8/office.context.mailbox.item.md
OWA bug (https://github.com/OfficeDev/office-js/issues/800) was fixed.
> [Outlook] (getSelectedDataAsync) Remove OWA bug note and workaround

- docs/includes/mac-cache-folders.md
- docs/testing/debug-office-add-ins-on-ipad-and-mac.md
- docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md
- docs/testing/testing-and-troubleshooting.md
- docs/testing/troubleshoot-manifest.md
- docs/tutorials/excel-tutorial.md
> [All Hosts] (cache) Add more info about clearing cache on Mac.

- docs/reference/manifest/group.md
> [All Hosts] Update manifest reference article to add link to child element article.

- docs/develop/common-coding-issues.md
Based off of this sample from @wandyezj: https://gist.github.com/wandyezj/d48859d4d3eae6cdcf71eb9447b36879
> [Rich API] (Events) Adding an explanation about how to remove event handlers

- docs/develop/auth-with-office-dialog-api.md
- docs/develop/authorize-to-microsoft-graph-without-sso.md
Reverts OfficeDev/office-js-docs-pr#1474
> Revert "add links to new sample"

- docs/concepts/privacy-and-security.md
- docs/develop/common-coding-issues.md
> [Admin] Fix bad links.

- docs/reference/requirement-sets/excel-api-online-requirement-set.md
Based on this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40830
> [excel] (Requirement Sets) Adding newly released ExcelApiOnline 1.1 APIs

- docs/concepts/browsers-used-by-office-web-add-ins.md
- docs/develop/create-and-debug-office-add-ins-in-visual-studio.md
- docs/includes/enable-debugging-on-edge-devtools.md
- docs/testing/debug-add-ins-using-f12-developer-tools-on-windows-10.md
* adding ui-less code debug info
* removing out of date note
* update publish date
* moved edge devtools debug info to include file
* update publish date
* add section link
* updated to be Edge specific
* date update
* minor change
* add browser info
* typo fix
> [all] debugging ui-less code with Edge DevTools (#1493)

- docs/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial.md
The sentence about using onCalculated is not correct at this time.
> [Excel](custom functions) minor update

- docs/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial.md
> [Excel](custom functions) removing incorrect sentence. (#1501)

- .openpublishing.redirection.json
You can use this URL to verify that the redirect is now working (in this branch):
https://review.docs.microsoft.com/office/dev/add-ins/overview/index?branch=kb-fix-redirect
> [Admin] (redirect) Fix invalid redirect for recently deprecated page.

- docs/reference/requirement-sets/excel-preview-apis.md
This PR updates the API list for the ExcelApi Preview requirement set. The content comes from DefinitelyTyped/office-js-preview.
> [excel] (Preview requirement set) Updating Excel preview requirement set list

- docs/develop/common-coding-issues.md
> [excel] (Coding patterns) Removing 'JSON struct' term

- docs/develop/add-in-manifests.md
- docs/excel/custom-functions-json.md
- docs/excel/custom-functions-naming.md
- docs/excel/custom-functions-overview.md
- docs/includes/manifest-guidance.md
This PR adds a tip (re maintaining a separate manifest file for each environment) to the following articles:
- https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?branch=kb-updates-re-partner-feedback
- https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview?branch=kb-updates-re-partner-feedback
- https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-naming?branch=kb-updates-re-partner-feedback
(Re work item: https://office.visualstudio.com/OC/_queries/edit/3720618)
> [Manifest] (guidance) Add guidance re maintaining separate manifest file for each environment.

- docs/excel/make-custom-functions-compatible-with-xll-udf.md
There was a statement about how updates are handled that was confusing, so recommendation was to just remove it as it is not applicable.
> [Excel](custom functions) removing confusing xll update statement

- docs/reference/javascript-api-for-office-error-codes.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/1504.
> [Outlook] (errors) Document error 9022

- docs/reference/manifest/desktopsettings.md
- docs/reference/manifest/form.md
- docs/reference/manifest/phonesettings.md
- docs/reference/manifest/tabletsettings.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/1494.
> [Outlook] (manifest) Note restrictions for Form's child elements

- docs/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial.md
There was a step missing to make the tutorial work correctly.
> [Excel](custom functions) Add missing step

- docs/design/using-office-ui-fabric-react.md
- docs/develop/create-sso-office-add-ins-nodejs.md
- docs/develop/develop-add-ins-vscode.md
- docs/includes/quickstart-yo-prerequisites.md
- docs/quickstarts/excel-custom-functions-quickstart.md
- docs/quickstarts/excel-quickstart-angular.md
- docs/quickstarts/excel-quickstart-jquery.md
- docs/quickstarts/excel-quickstart-react.md
- docs/quickstarts/excel-quickstart-vue.md
- docs/quickstarts/onenote-quickstart.md
- docs/quickstarts/powerpoint-quickstart.md
- docs/quickstarts/project-quickstart.md
- docs/quickstarts/sso-quickstart.md
- docs/quickstarts/word-quickstart.md
- docs/tutorials/excel-tutorial-create-custom-functions.md
- docs/tutorials/excel-tutorial.md
- docs/tutorials/word-tutorial.md
Changes made per internal work item # 3890206.
Articles impacted by this change include:
- all quick starts that use Yo Office (e.g., [Excel quick start](https://review.docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?branch=kb-yeoman-node-version&tabs=yeomangenerator) and [SSO quick start](https://review.docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/sso-quickstart?branch=kb-yeoman-node-version))
- all tutorials that use Yo Office (e.g., [Excel tutorial](https://review.docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial?branch=kb-yeoman-node-version) and [Node.js SSO tutorial](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs?branch=kb-yeoman-node-version))
- [Use Office UI Fabric …
> [All hosts] (Yo Office) Updated info about the version of Node.js that's required.

- docs/overview/office-add-in-availability.md
Pointing the requirement set links to the Custom Functions requirement set article. Also clarifying that CFs are only for Excel.
> [excel] (Custom Functions) Fixing CF req set links

- docs/reference/manifest/customtab.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/1558.
> [Manifest] Note that Mac doesn't support CustomTab

- docs/reference/manifest/runtime.md
- docs/reference/manifest/runtimes.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/1560.
> [Manifest] Update links between runtime and runtimes

- docs/reference/javascript-api-for-office-error-codes.md
Related to https://github.com/OfficeDev/office-js-docs-pr/issues/1555.
> [Outlook] (error) Document 9021 SaveError

- docs/reference/manifest/officeapp.md
- docs/reference/manifest/versionoverrides.md
The table in the new **Namespace values** section isn't great looking, but its the least bad way I found for to format this info and express it concisely.
> Minor manifest errors

- docs/reference/requirement-sets/outlook-api-requirement-sets.md
Fixes https://github.com/OfficeDev/outlook-dev-docs/issues/835.
> [Outlook] Link to requirements page

- docs/excel/excel-add-ins-comments.md
- docs/excel/excel-add-ins-events.md
- docs/excel/excel-add-ins-ranges-advanced.md
Reverts OfficeDev/office-js-docs-pr#1591
> Revert "Merge to live!"

- docs/overview/office-add-ins.md
My understanding is that moving this will improve SEO
> [All] (Overview) Fix placement of image on overview page

- docs/reference/requirement-sets/office-add-in-requirement-sets.md
- docs/reference/requirement-sets/shared-runtime-requirement-sets.md
- docs/toc.yml
* [All Hosts] (runtimes) Req Set article for ShareRuntime
* add TOC entry
* Update docs/reference/requirement-sets/shared-runtime-requirement-sets.md
Co-Authored-By: Kim Brandl - MSFT <kbrandl@users.noreply.github.com>
* added version numbers
* added SharedRuntime entry in list of common req sets
* fixing version numbers
* add show-hide api doc
* remove obsolete note
* updating methods in the SharedRuntime req set
Co-Authored-By: Elizabeth Samuel <elizs@microsoft.com>
* revising list of APIs in the req set
* another revision of APIs in the set
* typo
* moving show-hide article to a different branch & PR
* removing from TOC
Co-authored-by: Kim Brandl - MSFT <kbrandl@users.noreply.github.com>
Co-authored-by: Elizabeth Samuel <elizs@microsoft.com>
> [All Hosts] (runtimes) Req Set article for ShareRuntime (#1550)

- docs/outlook/pinnable-taskpane.md
- docs/reference/manifest/action.md
- docs/reference/requirement-sets/outlook-api-requirement-sets.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/1616.
> [Outlook] (pinnable) Clarify pinnable task panes support

- docs/outlook/outlook-mobile-addins.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/1615.
> [Outlook] (bowa) Note that add-ins aren't supported

- docs/design/disable-add-in-commands.md
Also cleaned up other link references.
> [Admin] Remove link to RibbonAPI page

- docs/reference/manifest/extendedpermission.md
- docs/reference/manifest/extendedpermissions.md
- docs/reference/manifest/versionoverrides.md
- docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md
- docs/toc.yml
* [Outlook] (Preview) Append on send
* Include in TOC
* Updates based on feedback
>   [Outlook] (Preview) Append on send (#1644)

- docs/excel/custom-functions-errors.md
Looking for a review to double-check that I'm referring to Office Insider correctly.
> [admin] (Typo) Fixing grammar in Office Insider statement

- docs/excel/excel-add-ins-workbooks.md
- docs/reference/requirement-sets/excel-preview-apis.md
This section asks an article section for the CultureInfo APIs.
> [excel] (CultureInfo) Adding culture info article section

- docs/excel/excel-add-ins-worksheets.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/1690
> [Excel] (snippet) use more appropriate type of loop

- docs/excel/performance.md
The conceptual doc counterpart for https://github.com/OfficeDev/office-js-snippets/pull/415
> [excel] (Performance) Note about screen flickering with suspendScreenUpdatingUntilNextSync

- docs/tutorials/excel-tutorial.md
The Euro symbol wasn't displaying properly in the spreadsheet. This PR fixes it to use the Unicode character.
> [excel] (Tutorial) Fixing currency symbol

- docs/outlook/contextual-outlook-add-ins.md
- docs/reference/manifest/desktopsettings.md
- docs/reference/manifest/extensionpoint.md
- docs/reference/manifest/form.md
- docs/reference/manifest/phonesettings.md
- docs/reference/manifest/requestedheight.md
- docs/reference/manifest/requestedwidth.md
- docs/reference/manifest/tabletsettings.md
Updated ranges and ordering based on info in [mailappversionoverrides/1.1 schema](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-owemxml/8e722c85-eb78-438c-94a4-edac7e9c533a).
> [Manifest] (RequestedHeight) Correct examples

- docs/excel/excel-add-ins-error-handling.md
I couldn't figure out how this list was sorted, so I sorted it alphabetically. I think that'll be easier to reference.
> [excel] (Error codes) Alphabetizing the error codes

- docs/design/disable-add-in-commands.md
This is essentially just a code change in an article that was reviewed recently, so I'm going to merge it myself without another review.
> [Excel] (ui) update for new API shape

- docs/develop/overview-authn-authz.md
- docs/develop/troubleshoot-sso-in-office-add-ins.md
- docs/excel/custom-functions-json-autogeneration.md
- docs/excel/custom-functions-runtime.md
- docs/testing/testing-and-troubleshooting.md
Broken links from OPS weekly report that ran 4/12.
> [Admin] Fix broken links

- docs/index.md
- docs/overview/learning-path-beginner.md
- docs/toc.yml
Everyone's a reviewer. Please comment on each other's comments when you disagree. Thanks.
> Beginner learning path

- docs/excel/configure-your-add-in-to-use-a-shared-runtime.md
Fixes #1751. 
This adds a relevant link to the PnP sample from the appropriate shared runtime article.
> [excel] (Shared Runtime) Linking to the PnP sample

- docs/outlook/online-meeting.md
- docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md
Fixes #1769 
Also, tweak description on prev. reqt. set page.
> [Outlook] (online meeting) Note manifest example is an excerpt

- docs/concepts/browsers-used-by-office-web-add-ins.md
> [Add-ins] (browsers) Include link to ProPlus update history page

- docs/toc.yml
The michelle-sharedRuntime branch is what I'll be pushing all smaller shared runtime specific changes into. In this case, this is just a slight TOC rearrangement, not final because it will change as I change other things.
> Pulling TOC changes into sharedRuntime branch 

- docs/outlook/online-meeting.md
> [Outlook] (typo) Fix manifest excerpt

- docs/outlook/authenticate-a-user-with-an-sso-token.md
- docs/outlook/authentication.md
> [Outlook] (SSO) Note not for production add-ins

- docs/reference/manifest/extensionpoint.md
Related to https://github.com/OfficeDev/office-js-docs-pr/pull/1785.
> [Outlook] (manifest) Fix typo

- docs/publish/publish.md
* Update publish.md
* Update date
Co-authored-by: Elizabeth Samuel <elizs@microsoft.com>
> (typo) Update publish.md (#1811)

- docs/toc.yml
> [All Hosts] (manifest) correct TOC location for Runtime element

- docs/word/search-option-guidance.md
This typo causes compiling error
> [word] (Typo) Update search-option-guidance.md

- docs/testing/ie-11-testing.md
- docs/toc.yml
This is in draft for the moment as I have to add it to a couple places as a link and in the table of contents, but please go ahead and review the text :) Thanks!
> [Add-ins](Testing) IE11 command line tooling

- docs/outlook/outlook-on-send-addins.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/1763.
> [Outlook] (on send) Add support section

- docs/outlook/outlook-on-send-addins.md
* [Outlook] (on send) Add support section
* Tweak formatting
> [Outlook] (on send) Add support section (#1871)

- docs/develop/common-coding-issues.md
Here's the [internal spec describing the issue](https://microsoft.sharepoint.com/:w:/t/OfficePlatform/EeV3Q6rxFkhPvN4bHKiczlMB9Q7GDATVmn77PWa17sY_rQ?e=hp9tLi).
Here's the relevant [UserVoice request](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/39781582-fix-generalexceptions-being-thrown-when-multiple-e).
I'm open to suggestions for organizing the information, now that this article is growing.
> [excel] (Multiple Workbooks) Adding section about multi workbook behavior

- docs/reference/requirement-sets/office-add-in-requirement-sets.md
Staging site link: https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/office-add-in-requirement-sets?branch=AlexJerabek-patch-1#pdffile
> [Common APIs] (PDF) Update Excel support for PdfFile

- docs/publish/publish.md
- docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md
- docs/toc.yml
Also, some small fixes to the Publishing overview
> [All Hosts] (deployment) clarify status of deployment by network share

- docs/reference/overview/visio-javascript-reference-overview.md
- docs/reference/requirement-sets/office-add-in-requirement-sets.md
- docs/toc.yml
- docs/visio/index.md
Also includes the requirement set note change discussed in the same conversation.
> [visio] (Terminology) Removing the use of "add-ins" from Visio docs

- docs/reference/requirement-sets/office-add-in-requirement-sets.md
@mscharlock This was left out of the PR the other day.
> [Excel] (requirement sets) link to RibbonApi from req set overview

- docs/includes/mac-cache-folders.md
- docs/tutorials/excel-tutorial.md
> [Admin] Add Mac cache location

- docs/index.yml
Related to https://github.com/OfficeDev/office-js-docs-pr/pull/1877.
> [Admin] Update landing page

- docs/index.yml
- docs/powerpoint/index.yml
Related to PR https://github.com/OfficeDev/office-js-docs-pr/pull/1931.
> [Admin] Update PowerPoint landing page

- docs/index.yml
- docs/onenote/index.yml
Related to PR https://github.com/OfficeDev/office-js-docs-pr/pull/1930.
> [Admin] Update OneNote landing page

- docs/index.yml
- docs/outlook/index.yml
Related to https://github.com/OfficeDev/office-js-docs-pr/pull/1919.
> [Admin] Update Outlook landing page

- docs/index.yml
- docs/project/index.yml
- docs/reference/overview/powerpoint-add-ins-reference-overview.md
- docs/reference/overview/project-add-ins-reference-overview.md
- docs/toc.yml
Related to PR https://github.com/OfficeDev/office-js-docs-pr/pull/1932.
> [Admin] Update Project landing page

- docs/index.yml
- docs/visio/index.yml
- docs/word/index.yml
Also, small tweak to Visio landing page.
> [Admin] Update Word landing page

- docs/excel/index.yml
- docs/index.yml
- docs/word/index.yml
Related to PR https://github.com/OfficeDev/office-js-docs-pr/pull/1938.
> [Admin] Update Excel landing page

- docs/reference/manifest/appdomain.md
- docs/reference/manifest/appdomains.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/1956
And adds other clarifications.
> [All Hosts] (manifest) add details to AppDomains reference

- docs/testing/attach-debugger-from-task-pane.md
- docs/testing/test-debug-office-add-ins.md
- docs/testing/testing-and-troubleshooting.md
- docs/toc.yml
Apparently this got lost in the Build rush. D'oh
> [Add-ins][TOC] Add debugging article to TOC

- docs/develop/create-sso-office-add-ins-nodejs.md
This is really typo level fixes, so skipping review.
> [All Hosts] (sso) various small fixes

- docs/overview/office-add-in-availability.md
- docs/reference/requirement-sets/office-add-in-requirement-sets.md
> [excel] (Requirement Sets) Support for CompressedFile on Excel is 2016+

- docs/outlook/sideload-outlook-add-ins-for-testing.md
> [Outlook] (sideload) Add instructions for Outlook 2013

- docs/reference/requirement-sets/excel-preview-apis.md
Autogenerated content based on DefinitelyTyped.
> [excel] (Preview APIs) Refreshing Excel preview API table

- docs/excel/configure-your-add-in-to-use-a-shared-runtime.md
Skipping review because this is just a typo that the lead engineer spotted.
> [Excel] (runtimes) typo in file path

- docs/design/authentication-patterns.md
- docs/develop/auth-with-office-dialog-api.md
- docs/develop/create-sso-office-add-ins-aspnet.md
- docs/develop/create-sso-office-add-ins-nodejs.md
- docs/develop/dialog-api-in-office-add-ins.md
- docs/develop/overview-authn-authz.md
- docs/develop/sso-in-office-add-ins.md
- docs/develop/troubleshoot-sso-in-office-add-ins.md
- docs/includes/sso-tutorial-prereqs.md
- docs/overview/set-up-your-dev-environment.md
- docs/publish/host-an-office-add-in-on-microsoft-azure.md
- docs/quickstarts/sso-quickstart-customize.md
- docs/quickstarts/sso-quickstart.md
- docs/tutorials/migrate-vsto-to-office-add-in-shared-code-library-tutorial.md
> Scrub Office 365 continued

- docs/excel/performance.md
> [excel] (Range) Removing single property setting section in Perf article

- docs/index.yml
Per bug [3993611](https://office.visualstudio.com/OC/_workitems/edit/3993611)
> add resource links

- docs/develop/create-sso-office-add-ins-aspnet.md
Just a typo so no review needed.
> [All Hosts] (auth) typo in SSO walkthrough

- docs/develop/create-sso-office-add-ins-aspnet.md
This fixes a copy paste mistake so it doesn't need a review.
> [All Hosts] (sso) remove miscopied sentence

- docs/develop/common-coding-issues.md
- docs/excel/co-authoring-in-excel-add-ins.md
This PR adds some best practice guidance for avoiding coauth merge conflicts resulting from table row additions.
> [excel] (Coauth) Table row coauth issues

- docs/outlook/outlook-add-ins-overview.md
- docs/outlook/privacy-and-security.md
- docs/outlook/troubleshoot-outlook-add-in-activation.md
- docs/outlook/use-regular-expressions-to-show-an-outlook-add-in.md
- docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md
* [Outlook] (IRM) Support now in preview
* Updates based on feedback
* Update ms.date
* Note feature in preview
> [Outlook] (IRM) Supported now in preview (#2049)

- docs/reference/javascript-api-for-office-error-codes.md
This error codes incorrectly reference a data limit imposed by the add-in, instead of by the Office application.
> [Common API] (Errors) Update error code messages

- docs/excel/make-custom-functions-compatible-with-xll-udf.md
> [admin] (Typo) Fix closing tag in XML example

- docs/excel/configure-your-add-in-to-use-a-shared-runtime.md
- docs/excel/custom-functions-overview.md
- docs/excel/custom-functions-shared-overview.md
- docs/includes/shared-runtime-note.md
- docs/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial.md
We originally had left this info just in the Runtimes element but apparently nobody is finding it so now I put it all over the place!
> [Add-ins][Shared Runtime] Making sure a note about IE11 is prominent

- docs/outlook/outlook-on-send-addins.md
Related to issue https://github.com/OfficeDev/office-js/issues/1249.
> [Outlook] (on send) Describe workaround to prevent editing the item

- docs/outlook/get-and-set-recurrence.md
Related to issue https://github.com/OfficeDev/office-js/issues/1327.
> [Outlook] (recurrence) Add example of how to change recurrence

- docs/outlook/outlook-add-ins-overview.md
- docs/outlook/privacy-and-security.md
- docs/outlook/troubleshoot-outlook-add-in-activation.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2031.
> [Outlook] (IRM) Add-ins work with digitally signed messages

- docs/outlook/append-on-send.md
- docs/outlook/autolaunch.md
- docs/quickstarts/outlook-quickstart.md
- docs/tutorials/outlook-tutorial.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2114.
> [Outlook] (npm) Add note about handling error

- docs/outlook/authenticate-a-user-with-an-sso-token.md
- docs/outlook/authentication.md
- docs/outlook/get-attachments-of-an-outlook-item.md
- docs/outlook/implement-sso-in-outlook-add-in.md
Update links to renamed Outlook sample and add links to the article that the sample is based on.
> Outlook sso sample

- docs/excel/excel-add-ins-workbooks.md
A conceptual article section discussing [this new set of APIs](https://docs.microsoft.com/en-us/javascript/api/excel/excel.worksheet?view=excel-js-preview#customproperties).
> [excel] (Properties) Add a section about worksheet-level custom properties

- docs/testing/troubleshoot-manifest.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2142
Purely a technical correction from the PM, so this doesn't need a peer review.
> [All Hosts] (manifest) missing step in validation tool instructions

- docs/includes/office-js-access-library.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2146
> [All Hosts] (apis) typo in case sensitive URL

- docs/design/add-in-typography.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2032.
> [Add-ins] (typography) Remove inaccessible images

- docs/outlook/compare-outlook-add-in-support-in-outlook-for-mac.md
Includes support for ItemChanged event
> [Outlook] (new Mac) Now supports pinnable task pane, SSO

- docs/design/using-office-ui-fabric-react.md
- docs/outlook/append-on-send.md
- docs/outlook/autolaunch.md
- docs/quickstarts/onenote-quickstart.md
- docs/quickstarts/outlook-quickstart.md
- docs/quickstarts/sso-quickstart-customize.md
- docs/quickstarts/sso-quickstart.md
- docs/tutorials/outlook-tutorial.md
Also remove unnecessary notes since error should no longer be thrown.
> [Admin] (yo) Update to run dev-server where applicable

- docs/develop/create-sso-office-add-ins-aspnet.md
- docs/develop/create-sso-office-add-ins-nodejs.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2155
This is too trivial to need a review.
> [All Hosts] (sso) clarify note in walkthroughs

- docs/toc.yml
Seems like a "no-brainer" so I'm merging without a review.
> [All Hosts] (common apis) Move the binding article to Common from Word

- docs/testing/troubleshoot-manifest.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2193.
> [Admin] (typo) Fix command

- debug.log
- docs/outlook/outlook-add-ins-overview.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2183.
> [Outlook] Clarify how to activate add-ins

- docs/testing/sideload-office-add-ins-for-testing.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2200
> [All Hosts] (testing) update Edge loopback instructions

- docs/reference/requirement-sets/open-browser-window-api-requirement-sets.md
Alternative link: [/javascript/api/office/office.ui](https://docs.microsoft.com/javascript/api/office/office.ui)
> [Admin] Fix broken link

- docs/excel/custom-functions-errors.md
- Add CF 1.3 ErrorCode enum values 
- Adjust phrasing per 1.3 updates 
- Remove preview !Note from beginning of article
> [Excel] (Custom Functions 1.3) Update error handling article

- docs/outlook/outlook-on-send-addins.md
Helps address issue https://github.com/OfficeDev/office-js-docs-pr/issues/2208.
> [Outlook] (on-send) Clarify support

- docs/quickstarts/outlook-quickstart.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2199.
> [Outlook] (quick start) Clarify how to activate add-in

- docs/outlook/use-rest-api.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2166.
> [Outlook] (REST) Warn about CORS issue with AJAX and on-prem Exchange

- docs/concepts/browsers-used-by-office-web-add-ins.md
- docs/testing/sideload-office-add-ins-for-testing.md
Review changes from other PRs that came in after the PRs were approved/merged.
> [All Hosts] (browsers) small fixes

- docs/excel/custom-functions-json-autogeneration.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2222.
Includes typo fix and minor cleanup.
> [Custom functions] Fix anchor tags

- docs/excel/custom-functions-runtime.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2224.
> [Custom functions] (typo) Fix note format

- docs/testing/runtime-logging.md
@mscharlock @davidchesnut @alison-mk  The main change here is the supported Office version in the first NOTE. Everything else is minor cleanup.
> [Add-ins] (runtime) Supported versions

- docs/excel/pnp-open-in-excel.md
We recommend using SSO rather than an auth token, as the auth token approach comes with a security risk.
> [Excel](PnP) update security section

- docs/tutorials/outlook-tutorial.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2179.
> [Outlook] (tutorial) Fix instructions to update webpack config

- docs/concepts/privacy-and-security.md
Related to issue https://github.com/OfficeDev/office-js-docs-pr/issues/2243.
> Remove unnecessary statement

- docs/excel/excel-add-ins-comments.md
Adding comment events article section, with sub-sections and samples for onAdded, onChanged, and onDeleted events.
> [Excel] (Comments) Add comment events article section

- docs/excel/excel-add-ins-comments.md
* [Excel] (Comments) Add comment events article section
* Streamline comment event code samples
* Streamline samples, adjust onChanged description
* Adjust onDeleted description, improve grammar
* Add detail to comment events intro
Co-authored-by: Alex Jerabek <38896772+AlexJerabek@users.noreply.github.com>
* Incorporate changes from code review
* Incorporate suggestions from code review
* Remove typescript syntax from comment event samples
* Adjust notes per feedback
Co-authored-by: Alex Jerabek <38896772+AlexJerabek@users.noreply.github.com>
* Adjust section intro and comment addition sample description
* Clarify onChanged and onDeleted sample descriptions
* Apply change from code review
Co-authored-by: Elizabeth …
> [Excel] (Comments) Add comment events article section (#2245)

- docs/excel/excel-add-ins-ranges-advanced.md
This PR adds a Trace formula precedents section to the Range (Advanced) article.
> [Excel] (Range) Add formula precedents article section

- docs/excel/excel-add-ins-error-handling.md
Adding new error codes `RequestPayloadSizeLimitExcceded` and `ResponsePayloadSizeLimitExcceded`. Also adding other existing error codes that were missing from docs, and updating article title.
> [Excel] Add new error codes

- docs/design/keyboard-shortcuts.md
This PR removes some non-space characters and replaces them with spaces. This was causing problems when copied into code.
> Remove invalid characters

- docs/quickstarts/sso-quickstart.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2260.
> [Outlook] (SSO) Fix quick start instructions

- docs/design/office-ui-fabric.md
Fixes #2283 
This PR corrects the line recommending Fabric components your an add-in. It, instead, specifies that the given list is a general recommendation, instead of a more exclusionary list.
> [ui] (Fabric) Updating guidance about Fabric UI control selection

- docs/outlook/authentication.md
> [Outlook](authentication) remove preview now that sso is ga

- docs/outlook/add-and-remove-attachments-to-an-item-in-a-compose-form.md
Addresses request to note requirement set for get APIs by customer in this [SO thread](https://stackoverflow.com/questions/64738149/office-js-getattachmentsasync-fails-in-client).
> [Outlook] (attachments) Note reqt. set for get APIs in compose mode

- docs/includes/mac-cache-folders.md
- docs/tutorials/excel-tutorial.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2323.
> [Cache] (Mac) Update folder paths

- docs/publish/centralized-deployment.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2328.
> [CD] Clarify how to update LOB add-ins

- docs/reference/requirement-sets/excel-preview-apis.md
Updated with autogenerated content from https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/requirement-set-tables/excel-preview.md
> [excel] (Preview APIs) Update Excel preview table

- docs/outlook/autolaunch.md
Fixes https://github.com/OfficeDev/office-js/issues/1512.
> [Outlook] (autolaunch) getAccessToken not supported

- docs/outlook/outlook-on-send-addins.md
Related to issues https://github.com/OfficeDev/office-js/issues/1381, https://github.com/OfficeDev/office-js/issues/1484
Also, remove Preview tag from append-on-send feature mention.
> [Outlook] (on-send) Note OWA popout behavior

- docs/reference/objectmodel/preview-requirement-set/office.context.md
- docs/reference/objectmodel/requirement-set-1.1/office.context.md
- docs/reference/objectmodel/requirement-set-1.2/office.context.md
- docs/reference/objectmodel/requirement-set-1.3/office.context.md
- docs/reference/objectmodel/requirement-set-1.4/office.context.md
- docs/reference/objectmodel/requirement-set-1.5/office.context.md
- docs/reference/objectmodel/requirement-set-1.6/office.context.md
- docs/reference/objectmodel/requirement-set-1.7/office.context.md
- docs/reference/objectmodel/requirement-set-1.8/office.context.md
- docs/reference/objectmodel/requirement-set-1.9/office.context.md
Related PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49929
> [Outlook] (context.host) Not available in 1.1

- docs/reference/objectmodel/preview-requirement-set/office.context.md
- docs/reference/objectmodel/requirement-set-1.1/office.context.md
- docs/reference/objectmodel/requirement-set-1.2/office.context.md
- docs/reference/objectmodel/requirement-set-1.3/office.context.md
- docs/reference/objectmodel/requirement-set-1.4/office.context.md
- docs/reference/objectmodel/requirement-set-1.5/office.context.md
- docs/reference/objectmodel/requirement-set-1.6/office.context.md
- docs/reference/objectmodel/requirement-set-1.7/office.context.md
- docs/reference/objectmodel/requirement-set-1.8/office.context.md
- docs/reference/objectmodel/requirement-set-1.9/office.context.md
* [Outlook] (context.host) Not available in 1.1
* Updates
* Updates based on feedback on related PR
> [Outlook] (context.host) Not available in 1.1 (#2346)

- docs/excel/excel-add-ins-pivottables.md
- docs/reference/requirement-sets/excel-api-1-10-requirement-set.md
This PR: 
- Adds a new "Filter with PivotFilters" article section and series of code samples  
- Adds an introductory "Filter a PivotTable" article section, to encompass both slicers and PivotFilters  
Note to reviewers: I think the introductory "Filter a PivotTable" paragraph should include another sentence about the benefits of PivotFilters vs. slicers, but I'm not sure what to note as the most compelling PivotFilter feature. Open to suggestions!
> [Excel] (PivotTables) Add new PivotFilter article section

- docs/excel/custom-functions-parameter-options.md
This PR addresses Github issue #2238.
> [Excel] (Custom Functions) Clarify Range parameters article section

- docs/excel/excel-add-ins-troubleshooting.md
This PR adds documentation for a series of bugs and issues: 
- Binding Events ID discrepancy
- Cell format useStandardHeight and useStandardWidth issue
- Range return character limit (a follow-up to Issue #2255) 
- Range getImage method
> [Excel] (Troubleshooting) Add Known Issues article section

- docs/develop/create-sso-office-add-ins-aspnet.md
- docs/includes/register-sso-add-in-aad-v2-include.md
> [All hosts](SSO) Update UI descriptions to match latest

- docs/reference/requirement-sets/dialog-api-requirement-sets.md
fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2388
trivial fix needs no review.
> [All Hosts] (dialog) fix link to messageChild

- docs/reference/manifest/enabled.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2376
> [Excel] (manifest) enabled element only valid in Excel

- docs/concepts/browsers-used-by-office-web-add-ins.md
Doesn't require Insiders anymore.
> Webview2 now used in monthly channel. 

- docs/excel/excel-add-ins-error-handling.md
Adding InactiveWorkbook error code and message per request from PM.
> [Excel] (Error codes) Add InactiveWorkbook error code and message

- .openpublishing.redirection.json
Need to add a redirect for old page location at https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime
> add redirect

- docs/excel/excel-add-ins-tables.md
This PR addresses issue #2412. Using approved term [memory leak](https://termstudio.azurewebsites.net/viewdata.aspx?tid=171592&langCode=English).
> [Exce] (Tables) Update Table article to note content add-in memory issue

- .openpublishing.publish.config.json
- docs/excel/excel-add-ins-error-handling.md
- docs/powerpoint/insert-slides-into-presentation.md
- docs/reference/requirement-sets/powerpoint-api-1-1-requirement-set.md
- docs/reference/requirement-sets/powerpoint-api-1-2-requirement-set.md
- docs/reference/requirement-sets/powerpoint-api-requirement-sets.md
- docs/reference/requirement-sets/powerpoint-preview-apis.md
- docs/toc.yml
There will be a parallel PR, with the same branch name, in the -reference repo. They should publish roughly in sync so that the ToCs are integrated.
> [PowerPoint] (apis) GA of insert slides and req set 1.2

- docs/toc.yml
@ElizabethSamuel-MSFT We fixed the bug dropping `?view=<X>` on redirects.  Let me know if you see any other issues!
> Links: Office JS (2021-01a)

- docs/outlook/get-attachments-of-an-outlook-item.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2414.
> [Outlook] (attachments) Note other get options in Read mode

- .openpublishing.redirection.json
Related to PR https://github.com/OfficeDev/office-js-docs-pr/pull/2420.
> [Admin] (redirects) Remove redirects no longer used by TOC

- docs/excel/excel-add-ins-error-handling.md
Updating NonBlankCellOffSheet error message to align with the corresponding Excel UI error message, per conversation with PM/Eng.
> [Excel] (Error messages) Update NonBlankCellOffSheet error message

- docs/overview/office-add-in-availability.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2425
> #2425 - Updated references for Excel supported platforms

- docs/quickstarts/excel-quickstart-jquery.md
Addressing issue #2430.
Note to reviewers: **ExcelWebAddIn1** is the default Visual Studio 2019 project name.
> [Excel] (Quickstart) Update VS2019 path, manifest step

- docs/concepts/browsers-used-by-office-web-add-ins.md
technical change that doesn't need a review
> [All Hosts] (browsers) correct build number for WebView2

- docs/outlook/autolaunch.md
Related to issue https://github.com/OfficeDev/office-js-docs-pr/issues/2446.
> [Outlook] (autolaunch) Update lifetime length

- docs/excel/excel-add-ins-pivottables.md
[Internal work item](https://office.visualstudio.com/OC/_workitems/edit/4697626/).
> [Excel] (PivotTables) Add backticks to Pivot*Filter references

- docs/outlook/add-mobile-support.md
Related to issue https://github.com/OfficeDev/office-js-docs-pr/issues/2389.
> [Outlook] (mobile) Expand link description

- docs/testing/clear-cache.md
Given the popularity of this article, we should ensure it's accuracy in localized doc sets.
> [admin] (Localization) Upgrade loc priority for Cache Clearing article

- docs/develop/dialog-api-in-office-add-ins.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2457
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2461
**Note to reviewers:** the list of samples is not alphabetical. The principles I used were to put the most basic samples at the top of the list, archived samples at the end of the list, and the rest organized by host where possible.
> [All Hosts] (dialog) adding list of samples to main dialog article

- .openpublishing.redirection.json
- docs/toc.yml
We want the user to be taken to the reference section instead of remaining in the conceptual so reintroducing these redirects.
> [Admin] Fix TOC links to reference

- docs/index.yml
This PR transforms the current Office Add-ins 'Landing' page index.yml to a 'Hub' page format.
> [All] (Hub page)

- docs/index.yml
Accessibility and SEO updates per internal review.
> [All] (Hub page) Accessibility and SEO updates

- docs/excel/excel-add-ins-troubleshooting.md
Updating per feedback from editor.
> [Excel] (Troubleshooting) Switch tense to simple present

- docs/reference/requirement-sets/excel-preview-apis.md
Update Preview APIs intro/summary table to include formula changed events.
> [Excel] (Preview APIs) Add formula changed events to intro table

- docs/outlook/use-rest-api.md
Lost [this change](https://github.com/OfficeDev/outlook-dev-docs/pull/256) for issue https://github.com/OfficeDev/office-js/issues/140 at some point.
> [Outlook] (REST) Add note

- docs/powerpoint/add-slides.md
- docs/powerpoint/insert-slides-into-presentation.md
- docs/toc.yml
Also moves the "Delete slides" section from the "Insert slides" article to the new "Add slides" article.
> [PowerPoint] (slides) APIs for adding slides

- docs/develop/itp-and-third-party-cookies.md
- docs/toc.yml
This is a new article on working with ITP and third-party cookies
> [All Hosts](Security) ITP and third-party cookies

- docs/reference/requirement-sets/word-api-1-3-requirement-set.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2555
> [Word] (1.3) No custom XML

- docs/reference/requirement-sets/excel-api-1-5-requirement-set.md
- docs/reference/requirement-sets/excel-api-1-8-requirement-set.md
@alison-mk Looks like these tables were slightly corrupted so this is FYI.
> [Admin] Fix build suggestions

- docs/develop/itp-and-third-party-cookies.md
- docs/excel/custom-functions-json-autogeneration.md
Monthly links cleanup. /cc @ElizabethSamuel-MSFT
> Links: Office JS (2021-03)

- docs/design/add-in-icons-fresh.md
- docs/reference/manifest/icon.md
Related to issue https://github.com/OfficeDev/office-js-docs-pr/issues/2572.
> [Icons] Add See also section to guidelines

- docs/develop/create-sso-office-add-ins-aspnet.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2550
> Aspnet sso tutorial

- Contributing.md
- Issue_Template.md
- README.md
- docs/docfx.json
> [Admin] Replace UserVoice with Q&A

- docs/reference/requirement-sets/excel-api-online-requirement-set.md
- docs/reference/requirement-sets/excel-preview-apis.md
Pulling latest from DefinitelyTyped.
> [Excel] (requirement sets) Update Preview and Online API lists

- docs/design/add-in-icons-fresh.md
- docs/design/add-in-icons-monoline.md
- docs/reference/manifest/highresolutioniconurl.md
- docs/reference/manifest/icon.md
- docs/reference/manifest/iconurl.md
- docs/reference/manifest/resources.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2572.
> Add-in icon: 64 px required

- docs/concepts/browsers-used-by-office-web-add-ins.md
> [All Hosts] (browsers) link fix

- docs/develop/configure-your-add-in-to-use-a-shared-runtime.md
> [All Hosts](shared runtime) add 'true' value to yo office command

- docs/overview/office-add-in-availability.md
- docs/reference/requirement-sets/open-browser-window-api-requirement-sets.md
* Note availability of newer requirement sets
* List WXPO as supported apps on OpenBrowserWindowApi reqt. set page
* Clarifications
> Note availability of newer requirement sets (#2608)

- docs/excel/custom-functions-debugging.md
Updating article based on customer issue #2597.
> [Excel] (Custom Functions) Clarify runtimes in UI-less debugging article

- Issue_Template.md
- README.md
- docs/resources/resources-links-help.md
Updating the feature request links to point to Tech Community. @lindalu-MSFT, is this accurate guidance for our customers in the post-UserVoice world?
> [admin] (Resources) Updating feature request guidance

- docs/excel/excel-add-ins-pivottables.md
This PR documents some new 1.13 PivotLayout features (and some older ones that never received conceptual documentation). 
It also removes some arbitrary spaces in the article.
> [excel] (PivotTable) PivotLayout features

- Issue_Template.md
- README.md
- docs/excel/custom-functions-debugging.md
- docs/excel/excel-add-ins-pivottables.md
- docs/resources/resources-links-help.md
* [Excel] (Custom Functions) Clarify runtimes in UI-less debugging article
Co-authored-by: Michelle Scharlock <mischarl@microsoft.com>
* Adjust description of UI-less custom functions
* Fix link
* Adjust capitalization
Co-authored-by: Michelle Scharlock <mischarl@microsoft.com>
> [Admin] Publish

- docs/powerpoint/tagging-presentations-slides-shapes.md
- docs/toc.yml
[PowerPoint] (tags) work with tags
> [PowerPoint] (tags) work with tags

- docs/excel/excel-add-ins-cells.md
Removing list of APIs that mention cells, based on internal conversation.
> [Excel] (Cells) Update article based on internal feedback

- docs/develop/itp-and-third-party-cookies.md
Minor update to ensure consistent usage of WKWebView throughout article.
> [All Hosts](Security) Minor update for consistent terminology

- docs/excel/custom-functions-debugging.md
@alison-mk we should check that this is only for desktop and not available online as well
> Update from Adam/Igor about CF UI-less

- docs/excel/excel-add-ins-events.md
Fixes https://github.com/OfficeDev/office-js-docs-pr/issues/2635
> [Excel] Fix incorrect function name

- docs/design/office-ui-fabric.md
- docs/develop/add-ins-with-angular2.md
Fixes https://github.com/OfficeDev/office-js/issues/1757
> [Add-ins] (Angular) Nullify certain window.history APIs for IE compatibility
